temp/objects/Access_Request__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Access Requests</relationshipLabel>
        <relationshipName>Access_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Access Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Access Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Access_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Access_Request_ID__c</fullName>
        <label>Access Request ID</label>
        <referenceTo>Access_Request__c</referenceTo>
        <relationshipLabel>Access Request Line Items</relationshipLabel>
        <relationshipName>Access_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Access_Request_Type__c</fullName>
        <label>Access Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authentication</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Mainframes</fullName>
                </value>
                <value>
                    <fullName>MYSQL</fullName>
                </value>
                <value>
                    <fullName>Oracle</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Sybase</fullName>
                </value>
                <value>
                    <fullName>Unix</fullName>
                </value>
                <value>
                    <fullName>Windows</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Type__c</fullName>
        <label>Access Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Root Access</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Pre-Production</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested User</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Access Request Line Items</relationshipLabel>
        <relationshipName>Access_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <formula>Access_Request_ID__r.SOE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SOE</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Access Request Line Item</label>
    <nameField>
        <displayFormat>ARLI-{0000}</displayFormat>
        <label>Access Request Line Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Access_Request_Cntrl.cls
@isTest
public class Test_Access_Request_Cntrl{
    static Testmethod void Add_AccessRequest_LineItems_Cntrl(){
    
        Test.StartTest();
        SOEUtility.SystemSettings_Insert();
        Department__c  service1 = SOEUtility.Dep_Insert('Service1');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        user user1 = SOEUtility.user_insert('user--11@gmail.com');
        Member__c member = [select id from Member__c where Email__c ='user--11@gmail.com'];
        SOE__c SOE = SOEUtility.SOE_Insert('SOE--1dadsd',service1.Id,true,true,false,false);  
        System.assertEquals(SOE.SOE_Title__c , 'SOE--1dadsd');
        Access_Request__c AR = new Access_Request__c(SOE__c = SOE.ID, Start_Time__c = System.today().adddays(2), End_Time__c = System.today().adddays(4));
        Insert AR;
        ApexPages.CurrentPage().getparameters().put('Id', AR.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(new Access_Request__c());
        Add_AccessRequest_LineItems_Cntrl ARLI = new Add_AccessRequest_LineItems_Cntrl(sc);
        arli.WrapperList[0].ARLI.Access_Request_Type__c = 'Other';
        arli.WrapperList[0].ARLI.Environment__c = 'Other' ;
        arli.WrapperList[0].ARLI.Access_Type__c = 'Other' ;
        arli.SaveLineItems();
        arli.WrapperList[0].ARLI.Start_Time__c = System.Today();
        arli.WrapperList[0].ARLI.End_Time__c = System.Today().addDays(2);
        arli.SaveLineItems();
        arli.WrapperList[0].ARLI.Start_Time__c = System.Today();
        arli.WrapperList[0].ARLI.End_Time__c = System.Today().addDays(-2);
        arli.SaveLineItems();
        arli.EntryCount  =0;
        arli.DeleteRow();
        arli.AddRow();
        arli.WrapperList[0].ARLI.Start_Time__c = System.Today().adddays(2);
        arli.WrapperList[0].ARLI.End_Time__c = System.Today().addDays(3);
        arli.WrapperList[0].ARLI.Requested_User__c = UserInfo.getUSerId();
        arli.SaveLineItems();
        Access_Request_Line_Item__c ARLI1 = New Access_Request_Line_Item__c(Access_Request_ID__c = AR.ID, Start_Time__c = System.today().adddays(1), End_Time__c = System.today().adddays(3));
        Insert ARLI1;
        ARLI = new Add_AccessRequest_LineItems_Cntrl(sc);
        arli.EntryCount =0;
        arli.DeleteRow();
        arli.SaveLIneItems();     
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitrequest();
        app.setComments('Approve.');
        app.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        app.setObjectId(AR.Id);
        Approval.ProcessResult result = Approval.process(App);
        arli = new Add_AccessRequest_LineItems_Cntrl(sc);
        arli.AddRow();
        arli.EntryCount  =0;
        arli.DeleteRow();
        arli.CancelPage();
        Test.StopTest();
 
    }
}