temp/objects/Access_Request__c.object
<CustomObject>
    <fields>
        <fullName>Clone_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone ID</label>
        <referenceTo>Access_Request__c</referenceTo>
        <relationshipLabel>Access Request</relationshipLabel>
        <relationshipName>Access_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deactivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Domain_ID__c</fullName>
        <label>Domain ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Access_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Description__c</fullName>
        <label>Request Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Raised_Status__c</fullName>
        <label>Request Raised Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Access Requests</relationshipLabel>
        <relationshipName>Access_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Task</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Task__c.SOE__c</field>
                <operation>equals</operation>
                <valueField>$Source.SOE__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Access Request</relationshipLabel>
        <relationshipName>Access_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Access Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Access_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ACR_Type_Other__c</fullName>
        <label>ACR Type Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Dropped__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Access Dropped Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_Granted_Status__c</fullName>
        <label>Access Granted Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Request_ID__c</fullName>
        <label>Access Request ID</label>
        <referenceTo>Access_Request__c</referenceTo>
        <relationshipLabel>Access Request Line Items</relationshipLabel>
        <relationshipName>Access_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Access_Request_Type__c</fullName>
        <label>Access Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authentication</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Mainframes</fullName>
                </value>
                <value>
                    <fullName>MYSQL</fullName>
                </value>
                <value>
                    <fullName>Oracle</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Sybase</fullName>
                </value>
                <value>
                    <fullName>Unix</fullName>
                </value>
                <value>
                    <fullName>Windows</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Type_Other__c</fullName>
        <label>Access Type Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Type__c</fullName>
        <label>Access Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Root Access</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Verified__c</fullName>
        <label>Access Verified Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application_Access__c</fullName>
        <label>Application Access</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Environment_Other__c</fullName>
        <label>Environment Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Pre-Production</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Raised__c</fullName>
        <label>Request Raised</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_User_ID__c</fullName>
        <label>Requested User ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested User</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Access Request Line Items</relationshipLabel>
        <relationshipName>Access_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <formula>Access_Request_ID__r.SOE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SOE</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Access Request Line Item</label>
    <nameField>
        <displayFormat>ARLI-{0000}</displayFormat>
        <label>Access Request Line Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Add_AccessRequest_LineItems_Cntrl.cls
/* 
Class Name        : Add_AccessRequest_LineItems_Cntrl 
Test Class Name   : Test_Access_Request_Cntrl
Purpose/Overview  : To Add Line Items to Access Request
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class Add_AccessRequest_LineItems_Cntrl {
    public string errormessage {get;set;}
    public Access_Request__c AR {get; set;}
    Public Id RequestId{get;set;}
    public List<wrapclass> WrapperList{get;set;} 
    public integer EntryCount{get;Set;}
    public boolean output{get;set;}
    public list<Access_Request_Line_Item__c> DeleteLIstARLI{get;set;}
    public list<Access_Request_Line_Item__c> Orig_ARLIMap;

    public Add_AccessRequest_LineItems_Cntrl(ApexPages.StandardController controller) {
        RequestId = ApexPAges.CurrentPage().getParameters().get('id');
        output = false;
        errormessage = null;
        if(Utils.isAccessible('I8__Access_Request__c') && Utils.isAccessible('I8__Access_Request_Line_Item__c')){
             Orig_ARLIMAp = new list<Access_Request_Line_Item__c>();
             DeleteLIstARLI = new list<Access_Request_LIne_Item__c>();
             if(Schema.sObjectTYpe.ProcessInstance.isAccessible())
             AR = [select id,name,(select id,name,Access_Granted_Status__c,Requested_User_ID__c,Overall_Status__c,Requested_User__c ,Access_Dropped__c,Request_Raised__c,Access_Verified__c,ACR_Type_Other__c,Access_Type_Other__c,
                End_Time__c,Start_Time__c,Environment_Other__c,Access_Request_ID__c,Access_Request_Type__c,Access_Type__c,Additional_Comments__c,Application_Access__c,Environment__c from Access_Request_Line_Items__r order by name)
                Domain_ID__c,Domain__c,Deactivate__c,Implementation_Manager__c,End_Time__c,Clone_ID__c,Start_Time__c,Request_Description__c,Request_Raised_Status__c,
                SOE__c,Task__c,(select status from ProcessInstances order by createddate desc) from Access_Request__c where id =: RequestId];
            if(AR.Access_Request_Line_Items__r.SIze() > 0){
                  AddToWrapperLIst(AR.Access_Request_Line_Items__r);
                  for (Access_Request_Line_Item__c arli : AR.Access_Request_Line_Items__r)
                      Orig_ARLIMap.add(arli.clone(true,true,false,true));
            } else
                  AddRow();
             If(AR.ProcessInstances.size() > 0 && AR.ProcessInstances[0].status == 'Pending')
                    output = true;
         }
         else { errormessage = System.Label.ADMIN001;}
    }
    public void AddToWrapperLIst(list<Access_Request_Line_Item__c> AREntrylist ){
        WrapperList = new list<wrapclass>();   
        integer count =0;     
        for(Access_Request_Line_Item__c ARE: AREntrylist){                         
            WrapperList.add(new wrapclass(ARE,count));
            count++;
        }  
    }
    public class wrapclass{
        public Integer counterWrap{get;set;}  
        public Access_Request_Line_Item__c ARLI {get; set;}
        public wrapclass(Access_Request_Line_Item__c LI,integer c){       
            this.ARLI=LI;
            this.counterWrap=c;
        }
    }  
    public void addRow(){ 
        if(WrapperList == null)
             WrapperList = new list<wrapclass>(); 
        WrapperLIst.Add(new wrapclass(new Access_Request_Line_Item__c(Request_Raised__c = AR.Request_Raised_Status__c),WrapperLIst.Size()));
    }  
    public void DeleteRow(){
        for(Integer i=0; i < WrapperLIst.size(); i++){
            if(WrapperLIst[i].counterWrap == EntryCount){
                if(WrapperLIst[i].ARLI.Id != null)
                    DeleteLIstARLI.add(WrapperLIst[i].ARLI);
                WrapperLIst.remove(i);
            }
        }
        list<wrapclass> WrapperList1 = new list<wrapclass>();
        for(Integer i=0; i < WrapperLIst.size(); i++)
             WrapperLIst1.add(new wrapclass(wrapperlist[i].ARLI,i));
        WrapperLIst.clear();
        WrapperLIst.AddAll(WrapperLIst1);   
    }
    public pagereference SaveLineItems(){
        Boolean displayError = False;
        boolean bool = false;
        errorMessage = null;
        list<Access_Request_line_Item__c> LIstARLI = new list<Access_Request_LIne_Item__c>();
        try{
            list<Access_Request_Line_Item__c> InsertList = new list<Access_Request_Line_Item__c>();
            list<Access_Request_Line_Item__c> UpdateList = new list<Access_Request_Line_Item__c>();
            for(Integer i=0; i < WrapperList.size(); i++){
                WrapperLIst[i].ARLI.Access_Request_ID__c = RequestId;
                if(WrapperList[i].ARLI.Id == null)
                    insertList.add(WrapperList[i].ARLI);
                else 
                    UpdateList.add(WrapperLIst[i].ARLI);
            }
             if( Utils.isCreateable('i8__Access_Request_Line_Item__c')) {
                 for(Access_Request_Line_Item__c arli : InsertLIst){
                    bool = ARLI_Validations(arli);
                    if(bool == true )
                        return null;
                 }  
                 if(InsertList.Size() > 0 && Utils.isCreateable('i8__Access_Request_Line_Item__c'))                    
                         insert InsertList;
            }  
            else if(InsertList.Size() > 0){  displayError = true;     errorMessage = System.Label.AddTask006;   }
            list<Access_Request_Line_Item__c> arlilist1 = new list<Access_Request_Line_Item__c>();
            if( Utils.isUpdateable('i8__Access_Request_Line_Item__c')   ) {              
                 for(Access_Request_Line_Item__c arli : UpdateList){
                    bool = ARLI_Validations(arli);
                    if(bool == true )
                        return null;
                    else {
                        for(Access_Request_Line_Item__c  arli1 : Orig_ARLIMap){
                            if(arli.Id == arli1.Id && arli != arli1)
                                arlilist1.add(arli);
                        }                        
                    }                    
                 } 
                 if(arlilist1.Size() > 0 && Utils.isUpdateable('i8__Access_Request_Line_Item__c'))                    
                         update arlilist1;
            }  
            else if(arlilist1.Size() > 0){
                 displayError = true;  
                 errorMessage =    System.Label.AddTask007 ;               
            }    
                 if(DeleteLIstARLI.Size() > 0){
                    if(Schema.sObjectType.Access_Request_Line_Item__c.isDeletable())
                        delete DeleteLIstARLI;
                    else {  displayError = true;  errorMessage =    System.Label.AddTask008 ;  }
                 }
                 if(displayError == False)
                    return new pagereference('/'+RequestId);
        }catch(Exception e){
           LogFactory.error('Access_Request_Cntrl', 'SaveLineItems', '', e.getMessage() + '' + e.getStackTraceString());         
           errorMessage = e.getMessage();
           LogFactory.SaveLog();
        }
        return null;
    }
    public boolean ARLI_Validations(Access_Request_Line_Item__c arli){
        boolean bool = false;
        If(ARLI.Start_Time__c == null ){
            ARLI.Start_Time__c.adderror(System.Label.AccessRequest001);
            bool = true;
        }
        If(ARLI.End_Time__c == null){
           ARLI.End_Time__c.adderror(System.Label.AccessRequest002);
            bool = true;
        }
        If(ARLI.End_Time__c < ARLI.Start_Time__c){
            ARLI.End_Time__c.adderror(System.Label.AccessRequest003);
            bool = true;
        }
        If(ARLI.Start_Time__c < AR.Start_Time__c || ARLI.End_Time__c > AR.End_Time__c){
            ARLI.Start_Time__c.adderror(System.Label.AccessRequest004);
            bool = true;
        }                
        If(String.isempty(ARLI.Requested_User__c)){
            ARLI.Requested_User__c.adderror(System.Label.AccessRequest005);
            bool = true;
        }
        If((ARLI.Access_Request_Type__c == 'Other') && (ARLI.ACR_Type_Other__c== NULL || ARLI.ACR_Type_Other__c== '')){
            ARLI.ACR_Type_Other__c.adderror(System.Label.AccessRequest006);
            bool = true;
        }
        If((ARLI.Environment__c == 'Other') && (ARLI.Environment_Other__c== NULL || ARLI.Environment_Other__c== '')){
            ARLI.Environment_Other__c.adderror(System.Label.AccessRequest007);
            bool = true;
        }  
        If((ARLI.Access_Type__c == 'Other') && (ARLI.Access_Type_Other__c== NULL || ARLI.Access_Type_Other__c== '')){
            ARLI.Access_Type_Other__c.adderror(System.Label.AccessRequest008);
            bool = true;
        }
        return bool;
    }
    public pagereference CancelPage(){
        return new pagereference('/'+RequestId);
    }
}