temp/objects/Broadcast__c.object
<CustomObject>
    <fields>
        <fullName>All_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Broadcasts</relationshipLabel>
        <relationshipName>Broadcasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>This_SOE_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>This SOE Users</label>
        <type>Checkbox</type>
    </fields>
    <label>Broadcast</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Broadcast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <formula>Team_Member__r.Salesforce_User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Id</label>
        <type>Text</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/User.object
<CustomObject>
    <fields>
        <fullName>Broadcast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broadcast</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

temp/classes/Broadcast_TriggerHandler.cls
/* 
Class Name        : Broadcast_TriggerHandler 
Trigger Name      : Broadcast_Trigger
Test Class Name   : Test_Broadcast_TriggerHandler
Purpose/Overview  : Trigger Handler for Broadcast Trigger.
                    When Broadcast message is inserted or updated, it is available for All Users or with in that SOE USers based on field in broadcast.
Author            : Purview Ltd.
Code Coverage     : Trigger Handler - 100%
                    Trigger - 100%
Change History    : 

*/
public class Broadcast_TriggerHandler {
    public static void Afterupdate (Map<Id,Broadcast__c> oldMap,Map<Id,Broadcast__c> newMap,string context){
        set<id> soeid = new set<id>();
        list<User> userUpdate = new list<user>();
        Boolean Alluser = false;
        if(Utils.isAccess_Update('User')){
            for(Broadcast__c bc:newMap.values()){
                if( bc.All_Users__c == true && (context == 'insert' || (bc != oldMap.get(bc.Id) && context == 'update')))
                    Alluser = true;
                else if(bc.This_SOE_Users__c == true && (context == 'insert' || (bc != oldMap.get(bc.Id) && context == 'update')))
                   soeid.add(bc.SOE__c);
            }
            if(Alluser == true){
                for(User u : [SELECT Id,Broadcast__c FROM User WHERE Broadcast__c = false and isActive = true]){
                    u.Broadcast__c = true;
                    userUpdate.add(u);  
                }              
            }
            else { 
                set<Id> UserIds = new set<Id>();   
                if(Utils.isAccessible('i8__SOE_Team_Member__c'))
                for(SOE_Team_Member__c soeteam : [SELECT Id,User_Id__c FROM SOE_Team_Member__c WHERE SOE__c IN :soeid])
                    UserIds.add(soeteam.User_Id__c ); 
                if(Utils.isAccessible('i8__Task__c'))
                for(Task__c tas : [select id,Owner__r.Member__r.Salesforce_User__c from Task__c where SOE__c =: soeid]){
                    if(tas.Owner__c != null && tas.Owner__r.Member__r.Salesforce_User__c != null)
                        UserIds.add(tas.Owner__r.Member__r.Salesforce_User__c);
                } 
                for(User u : [SELECT Id,Broadcast__c FROM User WHERE Broadcast__c = false and isActive = true and ID IN : UserIds]){
                    u.Broadcast__c = true;
                    userUpdate.add(u);  
                }                     
           }
           try{
           if(userUpdate.Size() > 0 && Utils.isUpdateable('User'))
               UPDATE userUpdate;
           }Catch(EXception e){
                LogFactory.error('Broadcast_triggerHandler','AfterUpdate','',e.getMessage()+''+e.getSTackTraceString());
                LogFactory.Savelog();
            } 
        } 
        else{LogFactory.debug('Broadcast_TriggerHandler', 'AfterUpdate', 'User Info', System.Label.ADMIN001,'Line - 54');
        LogFactory.SaveLog();}
    }
}