temp/objects/Broadcast__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Broadcasts</relationshipLabel>
        <relationshipName>Broadcasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Broadcast</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Broadcast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/User.object
<CustomObject>
    <fields>
        <fullName>Broadcast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broadcast</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

temp/classes/Test_MIS_AllTasks_Cntrl.cls
// class :   SatckGantt_Chart_Cntrl

@istest
Public class Test_MIS_AllTasks_Cntrl {
    Public static i8Constants i8 = new I8Constants();
     @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
        Department__c service = SOEUtility.Dep_Insert('Service2');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('MIS All TAsk 1',service.id,true,true,false,false);
        System.assertEquals(soe.SOE_Title__c, 'MIS All TAsk 1'); 
    }
    Static testmethod void Test_MIS_AllTasks_Cntrl1 (){
        test.StartTest();
         user user1 = SOEUtility.user_insert('user--15@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--15@gmail.com'];
        Team__c Team1=SOEUtility.Team_insert('sap');
        Team_Member__c Teammember1=SOEUtility.Teammember_insert(member1.id,Team1.id);
        MIS__c mis = SOEUtility.MIS_Insert('MIS insetrt1');
        System.assertEquals(mis.MIS_Title__c, 'MIS insetrt1');
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='MIS All TAsk 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'MIS All TAsk 1');
        list<Task__c> tas = [select id,Id_Text__c from Task__c where soe__c =: soe.Id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c];
        SOE.MIS__c = mis.id;
        update soe;
        ApexPages.CurrentPage().getparameters().put('Id', mis.Id);
        MIS_AllTasks_Cntrl All = new MIS_AllTasks_Cntrl();
        tas[4].Team__c = Team1.Id;
        tas[4].Owner__c = Teammember1.Id;
        update tas[4];
        MIS_AllTasks_Cntrl.getTasks('select id,Owner__c,SOE__c from Task__c ','',mis.Id,10,0);
        ApexPages.CurrentPage().getparameters().put('input1', soe.id); 
        All.UpdateTasks();
        ApexPages.CurrentPage().getparameters().put('ActiveId', tas[4].Id);  
        ApexPages.CurrentPage().getparameters().put('input1', soe.id); 
        All.ActivateTask1();
        All.CompleteTask();      
        Test.StopTest();
        soe.Status__c = i8.STATUS_IMPINPROGRESS;
        update soe;
        ApexPages.CurrentPage().getparameters().put('Id', mis.Id);
        All = new MIS_AllTasks_Cntrl();        
        soe.Status__c = i8.STATUS_IMP_COMP;
        update soe;
        ApexPages.CurrentPage().getparameters().put('Id', mis.Id);
        All = new MIS_AllTasks_Cntrl();        
        soe.Status__c = i8.STATUS_SOE_COMP;
        update soe;
        ApexPages.CurrentPage().getparameters().put('Id', mis.Id);
        All = new MIS_AllTasks_Cntrl();
        All.Cancel(); 
    }
    Static testmethod void Test_MIS_AllTAsks_Cntrl2 (){
        test.StartTest();
        MIS__c mis = SOEUtility.MIS_Insert('MIS insetrt1');
        System.assertEquals(mis.MIS_Title__c, 'MIS insetrt1');
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='MIS All TAsk 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'MIS All TAsk 1');
        list<Task__c> tas = [select id,Id_Text__c from Task__c where soe__c =: soe.Id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c];
        SOE.MIS__c = mis.id;
        update soe;
        BroadCast__c br = SOEUtility.Broadcast_Insert('this is one message');
        ApexPages.CurrentPage().getparameters().put('id', mis.Id);
        MIS_AllTasks_Cntrl All = new MIS_AllTasks_Cntrl();
        ApexPages.CurrentPage().getparameters().put('ActiveId', tas[4].Id);  
        All.ReRunTask();
        All.BroadCastOnOff();
        All.BroadCastOnOff();
        ApexPages.CurrentPage().getparameters().put('tas', tas[4].Id); 
        ApexPages.CurrentPage().getparameters().put('body1','this is sample message'); 
        All.AddPINtoTask();
        All.openListIncidents();
        All.openListOpenIncidents();
        All.openListClosedIncidents();
        All.openMISDashboards();
        All.openCreateIncident();
        All.openAddDocuments();
        All.openModifyTask(); 
        All.openAllDocuments();
        All.openResourceROTA();
        All.openHistoryPage();
        All.openMyView();  
        All.openTaskGanttChart();
        All.openResourceGanttChart();    
        Test.StopTest();      
    }
     Static testmethod void Test_MIS_AllTAsks_Cntrl3 (){
        test.StartTest();
        MIS__c mis = SOEUtility.MIS_Insert('MIS insetrt1');
        System.assertEquals(mis.MIS_Title__c, 'MIS insetrt1');
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='MIS All TAsk 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'MIS All TAsk 1');
        list<Task__c> tas = [select id,Id_Text__c from Task__c where soe__c =: soe.Id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c];
        SOE.MIS__c = mis.id;
        update soe;
        ApexPages.CurrentPage().getparameters().put('id', mis.Id);
        MIS_AllTasks_Cntrl All = new MIS_AllTasks_Cntrl();
        All.RerunTask();
        All.ActivateTask1();
        All.CompleteTask();
        All.CreateCall();
        All.CreateSMS();
        All.UpdateTasks();
        Test.StopTest();
     }
     Static testmethod void Test_StackGanttChart_Cntrl (){
        test.StartTest();
        MIS__c mis = SOEUtility.MIS_Insert('MIS insetrt1');
        System.assertEquals(mis.MIS_Title__c, 'MIS insetrt1');
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='MIS All TAsk 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'MIS All TAsk 1');
        list<Task__c> tas = [select id,Id_Text__c from Task__c where soe__c =: soe.Id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c];
        SOE.MIS__c = mis.id;
        update soe;
        ApexPages.CurrentPage().getparameters().put('id', mis.Id);
        StackGanttChart_Cntrl  All = new StackGanttChart_Cntrl ();
        StackGanttChart_Cntrl.getTasks(mis.Id);
        All.OpenCancel();
        Test.StopTest();      
    }
}