temp/objects/Broadcast__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Broadcasts</relationshipLabel>
        <relationshipName>Broadcasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>This_SOE_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>This SOE Users</label>
        <type>Checkbox</type>
    </fields>
    <label>Broadcast</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Broadcast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/Broadcast_New_Cntrl.cls
/* 
Class Name        : Broadcast_New_Cntrl 
Test Class Name   : Test_Broadcast_New_Cntrl
Purpose/Overview  : To insert Broadcast message from SOE-All TasksConsole
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class Broadcast_New_Cntrl {
    public BroadCast__c bc {get;set;}
    Public id SOEId{get;set;}
    public Boolean error{get;set;}
    public String errorMessage{get;set;}
    public Broadcast_New_Cntrl (){
        error=false;
        SOEId = apexPages.CurrentPage().getparameters().get('id');
         if(Utils.isCreateable('i8__BroadCast__c')){
        bc = new BroadCast__c();
        bc.Status__c = 'Active'; 
        }else {  errormessage = System.LABEL.AddTASK006;error = true;}       
    }   
    public pagereference Save(){
        Savepoint sp = Database.setSavepoint();
        try{
            if(Utils.isCreateable('I8__BroadCast__c')){
                if(bc.This_SOE_Users__c== true)
                    bc.SOE__c = SOEId;
                LogFactory.info('Broadcast_New_Cntrl ', 'SaveMethod', 'Broadcast', JSON.Serialize(bc),'Line - 26');  
                LogFactory.SaveLog();            
                if(UTils.isCReateable('i8__Broadcast__c'))
                    insert bc;
                return new pagereference('/apex/AllTasks_ClientSide?id='+SOEId);
            }
            else { errorMessage = System.Label.AddTask006; error = true; }
            return null;
        }
        catch(DMLException e)
        {
            errorMessage = e.getDmlMessage(0);
            error = true;
            Database.rollback(sp);
            LogFactory.error('Broadcast_New_Cntrl ', 'SaveMethod', '', e.getMessage() + '' + e.getStackTraceString());  
            LogFactory.SaveLog(); 
            return null;
        }        
    }
    public pagereference Cancel(){
        return new pagereference('/apex/AllTasks_ClientSide?id='+SOEId);
    }
}