temp/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Additinal_Emails_Milestone__c</fullName>
        <label>Additinal Emails Milestone</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additinal_Emails_Task_Ready__c</fullName>
        <label>Additinal Emails Task Ready</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Emails_Completed__c</fullName>
        <label>Additional Emails Completed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Phone_Completed__c</fullName>
        <label>Additional Phone Completed</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Phone_Milestone__c</fullName>
        <inlineHelpText>,(comma) separated mails</inlineHelpText>
        <label>Additional Phone Milestone</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Phone_Task_Ready__c</fullName>
        <label>Additional Phone Task Ready</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed_Mails__c</fullName>
        <label>Completed Mails</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed_Members__c</fullName>
        <label>Completed Members</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed_Phones__c</fullName>
        <label>Completed Phones</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Default_Owner_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Owner Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Owner_Task_ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Owner Task ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MileStone_for_default_Imp_Mngrs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MileStone for default Imp Mngrs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone_Mails__c</fullName>
        <label>Milestone Mails</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Milestone_Members__c</fullName>
        <label>Milestone Members</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Milestone_Phones__c</fullName>
        <label>Milestone Phones</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <formula>Task__r.Milestone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ready_Mails__c</fullName>
        <label>Ready Mails</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ready_Phones__c</fullName>
        <label>Ready Phones</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Completed__c</fullName>
        <formula>Task__r.Task_Completed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Ready_Members__c</fullName>
        <label>Task Ready Members</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Ready__c</fullName>
        <formula>Task__r.When_Task_Ready__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <inlineHelpText>Country code(2 digits only) followed by Phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Task Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Communication_TriggerHandler.cls
/* 
Class Name        : Communication_TriggerHandler
Trigger Name      : Communication_Trigger
Test Class Name   : Test_Communication_TriggerHandler
Purpose/Overview  : To Update Phone and Email Fields in a Single Field.
Author            : Purview Ltd.
Code Coverage     : Trigger Handler - 87%.
                    Trigger - 100%
Change History    : 
*/
public class Communication_TriggerHandler {
    public static void BeforeInsert(list<Communication__c> ComList,string context,Map<id,Communication__c> ComMap){
        if(Utils.isCreateable('i8__Communication__c'))
            UpdateMailsPhones(ComList,context,ComMap);
        else {
            LogFactory.debug('Communication_TriggerHandler', 'Before Insert', 'CommunicationInfo', System.Label.AddTask006 ,'Line - 16');
            LogFactory.SaveLog();
        }
    }
    public static void BeforeUpdate(list<Communication__c> ComList,string context,Map<id,Communication__c> ComMap){
        if(Utils.isUpdateable('i8__Communication__c'))
            UpdateMailsPhones(ComList,context,ComMap);
        else {
            LogFactory.debug('Communication_TriggerHandler', 'Before Update', 'Communication Info', System.Label.AddTask007 ,'Line - 24');
            LOgFactory.SaveLog();
        }
    }
    public static void UpdateMailsPhones(list<Communication__c> ComList,string context,Map<id,Communication__c> ComMap){
        set<id> SOEIds = new set<ID>();
        set<id> TaskIds = new set<ID>();
        list<string> MemberIds = new list<string>();
        for(Communication__c com : ComList){
            if( com.Milestone__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.MileStone_for_default_Imp_Mngrs__c != ComMap.get(com.id).MileStone_for_default_Imp_Mngrs__c ) ||
                (context == 'update' && com.Milestone_Members__c != ComMap.get(com.id).Milestone_Members__c) ||
                (context == 'update' && com.Additinal_Emails_Milestone__c != ComMap.get(com.id).Additinal_Emails_Milestone__c ) ||
                (context == 'update' && com.Additional_Phone_Milestone__c != ComMap.get(com.id).Additional_Phone_Milestone__c)  
            )){
                if(com.MileStone_for_default_Imp_Mngrs__c == true   )
                    SOEIds.add(com.SOE__c);   
                if(com.Milestone_Members__c != null )
                     MemberIds.AddAll(com.Milestone_Members__c.split(','));
            }
            if( com.Task_Ready__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.Default_Owner_Task_ready__c != ComMap.get(com.id).Default_Owner_Task_ready__c) ||
                (context == 'update' && com.Task_Ready_Members__c != ComMap.get(com.id).Task_Ready_Members__c) ||
                (context == 'update' && com.Additinal_Emails_Task_Ready__c != ComMap.get(com.id).Additinal_Emails_Task_Ready__c) ||
                (context == 'update' && com.Additional_Phone_Task_Ready__c != ComMap.get(com.id).Additional_Phone_Task_Ready__c)  
            )){
                if(com.Default_Owner_Task_ready__c == true   )
                    TaskIds.add(com.Task__c);   
                if(com.Task_Ready_Members__c != null )
                     MemberIds.AddAll(com.Task_Ready_Members__c.split(','));
            }
            if( com.Task_Completed__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.Default_Owner_Completed__c != ComMap.get(com.id).Default_Owner_Completed__c) ||
                (context == 'update' && com.Completed_Members__c != ComMap.get(com.id).Completed_Members__c) ||
                (context == 'update' && com.Additional_Emails_Completed__c != ComMap.get(com.id).Additional_Emails_Completed__c) ||
                (context == 'update' && com.Additional_Phone_Completed__c != ComMap.get(com.id).Additional_Phone_Completed__c )  
            )){
                if(com.Default_Owner_Completed__c == true   )
                    SOEIds.add(com.SOE__c);   
                if(com.Completed_Members__c != null )
                     MemberIds.AddAll(com.Completed_Members__c.split(','));
            }
        }
        Map<id,Task__c> TaskMap ;
        if(Utils.isAccessible('i8__Task__c'))
           TaskMap = new Map<Id,Task__c>([select id,Owner__c,Owner__r.Member__r.Email__c,Owner__r.Member__r.Phone__c from Task__c where id IN: TaskIds]);
        Map<Id,Member__c> MemberMap;
        if(Utils.isAccessible('i8__Member__c'))
           MemberMap = new Map<Id,Member__c>([select id,Name,Email__c,Phone__c from Member__c where Id IN : MemberIds]);
        Map<Id,list<SOE_Team_Member__c >> SOEManagersMap = new Map<Id,list<SOE_Team_Member__c>>();
        if(Utils.isAccessible('i8__SOE_Team_Member__c'))      
            for(SOE_Team_Member__c  member : [select id, name,Team_Member__c,Team_Member__r.Email__c,Team_Member__r.Phone__c,SOE__c  from SOE_Team_Member__c where SOE__C In : SOEIds]){
                if(! SOEManagersMap.containskey(member.SOE__c))
                   SOEManagersMap.put(member.SOE__c,new list<SOE_Team_Member__c >()); 
                SOEManagersMap.get(member.SOE__c).add(member);
            }
        for(communication__c com : ComList){
            if(com.Milestone__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.MileStone_for_default_Imp_Mngrs__c != ComMap.get(com.id).MileStone_for_default_Imp_Mngrs__c ) ||
                (context == 'update' && com.Milestone_Members__c != ComMap.get(com.id).Milestone_Members__c) ||
                (context == 'update' && com.Additinal_Emails_Milestone__c != ComMap.get(com.id).Additinal_Emails_Milestone__c )  ||
                (context == 'update' && com.Additional_Phone_Milestone__c != ComMap.get(com.id).Additional_Phone_Milestone__c)
            )){
                com.Milestone_Mails__c ='';
                com.Milestone_Phones__c ='';
                if(com.MileStone_for_default_Imp_Mngrs__c == true){
                    for(SOE_Team_Member__c  member : SOEManagersMap.get(com.SOE__c)){
                        if(member.Team_Member__r.Email__c != null && ! com.Milestone_Mails__c.contains(member.Team_Member__r.Email__c))
                            com.Milestone_Mails__c += member.Team_Member__r.Email__c+','; 
                        if( member.Team_Member__r.Phone__c != null && ! com.Milestone_Phones__c .contains(member.Team_Member__r.Phone__c))
                            com.Milestone_Phones__c += member.Team_Member__r.Phone__c+',';                          
                    }
                }
                if(com.Milestone_Members__c != null){
                    for(string str : com.Milestone_Members__c.split(',')){
                        if(MemberMap.get(str).Email__c != null && ! com.Milestone_Mails__c.contains(MemberMap.get(str).Email__c))
                            com.Milestone_Mails__c += MemberMap.get(str).Email__c+','; 
                        if(MemberMap.get(str).Phone__c != null  && ! com.Milestone_Phones__c .contains(MemberMap.get(str).Phone__c))
                            com.Milestone_Phones__c += MemberMap.get(str).Phone__c+','; 
                    }
                }
                if(com.Additinal_Emails_Milestone__c != null){
                    for(string str : com.Additinal_Emails_Milestone__c.split(',')){
                        if(! com.Milestone_Mails__c.contains(str))
                            com.Milestone_Mails__c += str+',';
                    }
                }                
                 if(com.Additional_Phone_Milestone__c != null){
                    for(string str : com.Additional_Phone_Milestone__c.split(',')){
                        if(! com.Milestone_Phones__c .contains(str))
                            com.Milestone_Phones__c += str+',';  
                    }
                }
            } // end -----if
            if( com.Task_Ready__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.Default_Owner_Task_ready__c != ComMap.get(com.id).Default_Owner_Task_ready__c) ||
                (context == 'update' && com.Task_Ready_Members__c != ComMap.get(com.id).Task_Ready_Members__c) ||
                (context == 'update' && com.Additinal_Emails_Task_Ready__c != ComMap.get(com.id).Additinal_Emails_Task_Ready__c) ||
                (context == 'update' && com.Additional_Phone_Task_Ready__c != ComMap.get(com.id).Additional_Phone_Task_Ready__c)  
            )){
                com.Ready_Mails__c ='';
                com.Ready_Phones__c ='';
                if(com.Default_Owner_Task_ready__c == true){
                    if( TaskMap.get(com.Task__c).Owner__c != null && ! com.Ready_Mails__c.contains(TaskMap.get(com.Task__c).Owner__r.Member__r.Email__c))
                        com.Ready_Mails__c += TaskMap.get(com.Task__c).Owner__r.Member__r.Email__c+','; 
                    if(TaskMap.get(com.Task__c).Owner__c != null && ! com.Ready_Phones__c.contains(TaskMap.get(com.Task__c).Owner__r.Member__r.Phone__c))
                        com.Ready_Phones__c += TaskMap.get(com.Task__c).Owner__r.Member__r.Phone__c+',';                          
                 }
                if(com.Task_Ready_Members__c != null){
                    for(string str : com.Task_Ready_Members__c.split(',')){
                        if(MemberMap.get(str).Email__c != null && ! com.Ready_Mails__c.contains(MemberMap.get(str).Email__c))
                            com.Ready_Mails__c += MemberMap.get(str).Email__c+','; 
                        if(MemberMap.get(str).Phone__c != null && ! com.Ready_Phones__c.contains(MemberMap.get(str).Phone__c))
                            com.Ready_Phones__c += MemberMap.get(str).Phone__c+','; 
                    }
                }
                if(com.Additinal_Emails_Task_Ready__c != null){
                    for(string str : com.Additinal_Emails_Task_Ready__c.split(',')){
                        if(! com.Ready_Mails__c.contains(str))
                            com.Ready_Mails__c+= str+',';
                    }
                }                
                 if(com.Additional_Phone_Task_Ready__c != null){
                    for(string str : com.Additional_Phone_Task_Ready__c.split(',')){
                        if(! com.Ready_Phones__c.contains(str))
                            com.Ready_Phones__c += str+',';  
                    }
                }
                
            } // end --------if
            if( com.Task_Completed__c == true &&  ( context == 'insert' || 
                (context == 'update' && com.Default_Owner_Completed__c != ComMap.get(com.id).Default_Owner_Completed__c) ||
                (context == 'update' && com.Completed_Members__c != ComMap.get(com.id).Completed_Members__c) ||
                (context == 'update' && com.Additional_Emails_Completed__c != ComMap.get(com.id).Additional_Emails_Completed__c) ||
                (context == 'update' && com.Additional_Phone_Completed__c != ComMap.get(com.id).Additional_Phone_Completed__c )  
            )){
                com.Completed_Mails__c ='';
                com.Completed_Phones__c ='';
                if(com.Default_Owner_Completed__c == true){                    
                    for(SOE_Team_Member__c  member : SOEManagersMap.get(com.SOE__c)){
                        if( member.Team_Member__r.Email__c!= null &&  ! com.Completed_Mails__c.contains(member.Team_Member__r.Email__c))
                            com.Completed_Mails__c += member.Team_Member__r.Email__c+','; 
                        if( member.Team_Member__r.Phone__c != null && ! com.Completed_Phones__c.contains(member.Team_Member__r.Phone__c))
                            com.Completed_Phones__c += member.Team_Member__r.Phone__c+',';                          
                    }                         
                 }
                if(com.Completed_Members__c != null){
                    for(string str : com.Completed_Members__c.split(',')){
                        if(MemberMap.get(str).Email__c != null && ! com.Completed_Mails__c.contains(MemberMap.get(str).Email__c))
                            com.Completed_Mails__c+= MemberMap.get(str).Email__c+','; 
                        if(MemberMap.get(str).Phone__c != null && ! com.Completed_Phones__c.contains(MemberMap.get(str).Phone__c))
                            com.Completed_Phones__c+= MemberMap.get(str).Phone__c+','; 
                    }
                }
                if(com.Additional_Emails_Completed__c != null){
                    for(string str : com.Additional_Emails_Completed__c.split(',')){
                        if(! com.Completed_Mails__c.contains(str))
                            com.Completed_Mails__c+= str+',';
                    }
                }                
                 if(com.Additional_Phone_Completed__c != null){
                    for(string str : com.Additional_Phone_Completed__c.split(',')){
                        if(! com.Completed_Phones__c.contains(str))
                            com.Completed_Phones__c+= str+',';  
                    }
                }
            } // end------------if
        }
    }
}