temp/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <formula>Task__r.Milestone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jump__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Jump</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Link</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Detail__c</fullName>
        <label>Technical Detail</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Task_TriggerHandler.cls
@istest
public class Test_Task_TriggerHandler{
public static I8Constants i8 = new I8Constants();
    @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
           Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
           role = [select id,Reference_Role__c  from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
           System.assertEquals(role.Reference_Role__c , 'Imp Manager');
    }
    static testmethod void Test_Task_Triggerhandeler(){
       
        Department__c  service1 = SOEUtility.Dep_Insert('1Service1');
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,true,false,false);           
        System.assertEquals(SOE.SOE_Title__c , 'newsoetemp');
        list<Task__c> tas = [select id,Id_TExt__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        tas[1].Minutes__c = 10;
        tas[1].Jump__c = true;
        update tas[1];
        SOE__c SOE1 = SOEUtility.SOE_Insert('newsoetemp11190',service1.Id,true,true,true,false,false);
        list<Task__c> tas1 = [select id,Id_TExt__c,Minutes__c from TASk__c where SOE__c =: Soe1.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        ApexPages.CurrentPage().getparameters().put('SOEId',soe.Id);
        ApexPages.CurrentPage().getparameters().put('Id', TAS[1].Id);
        Test.StartTest();
        Add_Task_cntrl Add = new Add_Task_cntrl ();
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T3');
        Add.NewTask.Link__c = true;
        Add.CreateTask();
       
        ApexPages.CurrentPage().getparameters().put('Id', TAS[1].Id);
        Add = new Add_Task_cntrl ();
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T4');
        Add.CreateTask();
         ApexPages.currentPage().getParameters().put('page','SOE');
         ApexPages.currentPage().getParameters().put('Tid',tas[2].Id); 
            Manage_Dependencies_Cntrl  ManageDep=new Manage_Dependencies_Cntrl ();           
            manageDep.PrevTaskId = tas[1].Id;
            ManageDep.Add_Dependency();
            manageDep.LinkTask();
            manageDep.selectSOE = soe1.Id;
            manageDep.PrevTaskId = tas1[1].Id;
            ManageDep.Add_Dependency();
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        soe.Schedule_Start__c = System.Now()+1;
        soe.Schedule_End__c = soe.Schedule_Start__c.AddHours(2);
        soe.Warning_Zone__c = soe.Schedule_End__c.AddHours(2);
        soe.Schedule_End__c = soe.Warning_Zone__c.AddHours(2);
        soe.status__c = i8.STATUS_SCHEDULED;
        update soe;
          Test.StopTest();
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        ApexPages.currentPage().getParameters().put('ID',SOE.Id);      
        AllTasks_ClientSide_cntrl AllTasks = New AllTasks_ClientSide_cntrl();        
        AllTasks.SOEFreeze();
    }
    static testmethod void Test_Task_Triggerhandeler1(){
        Test.startTest();
        Department__c  service1 = SOEUtility.Dep_Insert('1Service1');
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,true,false,false);           
        System.assertEquals(SOE.SOE_Title__c , 'newsoetemp');
        SOE.Status__c = 'Freeze';
        Update SOE;
        list<Task__c> tas2 = [select id,Id_TExt__c,Status__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage__c =: I8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        ApexPages.CurrentPage().getparameters().put('SOEId',soe.Id);
        ApexPages.CurrentPage().getparameters().put('Id', TAS2[1].Id);
        Add_Task_cntrl Add = new Add_Task_cntrl ();
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T4');
        Add.CreateTask();
         
        ApexPages.currentPage().getparameters().put('SId',SOE.Id);
        ApexPages.currentPage().getparameters().put('Id',Tas2[1].Id);
        Modify_Task_cntrl Modify = New Modify_Task_cntrl();
        Modify.CurTask.Task_Title__c = 'Freeze Task';
        Modify.CurTask.Days__c = 12;
        Modify.CurTask.Technical_Detail__c = 'Freeze Detail';
        Modify.CurTask.Description__c = 'Freeze Description';
        Modify.CurTask.Milestone__c = True;
        Modify.SaveTask();   
        Test.stopTest();
    }
     static testmethod void Test_Task_Triggerhandeler2(){       
        Department__c  service1 = SOEUtility.Dep_Insert('1Service1');
        Role__c rol = [select id,Reference_Role__c  from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,true,false,false);           
        list<Task__c> tas = [select id,Id_TExt__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        Communication__c com = SOEUtility.COMM_Insert(tas[2].id,soe.id,true,'dsdad@gmail.com','','','');
        tas[1].Status__c = i8.STATUS_RUNNING;
        tas[1].End_time__c = System.Now().adddays(-1);
        update tas[1];
          tas[2].Milestone__c = true;
          update tas[2];
         System.assertEquals(tas[1].Status__c,  i8.STATUS_RUNNING);
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);        
        tas[1].Status__c = i8.STATUS_COMPLETED;
        tas[2].Status__c = i8.STATUS_COMPLETED;
        update tas;
        Test.StartTest();
        ApexPages.CurrentPage().getparameters().put('SOEId',soe.Id);
        ApexPages.CurrentPage().getparameters().put('Id', TAS[4].Id);
        Add_Task_cntrl Add = new Add_Task_cntrl ();
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T3');
        Add.NewTask.Link__c = true;
        Add.CreateTask();       
        ApexPages.CurrentPage().getparameters().put('Id', TAS[4].Id);
        Add = new Add_Task_cntrl ();
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T3');
        Add.NewTask.Link__c = true;
        Add.CreateTask();       
        tas = [select id,Id_TExt__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        tas[5].Jump__c = true;
        update tas[5];
        tas[4].Jump__c = true;
        update tas[4];
        tas[4].Jump__c = False;
        update tas[4];
        soe.Status__c = i8.STATUS_FREEZE;
        update soe;
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        delete tas[6];
        Test.StopTest();
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);       
        soe.Schedule_Start__c = System.Now().addMinutes(-2);
        soe.Schedule_End__c = soe.Schedule_Start__c.AddHours(2);
        soe.Warning_Zone__c = soe.Schedule_End__c.AddHours(2);
        soe.Schedule_End__c = soe.Warning_Zone__c.AddHours(2);
        soe.status__c = i8.STATUS_IMPINPROGRESS;
        update soe;
        tas = [select id,Id_TExt__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        tas[4].Status__c = i8.STATUS_COMPLETED;
        update tas[4];
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        tas[6].Status__c = i8.STATUS_COMPLETED;
        update tas[6];
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);  
     }
      static testmethod void Test_Task_Triggerhandeler3(){
        Test.startTest();
        Department__c  service1 = SOEUtility.Dep_Insert('1Service1');
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,true,false,false);           
        System.assertEquals(SOE.SOE_Title__c , 'newsoetemp');
        SOE.Status__c = 'Freeze';
        Update SOE;
        list<Task__c> tas2 = [select id,Id_TExt__c,Status__c,Minutes__c from TASk__c where SOE__c =: Soe.id and Stage__c =: I8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
      
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        soe.Status__c = i8.STATUS_IMPINPROGRESS;
        update soe;
        Create_Incident.SOE_ReExe = true;
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);        
         soe.Status__c = i8.STATUS_ABANDONED;
        update soe;
        Task_triggerHandler.UpdateAllTAsks(new list<id>{soe.id},i8.CONTEXT_IMP);
        Test.StopTest();
    }
    static testmethod void Test_Task_Triggerhandeler4(){
        Test.startTest();
        Department__c  service1 = SOEUtility.Dep_Insert('1Service1');
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetempa',service1.Id,true,true,true,false,false);           
        System.assertEquals(SOE.SOE_Title__c , 'newsoetempa');
        list<Task__c> tas = [select id,Id_TExt__c,Status__c,Minutes__c,SOE__c,Id_Before_Decimal__c from TASk__c where SOE__c =: Soe.id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_decimal__c,Id_After_decimal__c];
        user user1 = SOEUtility.user_insert('user--161@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--161@gmail.com'];
        Team__c Team1=SOEUtility.Team_insert('sap');
        Team_Member__c Teammember1=SOEUtility.Teammember_insert(member1.id,Team1.id);
        tas[1].Team__c = team1.id;
        tas[1].Owner__c = teammember1.id;
        tas[1].PIN__c = '2017-01-09 08:44:11-xaxaxa1321:sample message';
        update tas[1];
        Test.StopTest();
     }
}