temp/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Additinal_Emails_Milestone__c</fullName>
        <label>Additinal Emails Milestone</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additinal_Emails_Task_Ready__c</fullName>
        <label>Additinal Emails Task Ready</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Phone_Milestone__c</fullName>
        <inlineHelpText>,(comma) separated mails</inlineHelpText>
        <label>Additional Phone Milestone</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Phone_Task_Ready__c</fullName>
        <label>Additional Phone Task Ready</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Default_Owner_Task_ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Owner Task ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MileStone_for_default_Imp_Mngrs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MileStone for default Imp Mngrs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone_Members__c</fullName>
        <label>Milestone Members</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <formula>Task__r.Milestone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Ready_Members__c</fullName>
        <label>Task Ready Members</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>When_Task_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>When Task Ready</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_Communication_TriggerHandler.cls
@istest
Public class Test_Communication_TriggerHandler {
    @testSetup static void setup() {
        SOEUtility.SystemSettings_Insert();
        Department__c service = SOEUtility.Dep_Insert('Service2');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('Task Communication 1',service.id,true,true,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'Task Communication 1');      
    }
    Static testmethod void Comm_Milestone(){ 
        Test.StartTest();     
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='Task Communication 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'Task Communication 1'); 
        list<task__c> Tas = [select id,name,Task_Title__c,SOE__c,Stage_Level__c,Stage__c,Team__c,Owner__c from task__c where SOE__c =: SOE.id order by ID_Before_Decimal__c,Id_After_Decimal__c];      
        Communication__c  com = SOEUtility.COMM_Insert(tas[1].id,soe.id,false,null,null,null,null);
        tas[1].Milestone__c = true;
        update tas[1];
         User user1 = SOEUtility.USer_Insert('user--39--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--39--@gmail.com'];
        Role__c role = [select id from ROle__c where Reference_Role__c = 'Imp Manager' limit 1];
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Edit',soe.id,role.id);
        Member__c member2 = SOEUtility.Member_Insert('member1',null,'918978478545','membermail@gmail.com');
        com.MileStone_for_default_Imp_Mngrs__c  = true;
        update com;
        com.Milestone_Members__c = member2.id;
        update com;
        com.Additinal_Emails_Milestone__c ='gsfdg@gmail.com';
        update com;
        com.Additional_Phone_Milestone__c  ='9178974851412';
        update com;
        Test.StopTest();
     }
     Static testmethod void Comm_TaskReady(){ 
        Test.StartTest();     
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='Task Communication 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'Task Communication 1'); 
        list<task__c> Tas = [select id,name,Task_Title__c,SOE__c,Stage_Level__c,Stage__c,Team__c,Owner__c from task__c where SOE__c =: SOE.id order by ID_Before_Decimal__c,Id_After_Decimal__c];      
        Communication__c  com = SOEUtility.COMM_Insert(tas[1].id,soe.id,false,null,null,null,null);        
        User user1 = SOEUtility.USer_Insert('user--39--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--39--@gmail.com'];
        Team__c team = SOEUtility.Team_Insert('team2');
        Team_Member__c tmember = SOEUtility.Teammember_insert(member1.id,team.id);
        tas[1].Team__c = team.id;
        tas[1].Owner__c = tmember.id;
        tas[1].When_Task_Ready__c = true;
        update tas[1];
        Member__c member2 = SOEUtility.Member_Insert('member1',null,'918978478545','membermail@gmail.com');
        com.Default_Owner_Task_ready__c  = true;
        update com;
        com.Task_Ready_Members__c = member2.id;
        update com;
        com.Additinal_Emails_Task_Ready__c ='gsfdg@gmail.com';
        update com;
        com.Additional_Phone_Task_Ready__c ='9178974851412';
        update com;
        tas[1].Status__c = 'Ready';
        update tas[1];
        Test.StopTest();
     }
     Static testmethod void Comm_TaskCompleted(){ 
        Test.StartTest();     
        SOE__c soe = [select id,SOE_Title__c from SOE__c where SOE_Title__c ='Task Communication 1'];     
        System.assertEquals(SOE.SOE_Title__c , 'Task Communication 1'); 
        list<task__c> Tas = [select id,name,Task_Title__c,SOE__c,Stage_Level__c,Stage__c,Team__c,Owner__c from task__c where SOE__c =: SOE.id order by ID_Before_Decimal__c,Id_After_Decimal__c];      
        Communication__c  com = SOEUtility.COMM_Insert(tas[1].id,soe.id,false,null,null,null,null);
        tas[1].Task_Completed__c = true;
        update tas[1];
         User user1 = SOEUtility.USer_Insert('user--39--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--39--@gmail.com'];
        Role__c role = [select id from ROle__c where Reference_Role__c = 'Imp Manager' limit 1];
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Edit',soe.id,role.id);
        Member__c member2 = SOEUtility.Member_Insert('member1',null,'918978478545','membermail@gmail.com');
        com.Default_Owner_Completed__c  = true;
        update com;
        com.Completed_Members__c = member2.id;
        update com;
        com.Additional_Emails_Completed__c ='gsfdg@gmail.com';
        update com;
        com.Additional_Phone_Completed__c ='9178974851412';
        update com;
        tas[1].Status__c = 'Completed';
        update tas[1];
        Test.StopTest();
     }
}