temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <inlineHelpText>Country code(2 digits only) followed by Phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_newSOEteammember.cls
@istest
public class Test_newSOEteammember{
    @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
           Department__c  service1 = SOEUtility.Dep_Insert('Service1');
           Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
           SOE__c SOE1 = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,false,false); 
           System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp');
    }
    static Testmethod void newSOEteammember_Cntrl(){
        Test.StartTest();  
        role__c role = [select id from Role__c where Reference_Role__c = 'Imp Manager' limit 1];      
        SOE__c SOE1 = [Select id,SOE_Title__c from SOE__c where SOE_Title__c = 'newsoetemp' limit 1];
        System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp');
        ApexPages.currentPage().getParameters().put('id',SOE1.id);
        newSOEteammember_cntrl soeteammember = new newSOEteammember_cntrl();
        user user1 = SOEUtility.user_insert('user--2@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--2@gmail.com'];
        user user2 = SOEUtility.user_insert1('user--3@gmail.com');
        Member__c member2 = [select id from Member__c where Email__c ='user--3@gmail.com'];
        soeteammember.wrapperlist[0].Teammember.Team_Member__c = member1.id;
        soeteammember.wrapperlist[0].Teammember.Access_Level__c = 'Edit';
        soeteammember.wrapperlist[0].Teammember.Role__c = Role.Id;
        soeteammember.save();
        soeteammember.EntryCount = 1;
        soeteammember.Additem();        
        soeteammember.wrapperlist[1].Teammember.SOE__c = SOE1.id; 
        soeteammember.wrapperlist[1].Teammember.Team_Member__c = member1.id;
        soeteammember.wrapperlist[1].Teammember.Access_Level__c = 'Edit';
        soeteammember.wrapperlist[1].Teammember.Role__c = Role.Id;
        soeteammember.save();
        soeteammember.MemberId = 0;
        soeteamMember.HavingSalesforceUser();       
        soeteammember.EntryCount = 2;   
        soeteammember.Additem();        
        soeteammember.wrapperlist[2].Teammember.SOE__c = SOE1.id; 
        soeteammember.wrapperlist[2].Teammember.Team_Member__c = member1.id;
        soeteammember.wrapperlist[2].Teammember.Access_Level__c = 'Edit';  
        soeteammember.wrapperlist[2].Teammember.Role__c = Role.Id;  
        soeteammember.EntryCount = 2;   
        soeteammember.delitem();
        soeteammember.Additem();        
        soeteammember.EntryCount = 0;
        soeteammember.delitem();
        soeteammember.EntryCount = 1;
        soeteammember.Additem();        
        soeteammember.wrapperlist[1].Teammember.SOE__c = SOE1.id; 
        soeteammember.wrapperlist[1].Teammember.Team_Member__c = member1.id;
        soeteammember.wrapperlist[1].Teammember.Access_Level__c = 'Edit';
        soeteammember.wrapperlist[1].Teammember.Role__c = Role.Id;
        soeteammember.save();
        soeteammember = new newSOEteammember_cntrl();
        soeteammember.MemberId = 1;
        soeteamMember.HavingSalesforceUser();
        soeteammember.cancel();  
        Test.StopTest();   
    }
    static Testmethod void newSOEteammember_Cntrl1(){
        Test.StartTest();
            role__c role = [select id from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
            SOE__c SOE1 = [Select id,SOE_Title__c from SOE__c where SOE_Title__c = 'newsoetemp' limit 1]; 
            System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp');
            ApexPages.currentPage().getParameters().put('id',SOE1.id);
            newSOEteammember_cntrl soeteammember = new newSOEteammember_cntrl();
            user user1 = SOEUtility.user_insert('user--2@gmail.com');
            Member__c member1 = [select id from Member__c where Email__c ='user--2@gmail.com'];
            soeteammember.EntryCount = 1;
            soeteammember.Additem();
            soeteammember.save();
            soeteammember.wrapperlist[0].Teammember.Team_Member__c = member1.id;
            soeteammember.wrapperlist[0].Teammember.Access_Level__c = 'Edit';
            soeteammember.wrapperlist[0].Teammember.Role__c = Role.Id;
            soeteammember.save();
            soeteammember.EntryCount = 1;
            soeteammember.Additem();
            soeteammember.wrapperlist[1].Teammember.Team_Member__c = member1.id;
            soeteammember.Additem();
            soeteammember.save();
            Member__c member12 = new Member__c(Name = 'abc123',Email__c = 'abs@123.com',Phone__c = '1234566656');
            insert member12;
            soeteammember.wrapperlist[0].Teammember.Team_Member__c = member12.id;
            soeteammember.MemberId = 0;
            soeteammember.HavingSalesforceUser();   
            soeteammember.EntryCount = 1;
            soeteammember.wrapperlist[0].Teammember.Team_Member__c = member1.id; 
            soeteammember.Additem();
            soeteammember.wrapperlist[1].Teammember.Team_Member__c = soe1.id; 
            soeteammember.wrapperlist[1].Teammember.Access_Level__c = 'Edit';
            soeteammember.wrapperlist[1].Teammember.Role__c = Role.Id;      
            soeteammember.Save();
            SOE_Team_Member__c tm = [select id from SOE_TEam_Member__c where SOE__c =: soe1.id limit 1];
            delete tm;
            soeteammember.EntryCount = 0;    
            soeteammember.delitem(); 
        Test.StopTest();
    }
}