temp/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Detail__c</fullName>
        <label>Technical Detail</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_Search_and_Replace_cntrl.cls
@istest
Public class Test_Search_and_Replace_cntrl {
    Public static i8Constants i8 = new I8Constants();
    Static testmethod void Search_and_Replace_cntrl(){
    SOEUtility.SystemSettings_Insert();
    Department__c service = SOEUtility.Dep_Insert('Service2');
    Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
    SOE__c SOE = SOEUtility.SOE_Insert('SOE--1',service.Id,true,true,false,false);  
    System.assertEquals(SOE.SOE_Title__c , 'SOE--1');
    User user1 = SOEUtility.USer_Insert('user--36--@gmail.com');
    Member__c member1 = [select id from Member__c where Email__c ='user--36--@gmail.com'];
    SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Read',soe.id,role.id);
    list<Task__c> tas = [select id,Id_Text__c,Task_Title__c,Description__c,Technical_Detail__c from Task__c where SOE__c=: SOE .id order by Id_Before_Decimal__c,Id_After_Decimal__c];      
       tas[0].Description__c='decription';  
       update tas;
        Test.StartTest();
            ApexPages.CurrentPage().getparameters().put('Id', soe.Id);
            Search_and_Replace_cntrl SR = new Search_and_Replace_cntrl();
             SR.SearchValue='pre';
             SR.Go_Method();
             SR.SearchValue='1.0';
             SR.Go_Method(); 
             SR.Go_Method();             
             SR.strng='pre';
             SR.cancel_method();
             SR.Replace_action();
             SR.Search_string='Pre-Imp Stack';
             SR.Replace_action();
             SR.Search_string='Pre-Imp Stack';
             SR.Replace='pre1';
             SR.TitleCheck=true;
             SR.selectall=true;
             SR.SelectAllCheckbox();
             SR.Replace_action();
             SR.Search_string='Pre-Imp Stack';
             SR.Replace='pre1';
             SR.selectall=true;
             SR.SelectAllCheckbox();
             SR.Technical_DetailCheck=true;
             SR.Replace_action();
             SR.Clear_Method();
             
             tas[0].Technical_Detail__c ='sap';
             update tas;
             SR=new Search_and_Replace_cntrl();
             SR.Search_string='';
             SR.Replace='hi';
             SR.DescriptionCheck=true;
             SR.selectall=true;
             SR.SelectAllCheckbox();
             SR.Replace_action(); 
                          
             SR.Search_string='sap';
             SR.Replace='hi';
             SR.Technical_DetailCheck=true;
             SR.selectall=true;
             SR.SelectAllCheckbox();  
             SR.Replace_action();                
             SR.Search_string='decription';
             SR.Replace='decription1';
             SR.str='decription';
             SR.STR1=true;
             SR.DescriptionCheck=true;             
             SR.selectall=true;
             SR.SelectAllCheckbox();
             SR.Replace_action();  
             SR.selectall=false;
             SR.SelectAllCheckbox();
             
            Test.StopTest();
    }
}