temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Change_Record__c</fullName>
        <label>Change Request No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conference_Call_No__c</fullName>
        <label>Audio Call No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/Test_Email_Page.cls
@istest
Public class Test_Email_Page{
    Public static i8Constants i8 = new I8Constants();
        Static testmethod void Email_Page_Cntrl(){
        SOEUtility.SystemSettings_Insert();
        Test.StartTest();
             user user1 = SOEUtility.user_insert('user--12@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--12@gmail.com'];
            Department__c  service = SOEUtility.Dep_Insert('Service2');
            SOE__c SOE = SOEUtility.SOE_Insert('SOE-/-1',service.Id,true,true,false,false);
            System.assertEquals(SOE.SOE_Title__c , 'SOE-/-1');

            ApexPages.CurrentPage().getparameters().put('Id', SOE.Id);
            Email_Page_Cntrl Email = New Email_Page_Cntrl();
            Email.ExternalMails = 'venkatesh.2630@gmail.com,venkatesh.30@gmail.com';
            Email.emailbody = 'xyx';
            Email.SOE.Conference_Call_No__c = '8888998988';
            Email.SOE.Summary__c = 'descript';
            Email.SOE.Change_Record__c = 'record';
            Email.getLeftUsers();
            Email.getRightUsers();
            Email.leftselected.add(User1.Id);
            Email.AddUsers();
            Email.RightSelected.add(User1.Id);
            Email.DeleteUsers();
            Email.AddAllUsers();
            Email.SendMail();
            Email.ClearRightUsers();
            Email.selectformat();
            Email.getselectformatoption();
            Email.close();
            Email.reset();
            Email.Cancel();
    
            ApexPages.CurrentPage().getparameters().put('Id', SOE.Id);
            Email = New Email_Page_Cntrl();
            Email.selectaction = 'Excel';
            Email.ExternalMails = 'venkatesh.2630@gmail.com,venkatesh.260@gmail.com,venkatesh.263@gmail.com';
            Email.emailbody = '';
            Email.SendMail();
            Email.AddAllUsers();
            Email.SendMail();
            Email.selectformat();
            Email.getselectformatoption();
                
            ApexPages.CurrentPage().getparameters().put('Id', SOE.Id);
            Email = New Email_Page_Cntrl();
            Email.ExternalMails = '';
            Email.emailbody = '';
            Email.getLeftUsers();
            Email.getRightUsers();
            Email.DeleteAllUsers();
            Email.SendMail();           

            ApexPages.CurrentPage().getparameters().put('page', 'detail');
            ApexPages.CurrentPage().getparameters().put('Id', SOE.Id);
            Email = New Email_Page_Cntrl();
            Email.Cancel();
       Test.StopTest();
    }
}