temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/Test_ExportSOE.cls
@istest
public class Test_ExportSOE{
    static testmethod void ExportSOE(){
           SOEUtility.SystemSettings_Insert();
        Department__c service1 = SOEUtility.Dep_Insert('Service1');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE1 = SOEUtility.SOE_Insert('newsoeinc',service1.Id,true,true,false,false);
        System.assertEquals(SOE1.SOE_Title__c , 'newsoeinc');
        
        Test.starttest();
            ApexPages.CurrentPage().getparameters().put('Id',soe1.Id); 
            Export_Soe_cntrl ExportSOE = new Export_Soe_cntrl();
            ExportSOE.Select_soe();
            ExportSOE.getleftfields();
            ExportSOE.leftselected=new list<string>();
            ExportSOE.leftselected.add('Pre-Imp Stage');
            ExportSOE.leftselected.add('Post-Imp Stage');
            ExportSOE.leftselected.add('SOE Title');
            ExportSOE.AddFields();                  
            Exportsoe.getRightfileds();
            Exportsoe.Rightselected =new list<string>();
            Exportsoe.Rightselected.add('Pre-Imp Stage');
            Exportsoe.Rightselected.add('Post-Imp Stage');            
            Exportsoe.DeleteFields(); 
            ExportSOE.Export_method();
            ExportSOE.rightlist=new list<string>();
            ExportSOE.rightlist.add('Pre-Imp Stage');
            ExportSOE.rightlist.add('Post-Imp Stage');
            ExportSOE.fieldsdisplay='Pre_Implementation_Stage__c,Post_Implementation_Stage__c'; 
            ExportSOE.selectradio='PDF'; 
            ExportSOE.DownloadSoe_method();
            ExportSOE.selectradio='CSV'; 
            ExportSOE.DownloadSoe_method();
            ExportSOE.close_method();
         //   ExportSOE.Cancel_download();
            ExportSOE.CancelSOE();
            ExportSOE.DownloadSoe='';
            ExportSOE.Select_soe();
            
            ApexPages.CurrentPage().getparameters().put('Page','tab');              
            ExportSOE = new Export_Soe_cntrl();            
            ExportSOE.getSOEOptions();
            ExportSOE.SearchValue ='newsoeinc';
            ExportSOE.SOE_List();
            ExportSOE.DownloadSoe=SOE1.id;
            ExportSOE.SelectedSOEdownload();                      
            ExportSOE.CancelSOE(); 
            ExportSOE.DownloadSoe_method();
            ExportSOE.Clear_search();
        //    ExportSOE.Cancel_download();
            
        Test.stoptest();
    }
}