temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Jump_Stack_Cntrl.cls
@istest
public class Test_Jump_Stack_Cntrl{
    Public static i8Constants i8 = new I8Constants();
    
    Static testmethod void Jump_Stack_Cntrl(){
           SOEUtility.SystemSettings_Insert();
        Department__c  service1 = SOEUtility.Dep_Insert('Service1');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('SOE--1',service1.Id,false,false,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'SOE--1');
        SOE__c SOE1 = SOEUtility.SOE_Insert('SOE--11',service1.Id,true,true,false,false);
        list<task__c> Tas = [select id,name,Task_Title__c,SOE__c,Id_Before_Decimal__c,Id_Text__c,Stage_Level__c,Stage__c,Team__c,Owner__c from task__c where SOE__c =:soe.id and Is_Stack__c = True order by Id_Before_Decimal__c];
        test.starttest();
         User user1 = SOEUtility.USer_Insert('user--30--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--30--@gmail.com'];
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Read',soe.id,role.id);
        ApexPages.CurrentPage().getparameters().put('Id', SOE.Id);
        Stack_CreateMove_Cntrl Stack_Create = new Stack_CreateMove_Cntrl();
        Stack_Create.TargetStage = I8.STAGE_IMP;
        Stack_Create.TargetStack = Tas[0].Id_Text__c; 
        ApexPages.CurrentPage().getparameters().put('days', '2');
        ApexPages.CurrentPage().getparameters().put('hours', '2');
        ApexPages.CurrentPage().getparameters().put('minutes', '2');
        ApexPages.CurrentPage().getparameters().put('tasktitle', 'T2');
        Stack_Create.CreateStack();
        Tas = [select id,name,Task_Title__c,SOE__c,Id_Before_Decimal__c,Id_Text__c,Stage_Level__c,Stage__c,Team__c,Owner__c from task__c where SOE__c =:soe.id  order by Id_Before_Decimal__c,Id_After_decimal__c];
        tas[0].Status__c = i8.STATUS_RUNNING;
        update tas[0];
        jump_stack_cntrl Jump = new jump_stack_cntrl ();
        Jump.SourceStage = I8.STAGE_IMP;
        Jump.selected_Stack = string.valueOf(Tas[0].Id_Before_Decimal__c);
        Jump.jump_stack();
        Jump.selected_Stack = string.valueOf(Tas[3].Id_Before_Decimal__c);
        Jump.jump_stack();        
        jump.openCancel();
        ApexPages.CurrentPage().getparameters().put('Id', SOE1.Id);
        jump_stack_cntrl Jump1 = new jump_stack_cntrl ();
        Jump1.SourceStage = I8.STAGE_IMP;
        Jump1.selected_Stack = string.valueOf(Tas[0].Id_Before_Decimal__c);
        Jump1.jump_stack();
        Jump1.SOEObj = null;
        Jump1.jump_Stack();
        test.stoptest();
    }
}