temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_History_Tracking_Cntrl.cls
@istest
Public class Test_History_Tracking_Cntrl{
    Public static i8Constants i8 = new I8Constants();
    Static testmethod void History_Tracking_Cntrl(){
           SOEUtility.SystemSettings_Insert();
            Department__c service = SOEUtility.Dep_Insert('Service2');
            Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
            SOE__c SOE = SOEUtility.SOE_Insert('SOE--1',service.Id,true,true,false,false);
            SOE__c SOE1 = SOEUtility.SOE_Insert('SOE1',service.Id,true,true,false,false);
            System.assertEquals(SOE.SOE_Title__c , 'SOE--1');
            MIS__c mis1 = SOEUtility.MIS_Insert('dds');
            System.assertEquals(mis1.MIS_Title__c , 'dds');
            SOE1.MIS__c = mis1.id;
            update soe1;        
        Test.StartTest();
        
            ApexPages.CurrentPage().getparameters().put('Id', SOE1.Id);
            History_Tracking_Cntrl Add = new History_Tracking_Cntrl();
            Add.cancel();
                        
            ApexPages.CurrentPage().getparameters().put('Id', mis1.Id);
            Add = new History_Tracking_Cntrl();
            Add.cancel();
            
        Test.StopTest();
    }
}