temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>PayPeriod_End__c</fullName>
        <inlineHelpText>Enter the Pay Period End Date here.</inlineHelpText>
        <label>PayPeriod End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PayPeriod_Start__c</fullName>
        <inlineHelpText>Enter the Pay Period Start Date here.</inlineHelpText>
        <label>PayPeriod Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the Timesheet.  Set by Approval process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Timesheet #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Timesheet_Entry__c.object
<CustomObject>
    <description>Entries for Timesheets</description>
    <fields>
        <fullName>End__c</fullName>
        <inlineHelpText>Enter the end of your day here.</inlineHelpText>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Timesheet Entries</relationshipLabel>
        <relationshipName>Timesheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <inlineHelpText>Enter the start of your day here.</inlineHelpText>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Entries</relationshipLabel>
        <relationshipName>Timesheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TS Entry-{000000000}</displayFormat>
        <label>Timesheet Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/User.object
<CustomObject>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                    <default>true</default>
                    <label>Hourly</label>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/classes/Test_Add_Timesheet_Entries_Cntrl.cls
@istest
public class Test_Add_Timesheet_Entries_Cntrl {
    static testmethod void Add_Timesheet_Entries_Cntrl(){
        SOEUtility.SystemSettings_Insert();
        Department__c  service1 = SOEUtility.Dep_Insert('Service1');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('newsoetemp1',service1.Id,true,true,false,false); 
        System.assertEquals(SOE.SOE_Title__c , 'newsoetemp1');
         user user1 = SOEUtility.user_insert('user--10@gmail.com');
        user1.Pay_Type__c='Hourly';
        user1.Rate_Card__c=200;
        Timesheet__c Timesheet1 = new Timesheet__c(PayPeriod_Start__c= System.today(),PayPeriod_End__c= System.today().adddays(4));
        Insert Timesheet1 ;
        Timesheet__c Timesheet2 = new Timesheet__c();
        Insert Timesheet2 ;
        Timesheet_Entry__c Timesheetentry = new Timesheet_Entry__c(SOE__c=SOE.id,Timesheet__c=Timesheet1.id,Start__c=System.now(),End__c=System.now().addminutes(5));  
        insert  Timesheetentry ; 
        Timesheet_Entry__c Timesheetentry1 = new Timesheet_Entry__c(SOE__c=SOE.id,Timesheet__c=Timesheet1.id,Start__c=System.now().addminutes(5),End__c=System.now());
        insert  Timesheetentry1 ; 
                   
        test.starttest(); 
            ApexPages.StandardController sc1 = new ApexPages.StandardController( new Timesheet__c());
            Apexpages.Currentpage().getParameters().put('id',Timesheet2.id);
        Add_Timesheet_Entries_Cntrl Deiltimesheet1= new Add_Timesheet_Entries_Cntrl(sc1);
           
            ApexPages.StandardController sc = new ApexPages.StandardController( new Timesheet__c());
            Apexpages.Currentpage().getParameters().put('id',Timesheet1.id);  
            Add_Timesheet_Entries_Cntrl Deiltimesheet= new Add_Timesheet_Entries_Cntrl(sc);
            Deiltimesheet.TsObj.PayPeriod_Start__c = null;
            Deiltimesheet.Create();            
            Deiltimesheet.TsObj.PayPeriod_Start__c=System.today().adddays(5);
            Deiltimesheet.TsObj.PayPeriod_End__c= System.today();
            Deiltimesheet.Create();
            Deiltimesheet.TsObj.PayPeriod_Start__c=System.now();            
            Deiltimesheet.TsObj.PayPeriod_End__c= System.now().adddays(5);
            Deiltimesheet.TsObj.PayPeriod_End__c= System.now().addHours(5);
            Deiltimesheet.Create();
            Deiltimesheet.entrycount =1;
            Deiltimesheet.deleteLI();
            Deiltimesheet.Create(); 
            Deiltimesheet.entrycount =2; 
            Deiltimesheet.deleteLI();
            Deiltimesheet.NewLI();  
            Deiltimesheet.entrycount =1; 
            Deiltimesheet.deleteLI();    
            Deiltimesheet.Create();
            Deiltimesheet.NewLI();
            Deiltimesheet.Create();
            Deiltimesheet.NewLI();
            Deiltimesheet.entrycount =1;
            Deiltimesheet.TSEntrywraplist[1].TSEntry.Start__c = null;
            Deiltimesheet.Create();
            Deiltimesheet.TSEntrywraplist[1].TSEntry.Start__c = System.now().addHours(124);
            Deiltimesheet.TSEntrywraplist[1].TSEntry.End__c = System.now().addHours(3);
            Deiltimesheet.Create();
            Deiltimesheet.TSEntrywraplist[1].TSEntry.Start__c = System.now().addHours(1);
            Deiltimesheet.TSEntrywraplist[1].TSEntry.End__c = System.now().addHours(3);
            Deiltimesheet.Create();
            Deiltimesheet.TSEntrywraplist[1].TSEntry.SOE__c = null;
            Deiltimesheet.Create();
            Deiltimesheet.TSEntrywraplist.clear();
            
            
            Timesheetentry = new Timesheet_Entry__c(SOE__c=SOE.id,Timesheet__c=Timesheet1.id,Start__c=System.now(),End__c=System.now().adddays(1));  
            insert  Timesheetentry ; 
            Deiltimesheet= new Add_Timesheet_Entries_Cntrl(sc);
            Deiltimesheet.Create();
            Deiltimesheet.TSEntrywraplist.clear();  
            Timesheetentry = new Timesheet_Entry__c(SOE__c=SOE.id,Timesheet__c=Timesheet1.id,Start__c=System.now(),End__c=System.now().addminutes(5));  
            insert  Timesheetentry ; 
            Deiltimesheet= new Add_Timesheet_Entries_Cntrl(sc);
            Deiltimesheet.Create(); 
            Timesheet1.Status__c = 'Waiting for Approval';
            update Timesheet1;
            Deiltimesheet= new Add_Timesheet_Entries_Cntrl(sc);
        test.stoptest();
    }
}