temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_SOE_DashBoards_Cntrl.cls
@istest(SeeAllData=true)
Public class Test_SOE_DashBoards_Cntrl{  
 Static testmethod void SOE_DashBoards(){
     i8Constants i8 = new I8Constants();
   Test.StartTest(); 
      Department__c  service1 = SOEUtility.Dep_Insert('Service1');
      Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
       User user1 = SOEUtility.USer_Insert('user--26--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--26--@gmail.com'];
      system.runas(user1){
      SOE__c SOE1 = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,false,false); 
      System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp');
      apexpages.currentpage().getparameters().put('id',soe1.id);
      SOE_DashBoards_Cntrl SoeDashboard=new SOE_DashBoards_Cntrl(); 
      soe1.Schedule_Start__c = System.Now().AddMinutes(5);
      soe1.Schedule_End__c = System.Now().AddHours(5);
      soe1.Warning_Zone__c = System.Now().AddHours(5);
      soe1.BAU_Impact__c = System.Now().AddHours(5);
      soe1.Status__c = i8.STATUS_FREEZE;
      update soe1;
      list<Task__c> tas = [select id,Id_Text__c from Task__c where soe__c =: soe1.Id and Stage_Level__c =: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c];
      tas[3].Start_Time__c = System.Now().AddDays(5);
      tas[3].End_Time__c = tas[3].Start_Time__c .AddMinutes(5);
      tas[3].Status__c = i8.STATUS_FREEZE;
      update tas[3];
      Task_TriggerHandler.UpdateAllTasks(new list<id>{soe1.Id},i8.CONTEXT_IMP);
      SoeDashboard=new SOE_DashBoards_Cntrl();
      soe1.status__c = i8.STATUS_IMP_COMP;
      update soe1;
      SoeDashboard=new SOE_DashBoards_Cntrl();
      soedashboard.openCancel();
      soedashboard.OPenReport();
      }
      Test.StopTest();  
  }
  Static testmethod void Report_Cntrl1(){
      Test.StartTest();
      User user1 = SOEUtility.USer_Insert('user--26--@gmail.com');
      Member__c member1 = [select id from Member__c where Email__c ='user--26--@gmail.com'];
      system.runas(user1){
          Department__c  service1 = SOEUtility.Dep_Insert('Service1');
          SOE__c SOE1 = SOEUtility.SOE_Insert('newsoetemp1212',service1.Id,true,true,false,false); 
          System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp1212');
          ApexPAges.CurrentPAge().getPArameters().put('pn0','s-120');
          ApexPAges.CurrentPAge().getPArameters().put('pv0','s-120');
          ApexPAges.CurrentPAge().getPArameters().put('pv1','s-120');
          Report_Cntrl rc = new Report_Cntrl();
          ApexPAges.CurrentPAge().getPArameters().put('pc0','s-120');
          rc = new Report_Cntrl();
          ApexPAges.CurrentPAge().getPArameters().put('pc0',null);
          ApexPAges.CurrentPAge().getPArameters().put('pn0',null);
          ApexPAges.CurrentPAge().getPArameters().put('pv0','s-120');
          rc = new Report_Cntrl();
      }
      Test.StopTest();
  }
}