temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_Create_Incident_Method.cls
@istest
public class Test_Create_Incident_Method{
    public static i8Constants i8 = new I8Constants();
    public static boolean ReExecute;   
    static testmethod void Create_Incident(){ 
        SOEUtility.SystemSettings_Insert();
        MIS__c mis = SOEUtility.MIS_Insert('MIS_Testing');
        Department__c service1 = SOEUtility.Dep_Insert('Service1');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE1 = SOEUtility.SOE_Insert('newsoeinc',service1.Id,true,true,false,false);  
        System.assertEquals(SOE1.SOE_Title__c , 'newsoeinc');
        user user1 = SOEUtility.user_insert('user--10@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--10@gmail.com'];        
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Read',soe1.id,role.id);
        List<Task__c> TaskList = [select id,status__c,Task_Title__c  from Task__C where SOE__c =: SOE1.Id order by Id_Before_Decimal__c,Id_After_decimal__c];
        Test.StartTest();
        
       ApexPages.CurrentPage().getparameters().put('SOEId',soe1.Id); 
        Create_Incident inc = new Create_Incident();  
        inc.cancel_INC();        
        ApexPages.CurrentPage().getparameters().put('MId',mis.Id);
        inc = new Create_Incident();  
        inc.cancel_INC();
        
        inc = new Create_Incident(); 
        inc.INCOBJ.Inc_Type__c =null;
        inc.save_INC();
        
        inc.INCOBJ.Inc_Type__c ='Bug';
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Priority__c = 'Low';
        inc.save_INC();  
        inc.Add_Note ='incident';
        inc.Add_Note_Action();
        
        //SOE Suspend,ReExecute,Abandoned. 
        ApexPages.CurrentPage().getparameters().put('SOEId',soe1.Id);  
        ApexPages.CurrentPage().getparameters().put('type', 'Abandoned');
        inc = new Create_Incident();
        inc.INCOBJ.Summary__c = 'Summary';
        inc.INCOBJ.Inc_Type__c = 'Abandoned';
        inc.INCOBJ.Priority__c = 'Low';
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('type', 'Suspend');
        inc = new Create_Incident();
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('type', 'Suspend');
        inc = new Create_Incident(); 
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Priority__c = 'Low'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('type', 'ReExecute');
        inc = new Create_Incident(); 
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Priority__c = 'Low'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        
        ApexPages.CurrentPage().getparameters().put('TAskId',TaskList[1].Id);
        ApexPages.CurrentPage().getparameters().put('type', 'Suspend');
        inc = new Create_Incident(); 
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Priority__c = 'Low'; 
        inc.INCOBJ.Assignee__c=member1.id;
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('type', 'ReExecute');
        inc = new Create_Incident(); 
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Priority__c = 'Low';
        inc.INCOBJ.Inc_Type__c ='Suspended'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        Test.stoptest();
        ApexPages.CurrentPage().getparameters().put('type', 'Force');
        inc = new Create_Incident();         
        inc.INCOBJ.Priority__c = 'Low';
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Inc_Type__c ='Suspended'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('TAskId',null);
        ApexPages.CurrentPage().getparameters().put('type', 'backout');
        inc = new Create_Incident();         
        inc.INCOBJ.Priority__c = 'Low';
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Inc_Type__c ='Suspended'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('TAskId',TaskList[1].Id);
        ApexPages.CurrentPage().getparameters().put('type', 'ReExecute');
        inc = new Create_Incident();         
        inc.INCOBJ.Priority__c = 'Low';
        inc.INCOBJ.Summary__c='hii';
        inc.INCOBJ.Inc_Type__c ='Suspended'; 
        inc.INCOBJ.Assignee__c=member1.id; 
        inc.save_INC();
        ApexPages.CurrentPage().getparameters().put('TAskId',null);
        ApexPages.CurrentPage().getparameters().put('MId',mis.Id);
        inc.save_INC();
        
        ApexPages.CurrentPage().getparameters().put('MId',null);
        ApexPages.CurrentPage().getparameters().put('TAskId',TaskList[1].Id);
        Create_Incident incident = new Create_Incident(); 
        incident.cancel_INC();
        ApexPages.CurrentPage().getparameters().put('SOEId',null);
        ApexPages.CurrentPage().getparameters().put('MId',mis.Id);
        ApexPages.CurrentPage().getparameters().put('TAskId',TaskList[1].Id);
        incident = new Create_Incident(); 
        incident.cancel_INC();
        
        
    } 
}