temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BackOut_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BackOut Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Backout__c</fullName>
        <label>Backout Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Baseline_Start__c</fullName>
        <label>Baseline Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QA_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WalkThrough_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Walkthrough Manager is default Implementation Manager.</inlineHelpText>
        <label>WalkThrough Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_SOE_Trigger_Handler.cls
@istest
public class Test_SOE_Trigger_Handler{  
    @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
            Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
            role = [select id,Reference_Role__c  from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
            System.assertEquals(role.Reference_Role__c , 'Imp Manager');
           }
    public static SOE__c SOE_Insert(string title,Id service,Boolean pre,Boolean Post,Boolean Backout,Boolean QA,Boolean WT){
        SOE__c SOE= new SOE__c();
        SOE.SOE_Title__c = title;
        SOE.Department__c = service;
        SOE.Pre_Implementation_Stage__c = pre;
        SOE.Post_Implementation_Stage__c = post;
        SOE.BackOut_Stage__c= Backout;
        SOE.QA_Review_Required__c = QA;        
        SOE.WalkThrough_Required__c = WT;
        SOE.Baseline_Start__c = system.now();
        if(soe.BackOut_Stage__c == true)
            soe.Backout__c = 'Manual';
        soe.Summary__c = 'sdfsdfsd';
        insert SOE;
        return SOE;
    }
    
    static testmethod void Test_SOE(){    
        Test.StartTest();        
        Department__c  service1 = SOEUtility.Dep_Insert('Service1');
        SOE__c SOE1 = SOEUtility.SOE_Insert('newsoeinc',service1.Id,true,false,false,false);
        System.assertEquals(SOE1.SOE_Title__c , 'newsoeinc');
        SOE__c SOE2 = SOEUtility.SOE_Insert('newsoeinc1',service1.Id,false,true,false,false);
        SOE__c SOE3 = SOE_Insert('newsoeinc2',service1.Id,false,true,true,false,false); 
         user user1 = SOEUtility.user_insert('user--21@gmail.com');
        SOE3.QA_Review_Required__c = true;
        SOE3.QA_Manager__c = user1.id;
        update SOE3;
         Test.StopTest(); 
        user user2 = SOEUtility.user_insert1('user--22@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--22@gmail.com'];
        id Id1;
        Role__c role = SOEUtility.Role_insert('QA Manager');
        SOE_Team_Member__c  stm1 = SOEUtility.teammember_insert(member1.id,'Edit',SOE3.Id,id1);
        SOE3.QA_Manager__c = user2.id;
        update SOE3;
        SOE3.QA_Manager__c = null;
        update SOE3;          
    }
      static testmethod void Test_SOE1(){    
        Test.StartTest();  
        Role__c role = [select id,Reference_Role__c  from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
        User user1 = SOEUtility.USer_Insert('user--34--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--34--@gmail.com'];            
        Department__c  service1 = SOEUtility.Dep_Insert('Service1');
        SOE__c SOE1 = SOEUtility.SOE_Insert('newsoeinc111',service1.Id,false,false,false,false);
        System.assertEquals(SOE1.SOE_Title__c , 'newsoeinc111');
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Edit',soe1.id,role.id);
        MIS__c mis1 = SOEUtility.MIS_Insert('dds');
        soe1.MIS__c = mis1.id;
        soe1.Status__c = 'Imp In Progress';
        update soe1;
        soe1.Schedule_Start__c = System.Now();
        soe1.Schedule_End__c = System.Now().addHours(1);
        soe1.Warning_Zone__c = System.Now().Addhours(2);
        soe1.BAU_Impact__c = System.Now().Addhours(3);
        update soe1;
        Member__c member = SOEUtility.Member_Insert('xxxx',UserInfo.getUserId(),'232323','sasa@gmail.com');
        MIS__c mis2 = SOEUtility.MIS_Insert('dds12');
        soe1.MIS__c = mis2.id;
        update soe1;
        Test.StopTest();
    }
}