temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Expense_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <label>Employee Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expense_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>EC-{000000}</displayFormat>
        <label>Expense Claim #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Expenses_cntrl.cls
@istest
public class Test_Expenses_cntrl{
    static Testmethod void  Expenses_cntrl(){
        SOEUtility.SystemSettings_Insert();
        Department__c service = SOEUtility.Dep_Insert('Service2');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('SOE--1',service.Id,true,true,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'SOE--1');
         user user1 = SOEUtility.user_insert('user--13@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--13@gmail.com'];
        Expense_Claim__c EC = new Expense_Claim__c (From_Date__c =Date.today(),To_Date__c=Date.today()+1,Employee_Name__c='sot',Manager__c=user1.id);
        Insert EC;
        Test.StartTest();
            apexpages.currentpage().getparameters().put('id',EC.id);
            ApexPages.StandardController sc = new ApexPages.StandardController( new Expense_Claim__c ());
            Expenses_cntrl Expen = new Expenses_cntrl(sc);
            Expen.SaveExpenses();
            Expen.WrapperList[0].Exp.Date__c = Date.today()+ 2;
            Expen.WrapperList[0].Exp.Payment_Type__c = 'Card';
            Expen.WrapperList[0].Exp.Expense_Type__c = 'Airfare';
            Expen.WrapperList[0].Exp.Amount__c = 100.0;            
            Expen.SaveExpenses();
            Expen.UpdateLists();
            Expen.AddEntry();
            ApexPages.currentPage().getParameters().put('DeleteId','1'); 
            Expen.DeletEntry();
            ApexPages.currentPage().getParameters().put('DeleteId','0'); 
            Expen.DeletEntry();
            Expen.SaveExpenses();
            Expen.WrapperLIst = null;
            Expen.SaveExpenses();
            Expen.CancelExpenses();         
        Test.StopTest();
        }
}