temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/Test_MIS_DashBoards_Cntrl.cls
@istest(SeeAllData=true)
Public class Test_MIS_DashBoards_Cntrl {  
    Static testmethod void MIS_DashBoards(){
         i8Constants i8 = new I8Constants();   
          Department__c  service1 = SOEUtility.Dep_Insert('Service1');
          Role__c  Role =  SOEUtility.Role_Insert('Imp Manager');
          User user1 = SOEUtility.USer_Insert('user--26--@gmail.com');
          Member__c member1 = [select id from Member__c where Email__c ='user--26--@gmail.com'];
          Test.StartTest(); 
          system.runas(user1){
              SOE__c SOE1 = SOEUtility.SOE_Insert('newsoetemp',service1.Id,true,true,false,false); 
              System.assertEquals(SOE1.SOE_Title__c , 'newsoetemp');
              MIS__c mis1 = SOEUtility.MIS_Insert('dds');
              System.assertEquals(mis1.MIS_Title__c , 'dds');
              soe1.MIS__c = mis1.id;
              update soe1;
              SOE__c SOE2 = SOEUtility.SOE_Insert('newsoetemp123123',service1.Id,true,true,false,false);
              soe2.MIS__c = mis1.id;
              update soe2;
              apexpages.currentpage().getparameters().put('id',mis1.id);
              MIS_DashBoards_Cntrl MISDashboard=new MIS_DashBoards_Cntrl(); 
              MISDashboard.OPenCancel();
              MISDashboard.OpenReport();
         }  
         Test.stoptest();  
    }   
}