temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/Test_TwilioUtility.cls
@istest
Public class Test_TwilioUtility {
     @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
        Department__c service = SOEUtility.Dep_Insert('Service2');
        Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
        SOE__c SOE = SOEUtility.SOE_Insert('Modify SOE12',service.id,true,true,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'Modify SOE12');  
        SOEUtility.TwilioSettings_Insert('TwilioUtility','no');       
    }
    Static testmethod void twilio1(){ 
        Test.StartTest();  
            list<string> PhNumbers = new list<string>();
            PhNumbers.add('917889748596');
            System.assertEquals(PhNumbers[0] , '917889748596');
            TwilioUtility twilio = new TwilioUtility ();
            twilio.SendSMS(PhNumbers,'aaaaa'); 
            twilio.SendSMS2(PhNumbers,'aaaaa');            
        Test.StopTest();
    }
     Static testmethod void twilio2(){ 
        Test.StartTest();  
            list<string> PhNumbers = new list<string>();
            PhNumbers.add('917889748596');
            System.assertEquals(PhNumbers[0] , '917889748596');
            TwilioUtility twilio = new TwilioUtility ();
            twilio.SendCall('919553333148');            
        Test.StopTest();
    }
     Static testmethod void twilio3(){ 
        Test.StartTest();  
            list<string> PhNumbers = new list<string>();
            PhNumbers.add('917889748596');
            System.assertEquals(PhNumbers[0] , '917889748596');
            TwilioUtility twilio = new TwilioUtility ();
            twilio.SendSMS(PhNumbers,'aaaaa');
        Test.StopTest();
    }
    static testmethod void MIS_Call(){ 
        Test.StartTest();  
            MIS__c mis = SOEUtility.MIS_Insert('MIS insetrt1');
            System.assertEquals(mis.MIS_Title__c, 'MIS insetrt1');
            ApexPages.CurrentPage().getparameters().put('ActiveId', '919234567765');
            ApexPages.CurrentPage().getparameters().put('body1', 'sample message');
            ApexPages.CurrentPage().getparameters().put('id', mis.Id);
            MIS_AllTasks_Cntrl All = new MIS_AllTasks_Cntrl();
            All.CreateCall();           
            All.CreateSMS();
        Test.StopTest();
    }
    static testmethod void SOE_Call(){ 
        Test.StartTest();  
        User user1 = SOEUtility.USer_Insert('user--26--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--26--@gmail.com'];
        system.runas(user1){
            Department__c service = SOEUtility.Dep_Insert('Service2');
            SOE__c SOE = SOEUtility.SOE_Insert('SOE--1123',service.Id,false,false,false,true);  
            System.assertEquals(SOE.SOE_Title__c , 'SOE--1123');
            ApexPages.CurrentPage().getparameters().put('ActiveId', '919234567765');
            ApexPages.CurrentPage().getparameters().put('body1', 'sample message');
            ApexPages.CurrentPage().getparameters().put('id', soe.Id);
            AllTasks_ClientSide_Cntrl  All = new AllTasks_ClientSide_Cntrl  ();
            All.CreateCall();
            All.CreateSMS();
        }
        Test.StopTest();
    }
 
}