temp/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Review__c</fullName>
        <label>QA Review</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_SOE_Schedule_Cntrl.cls
@istest
Public class Test_SOE_Schedule_Cntrl{
        @testSetup static void setup() {
           SOEUtility.SystemSettings_Insert();
           Role__c  Role = SOEUtility.Role_Insert('Imp Manager');
           role = [select id,Reference_Role__c from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
           System.assertEquals(role.Reference_Role__c , 'Imp Manager');
        }
     Static testmethod void SOE_Schedule_Cntrl(){     
        Department__c  service1 = SOEUtility.Dep_Insert('Service2');
       role__c role = [select id from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
        SOE__c SOE = SOEUtility.SOE_Insert('SOE 16/10',service1.Id,true,true,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'SOE 16/10');
        SOE__c SOE1 = SOEUtility.SOE_Insert('SOE1 16/10',service1.Id,true,true,false,false);
        test.starttest();
        SOE.Status__c = 'Review';
        Update SOE;
        SOE1.Status__c = 'Review';
        Update SOE1;
        SOE__c SOE3 = SOEUtility.SOE_Insert('SOE3 16/10',service1.Id,true,true,false,false);
        Integer duration =56;
        ApexPages.currentPage().getParameters().put('id', SOE3.id);
        SOE_Schedule_Cntrl SOETest_test = new SOE_Schedule_Cntrl();
        ApexPages.currentPage().getParameters().put('id', SOE.id);
        ApexPages.CurrentPage().getParameters().put('duration',String.valueOf(duration)); 
        SOE_Schedule_Cntrl SOETest = new SOE_Schedule_Cntrl();
        SOETest.Apply();
        SOE.Schedule_Start__c = system.now()+2;
        SOE.Schedule_End__c = system.now()+1;
        SOE.Warning_Zone__c = system.now();
        SOE.BAU_Impact__c = system.now()-1;
        update SOE;
        ApexPages.currentPage().getParameters().put('id', SOE.id);
        SOE_Schedule_Cntrl SOETest1 = new SOE_Schedule_Cntrl();
        SOETest1.change_end();
        SOETest1.Cancel();
        SOETest1.Apply();
        SOETest1.errorbool = false;
        SOETest1.Apply();
        ApexPages.currentPage().getParameters().put('id', SOE1.id);
        SOE_Schedule_Cntrl SOETest2 = new SOE_Schedule_Cntrl();
        SOETest2.duration = 59000;
        SOETest2.SOE.Schedule_Start__c = system.now().addSeconds(-5);
        SOETest2.Apply();
        SOETest2.SOE.Schedule_Start__c = system.now().addSeconds(5);
        SOETest2.SOE.Schedule_End__c = system.now().addSeconds(7);
        SOETest2.SOE.Warning_Zone__c = system.now().addSeconds(8);
        SOETest2.SOE.BAU_Impact__c = system.now().addSeconds(27);
        SOETest2.Apply();
        SOETest2.Cancel();
        test.stoptest();
        ApexPages.currentPage().getParameters().put('id', SOE1.id);
        ApexPages.currentPage().getParameters().put('page', 'detail');
        SOE_Schedule_Cntrl SOETest3 = new SOE_Schedule_Cntrl();
        SOETest3.duration = 590000;
        SOETest3.SOE.Schedule_Start__c = system.now().addSeconds(5);
        SOETest3.SOE.Schedule_End__c = system.now().addSeconds(7);
        SOETest3.SOE.Warning_Zone__c = system.now().addSeconds(8);
        SOETest3.SOE.BAU_Impact__c = system.now().addSeconds(27);
        SOETest3.Apply();
        SOETest3.Cancel();        
     }
      Static testmethod void SOE_Schedule_Cntr2(){     
        Department__c  service1 = SOEUtility.Dep_Insert('Service2');
        role__c role = [select id from Role__c where Reference_Role__c = 'Imp Manager' limit 1];
        SOE__c SOE = SOEUtility.SOE_Insert('SOE 16/10',service1.Id,true,true,false,false);
        System.assertEquals(SOE.SOE_Title__c , 'SOE 16/10');        
        test.starttest();
        User user1 = SOEUtility.USer_Insert('user--25--@gmail.com');
        Member__c member1 = [select id from Member__c where Email__c ='user--25--@gmail.com'];
        SOE_Team_Member__c stm1 = SOEUtility.teammember_insert(member1.id,'Read',soe.id,role.id);
        soe.Status__c = 'Review';
        soe.QA_Review__c = 'In Progress';
        update soe;
        ApexPages.currentPage().getParameters().put('id', SOE.id);
        SOE_Schedule_Cntrl SOETest2 = new SOE_Schedule_Cntrl();
        soe.QA_Review__c = 'Complete';
        update soe;
        system.runas(user1){
            SOETest2 = new SOE_Schedule_Cntrl();
        }
        soetest2.soe = null;
        soetest2.Apply();
        test.stoptest();
     }
}