temp/objects/Dependency__c.object
<CustomObject>
    <fields>
        <fullName>Dep_Type__c</fullName>
        <label>Dep Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Link</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent_Type__c</fullName>
        <label>Dependent Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Predecessors</fullName>
                </value>
                <value>
                    <fullName>Successors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preceeding_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preceeding Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Dependencies (Pred/Suc Task)</relationshipLabel>
        <relationshipName>Dependencies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Dependencies</relationshipLabel>
        <relationshipName>Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Dependencies</relationshipLabel>
        <relationshipName>Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FS</fullName>
                    <default>true</default>
                    <label>FS</label>
                </value>
                <value>
                    <fullName>SS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dependency</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Dependency_Type__c</fullName>
        <label>Dependency Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>IF(Days__c!=0,TEXT(Days__c) +&apos;d &apos;,&apos;&apos;)+ TEXT( Hours__c )+&apos;h &apos;+TEXT( Minutes__c )+&apos;m&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF((Is_Stack__c=true),&apos;stage&apos;,
IF((End_Stack__c =true),&apos;Check point&apos;,
IF(AND((Is_Stack__c=false),(End_Stack__c =false)) ,&apos;Task&apos;,
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/GanttChart_Cntrl1.cls
/* 
Class Name        : GanttChart_Cntrl1
Test Class Name   : Test_GanttChart_Cntrl1
Purpose/Overview  : To display tasks in Gantt Chart.
Author            : Purview Ltd.
Code Coverage     : 100 %.
Change History    : 
*/
global with sharing class GanttChart_Cntrl1 {  
    public Id SOEId{get;set;}
    
    public GanttChart_Cntrl1 ()
    {
        SOEId = ApexPages.CurrentPage().getParameters().get('id');
    }
    @RemoteAction    
    global static WrapperClass getTasks(string sid) {
        list<Dependency__c> DepList = new list<Dependency__c>();
        Map<Id,Task__c> TaskList ;
        if( Utils.isAccessible('i8__Task__c')&& Utils.isAccessible('i8__Dependency__c')){
            TaskList = new Map<Id,Task__c>([select Task_Title__c,id,Start_time__c,End_Time__c,Owner__c,Minutes__c,Duration__c,Id_Text__c,Id_Before_Decimal__c,Is_Stack__c,Dependency_Type__c from Task__c where SOE__c =: sid and Stage_Level__c = 'Implementation' order by Id_Before_Decimal__c,Id_After_Decimal__c]);       
                DepList = [select id,Task__c,Task__r.ID_Text__c,Preceeding_Task__c,Preceeding_Task__r.ID_Text__c,Dep_Type__c,Type__c from Dependency__c where Task__c IN: TaskList.keyset() and Dependent_Type__c = 'Predecessors' ];       
        return new WrapperClass(TaskList.values(), DepList);
        }
        return null;
    }
    global class WrapperClass{
        public list<Task__c> Tasks{get;set;}
        public list<Dependency__c> Deps{get;set;}
        public WrapperClass(list<Task__c> task, List<Dependency__c> Dep){
            Tasks = task; Deps = Dep;
        }
    }
    public pagereference OpenCancel(){
        return new pagereference('/apex/AllTasks_ClientSide?id='+SOEId);
    }
}