temp/objects/Dependency__c.object
<CustomObject>
    <fields>
        <fullName>Dep_Type__c</fullName>
        <label>Dep Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Link</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent_Type__c</fullName>
        <label>Dependent Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Predecessors</fullName>
                </value>
                <value>
                    <fullName>Successors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preceeding_SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preceeding SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Dependencies (Prec/Succ STP)</relationshipLabel>
        <relationshipName>Dependencies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preceeding_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preceeding Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Dependencies (Pred/Suc Task)</relationshipLabel>
        <relationshipName>Dependencies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Dependencies</relationshipLabel>
        <relationshipName>Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Dependencies</relationshipLabel>
        <relationshipName>Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FS</fullName>
                    <default>true</default>
                    <label>FS</label>
                </value>
                <value>
                    <fullName>SS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dependency</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>IF(Days__c!=0,TEXT(Days__c) +&apos;d &apos;,&apos;&apos;)+ TEXT( Hours__c )+&apos;h &apos;+TEXT( Minutes__c )+&apos;m&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>End Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stack_Owner_Name__c</fullName>
        <formula>Owner__r.Member__r.Name</formula>
        <label>Stack Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Running&apos;,IMAGE(&quot;/resource/I8__Running&quot;,&quot;Running&quot;,20,20),
IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),
IF(TEXT(Status__c) = &apos;Waiting&apos;,IMAGE(&quot;/resource/I8__waiting&quot;,&quot;Pending&quot;,17,17),
IF(TEXT(Status__c) = &apos;Ready&apos;,IMAGE(&quot;/resource/I8__ready&quot;,&quot;Ready&quot;,21,22),
IF(TEXT(Status__c) = &apos;Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),
IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),
IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__schedule&quot;,&quot;Scheduled&quot;,20,20),
IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20), 
IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;ReRun&apos;,IMAGE(&quot;/resource/I8__rerun&quot;,&quot;ReRun&quot;,20,20),
IF(TEXT(Status__c) = &apos;To Be Released&apos;,IMAGE(&quot;/resource/I8__ToBeReleased&quot;,&quot;To Be Released&quot;,20,20),
IF(TEXT(Status__c) = &apos;Completed-Jump&apos;,IMAGE(&quot;/resource/I8__completedjump&quot;,&quot;completedjump&quot;,20,20),
IF(TEXT(Status__c) = &apos;Force Completed&apos;,IMAGE(&quot;/resource/I8__forcecomplete&quot;,&quot;Force Completed&quot;,18,18), 
IF(Jump__c = true,IMAGE(&quot;/resource/I8__jump&quot;,&quot;Jump&quot;,24,24),
null)))))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF((Is_Stack__c=true),&apos;stage&apos;,
IF((End_Stack__c =true),&apos;Check point&apos;,
IF(AND((Is_Stack__c=false),(End_Stack__c =false)) ,&apos;Task&apos;,
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/PDF_cntrl.cls
/* 
Class Name        : PDF_cntrl 
Test Class Name   : Test_PDF_cntrl
Purpose/Overview  : To export SOE and TAsks to PDF and CSV 
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class PDF_cntrl {    
    public list<task__c> task{get;set;}           
    public list<soe__c> soelist{get;set;}
    public Id SOEId{get;set;}
    public string displayfields {get;set;}
    public Map<string,string> labelMap{get;set;}
    public list<string> str{get;set;}
    public list<wrapperClass> WrapperList{get;set;}
    public PDF_cntrl (){
        str=new list<string>();
        labelMap = new map<string,string>();
        SOEId = ApexPages.currentPage().getParameters().get('id');  
        displayfields = String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('fields')) ;
        WrapperList = new list<wrapperClass>();
        If(Utils.isAccessible('i8__Task__c') && Utils.isAccessible('i8__Dependency__c'))
        task = [select id,Is_Stack__c ,End_Stack__c ,SOE__r.Name,SOE__r.SOE_Title__c,Name,Description__c,Stage_Level__c,Stack_Owner_Name__c,Team__c,Task_Title__c,Stage__c,Start_Time__c,Duration__c,End_Time__c,
        (select id,Dep_Type__c ,Type__c,Dependent_Type__c,Preceeding_Task__r.ID_Text__c,Preceeding_Task__r.Task_Title__c,Preceeding_Task__r.State__c,Preceeding_SOE__r.SOE_Title__c,SOE__r.SOE_Title__c,Preceeding_Task__r.Status__c from Dependencies__r where Preceeding_Task__c != null order by Preceeding_Task__r.ID_Text__c)
        State__c,ID_Text__c,Id_After_Decimal__c,Id_Before_Decimal__c,Soe__c,Status__c from task__c where soe__c =: SOEId and Stage_Level__c = 'Implementation' order by Stage_Level__c ,Id_Before_decimal__c,Id_After_Decimal__c limit 1000];                                     
        for(Task__c tas: task){
            string str1='',str2='';
            for(Dependency__c dep: tas.Dependencies__r){
                if(dep.Dependent_Type__c == 'Predecessors')
                    str1 += dep.Type__c +'-'+dep.Preceeding_Task__r.ID_Text__c+',';
                else 
                    str2 += dep.Type__c +'-'+dep.Preceeding_Task__r.ID_Text__c+',';
            }
            if(str1.length() > 3)
                str1 = str1.substring(0,str1.length()-1);
            if(str2.length() > 3)
                str2 = str2.substring(0,str2.length()-1);
            if(str1 =='')
                str1 = 'None';
            if(str2 == '')
                str2 = 'None';
            WrapperList.add(new WrapperClass(tas,str1,str2));
        }
   }
   public class wrapperClass{
       public task__c tas{get;set;}
       public string Pred{get;set;}
       public string Succ{get;set;}
       public wrapperClass (Task__c tas1, string pre,string suc){
           Tas = tas1; Pred = pre; Succ = suc;
       }
   }     
    public PageReference getfields() {  
        soelist = new List<SOE__c>(); 
        List<String> SplitList = displayfields.split(','); 
        for(string field : SplitList ){         
            if(field == 'I8__programme__r.Name' )
                labelMap.put(field,'Programme');
             else if(field == 'I8__Project__r.Name' )
                labelMap.put(field,'Project');
             else if(field == 'I8__Department__r.name' )
                labelMap.put(field,'Department');
              else if(field == 'I8__QA_Manager__r.name' )
                labelMap.put(field,'QA Manager');   
             else
                 labelMap.put(field,Schema.getGlobalDescribe().get('I8__Soe__c').getDescribe().fields.getMap().get(field).getDescribe().getLabel());
        }
        str.addAll(labelMap.keyset());
        if(UTils.isAccessible('i8__SOE__c')){
            string  soequery1 = 'Select ' + displayfields+' from  I8__Soe__c where id =: SOEId';
            soelist = Database.query(String.escapeSingleQuotes(soequery1)); 
        }
        return null;
    }      
}