temp/objects/Expense_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <label>Employee Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expense_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_Of_Claims__c</fullName>
        <label>No Of Claims #</label>
        <summaryForeignKey>Expenses__c.Expense_Claim__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Claim_Amount__c</fullName>
        <label>Total Claim Amount</label>
        <summarizedField>Expenses__c.Amount__c</summarizedField>
        <summaryForeignKey>Expenses__c.Expense_Claim__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>EC-{000000}</displayFormat>
        <label>Expense Claim #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Expenses__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Claim__c</fullName>
        <label>Expense Claim</label>
        <referenceTo>Expense_Claim__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <label>Expense Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boarding</fullName>
                </value>
                <value>
                    <fullName>Airfare</fullName>
                </value>
                <value>
                    <fullName>Other Airfare</fullName>
                </value>
                <value>
                    <fullName>Other Expenses</fullName>
                </value>
                <value>
                    <fullName>Travel by Own Car</fullName>
                </value>
                <value>
                    <fullName>Car Parking Charges</fullName>
                </value>
                <value>
                    <fullName>Visa Fees</fullName>
                </value>
                <value>
                    <fullName>Relocation Accommodation &amp; Conv.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SOE__c</field>
                <operation>equals</operation>
                <valueField>Task__c.SOE__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expenses</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Expenses_cntrl.cls
/* 
Class Name        : Expenses_cntrl
Test Class Name   : Test_Expenses_cntrl
Purpose/Overview  : To add Expenses to an SOE.
Author            : Purview Ltd.
Code Coverage     : 100%.
Change History    : 
*/
public with sharing class Expenses_cntrl {
    public ID ExpClaimID{get;set;}
    public boolean error{get;set;}
    public string errorMessage{get;set;}
    public Expense_Claim__c ExpClaim{get;set;} 
    public List<Expenses__c> entryList{get;set;}
    public list<Expenses__c> Original_expenseslist; 
    public List<WrapperClass> WrapperList{get;set;}
    public List<Expenses__c> deletEntryList;
    public String deleteID;
    
    public Expenses_cntrl(ApexPages.StandardController controller) {
    WrapperList = new list< WrapperClass>();
        ExpClaimID = ApexPages.currentPage().getParameters().get('id');
        
        if(ExpClaimID != null){
      
        deletEntryList = new list<Expenses__c>();
        if(Utils.isAccessible('I8__Expense_Claim__c') && Utils.isAccessible('I8__Expenses__c')){
        Original_expenseslist = new list<Expenses__c>();
        ExpClaim = [Select id, Name, From_Date__c, To_Date__c, Employee_Name__c, Manager__c,Total_Claim_Amount__c, No_Of_Claims__c  From Expense_Claim__c where id =: ApexPages.currentPage().getParameters().get('id')];
        UpdateLists();
        If(WrapperList.size() < 1)
            AddEntry();
         }else{error=true;errorMessage = System.Label.AddTask001;}
         }
    }
    public class WrapperClass{
        public Expenses__c Exp{get;set;}
        public Integer Count{get;set;}
        public WrapperClass(Expenses__c exp1, integer cnt){
            Exp = exp1;
            Count = cnt;
        }
    } 
    public void UpdateLists(){      
        
        Integer cnt =0;  
        if(Utils.isAccessible('I8__Expenses__c'))
        for (Expenses__c exp: [Select Id, Expense_Claim__c,CreatedDate,Date__c, SOE__c, Task__c, Expense_Type__c,Payment_Type__c, Amount__c,Description__c From Expenses__c Where Expense_Claim__c =: ExpClaimID order by createddate ]){
            Original_expenseslist.add(exp.clone(true,true,false,true)); 
            WrapperList.add(new WrapperClass(exp,cnt));
            cnt++;
        }
    }
    public PageReference AddEntry()
    {        
        if(WrapperList.SIze() == 0)
            WrapperList.add(new WrapperClass(new Expenses__c(Expense_Claim__c = ExpClaimID),0)); 
        else
            WrapperList.add(new WrapperClass(new Expenses__c(Expense_Claim__c = ExpClaimID,Payment_Type__c='Cash'),WrapperList.Size()));          
        return null;
    }
    public void DeletEntry()
    {  
        deleteID = ApexPages.currentPage().getParameters().get('DeleteId');
        for(Integer i=0;i<  WrapperList.Size();i++){
            if(WrapperList[i].Count == Integer.valueof(deleteID )){
                WrapperLIst[i].exp.Date__c = System.Today();
                 WrapperLIst[i].exp.Expense_Type__c= 'Airfare';
                 WrapperLIst[i].exp.Amount__c = 10;
                if(WrapperList[i].exp.id != null)
                    deletEntryList.add(WrapperList[i].Exp);
                WrapperList.Remove(i);
            }
        }
        list< WrapperClass> WrapperList1 = new list< WrapperClass>();
        for(integer i=0;i< WrapperList.Size(); I++){
            WrapperList1.add(new WrapperClass(WrapperList[i].exp,i));
        }
        WrapperList.Clear();
        WrapperList.AddAll(WrapperList1);
    }
    public pagereference SaveExpenses(){
    Boolean displayError = False;
        entryList = new List<Expenses__c>(); 
        Savepoint sp = Database.setSavepoint();
        boolean bool = false;
        try{
            list<Expenses__c> InsertList = new list<Expenses__c>();
            list<Expenses__c> UpdateList = new list<Expenses__c>();
            
            for(Integer i=0;i<  WrapperList.Size();i++){
            WrapperList[i].exp.Expense_Claim__c = ExpClaimID;
                if(WrapperList[i].exp.Id == null)
                    insertList.add(WrapperLIst[i].exp);
                else 
                    UpdateList.add(WrapperLIst[i].exp);
            }
            if( Utils.isCreateable('I8__Expenses__c')) {
                for(Expenses__c exp : InsertLIst){
                    Error  = Expenses_Validations(exp);
                    if(Error  == true )
                        return null;
                }  
                if(InsertList.Size() > 0 && Utils.isCreateable('I8__Expenses__c'))    
                    insert InsertList;
            }  
            else if(InsertList.Size() > 0){
                displayError = true;
                errorMessage = System.Label.AddTask006;
            }
            list<Expenses__c> expenseList = new list<Expenses__c>();
            if( Utils.isUpdateable('I8__Expenses__c')) {              
                for(Expenses__c exp : UpdateList){
                    Error  = Expenses_Validations(exp);
                    if(Error  == true )
                        return null;
                    else {
                        for(Expenses__c expensesList : Original_expenseslist){
                            if(exp.Id == expensesList.Id && exp != expensesList)
                                expenseList.add(exp);
                        }                        
                    }                    
                } 
                if(expenseList.Size() > 0 && Utils.isUpdateable('I8__Expenses__c'))
                    update expenseList;
            }  
            else if(expenseList.Size() > 0){
                displayError = true;
                errorMessage =    System.Label.AddTask007 ;
            } 
            if(deletEntryList.size() > 0 ){
                if(Schema.sObjectType.Expenses__c.isDeletable())
                    delete deletEntryList;
                else{
                    displayError = true;
                    errormessage = System.Label.AddTask008;
                }
            } 
            if(displayError == false){
                return new pagereference('/'+ExpClaimID);
            } 
            else
                return null; 
        }
        catch (Exception e) {
           Database.rollback(sp);
           LogFactory.error('Expenses_cntrl', 'SaveExpenses', '', e.getMessage() + '' + e.getStackTraceString());  
           LogFactory.SaveLog(); 
           error = true;
           errorMessage = e.getMessage();  
            return null;
        }      
    } 
        public boolean Expenses_Validations(Expenses__c exp){
        boolean bool = false;
        if(exp.Date__c == null) {
                    exp.Date__c.AddError('You must enter value');
                    bool = true;
                }
                if(exp.Expense_Type__c== null) {
                   exp.Expense_Type__c.AddError('You must enter value');
                    bool = true;
                }
                if(exp.Amount__c== null) {
                    exp.Amount__c.AddError('You must enter value');
                    bool = true;
                }
                if(exp.Payment_Type__c== null) {
                    exp.Payment_Type__c.AddError('You must enter value');
                    bool = true;
                }
        return bool;
    }
    public pagereference CancelExpenses(){
       if(ExpClaimID != null)
        return new pagereference('/'+ExpClaimID);
        return null;
    }
}