temp/objects/History__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Dependency Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Task Title</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Minutes</fullName>
                </value>
                <value>
                    <fullName>Technical Detail</fullName>
                </value>
                <value>
                    <fullName>Description</fullName>
                </value>
                <value>
                    <fullName>Milestone</fullName>
                </value>
                <value>
                    <fullName>Dependency Type</fullName>
                </value>
                <value>
                    <fullName>Schedule Start</fullName>
                </value>
                <value>
                    <fullName>Schedule End</fullName>
                </value>
                <value>
                    <fullName>Warning Zone</fullName>
                </value>
                <value>
                    <fullName>BAU Impact</fullName>
                </value>
                <value>
                    <fullName>RAG status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Value__c</fullName>
        <label>Old Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>User History</relationshipLabel>
        <relationshipName>Audits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_Id__c</fullName>
        <label>Task Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>History</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/History_Tracking_Cntrl.cls
/* 
Class Name        : History_Tracking_Cntrl
Test Class Name   : Test_History_Tracking_Cntrl
Purpose/Overview  : To DIsplay History Records related to that SOE.
Author            : Purview Ltd.
Code Coverage     : 100%.
Change History    : 
*/
public with sharing class History_Tracking_Cntrl {
    public list<History__c> HistoryList { get;set;}
    public id SOEid{get;set;}
    Public string SOEidstring{get;set;}
    Public Boolean SOE{get;set;}
    public string errmsg {get;set;}
    
    public  History_Tracking_Cntrl (){
        SOEid=ApexPages.currentPage().getParameters().get('id');
        SOEidstring = string.valueof(SOEid);
        boolean History_Access = Utils.isAccessible('i8__History__c');
            If(SOEidstring.substring(0,3) == SOE__c.sobjecttype.getDescribe().getKeyPrefix()  ){
                 SOE = False;
                if(History_Access )
                    HistoryList = [select id,name,SOE__c,Action__c,Task_Id__c,Old_value__c,New_value__c,Field__c,Modified_By__c from History__c where SOE__c =: SOEid limit 10000];
                else errmsg = System.Label.ADMIN001;
            }
            Else If(SOEidstring.substring(0,3) == MIS__c.sobjecttype.getDescribe().getKeyPrefix()){
                SOE = True;
                if(Utils.isAccessible('i8__SOE__c') && History_Access ){
                    List<SOE__c> MISSOE_list = [Select Id,MIS__c from SOE__c where MIS__c =: SOEid];
                    Set<Id> SOEIds = New Set<Id>();
                    for(SOE__c MIS_SOE : MISSOE_list)
                        SOEIds.add(MIS_SOE.id); 
                    HistoryList = [select id,name,SOE__c,Action__c,Task_Id__c,Old_value__c,New_value__c,Field__c,Modified_By__c from History__c where SOE__c IN : SOEIds limit 10000];
                }else errmsg = System.Label.ADMIN001; 
            }
    }
    Public pagereference cancel(){
        If(SOE == True)
            return New PageReference('/apex/MIS_AllTasks?id='+SOEid);
        return New PageReference('/apex/AllTasks_ClientSide?id='+SOEid);
    }
}