temp/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Task__c.SOE__c</field>
                <operation>equals</operation>
                <valueField>$Source.SOE1__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>INC#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <formula>(Total_Completed_Tasks_in_Imp__c / Total_Tasks_In_Imp__c ) * 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completed %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Forecast_Start__c</fullName>
        <label>Min Forecast Start</label>
        <summarizedField>Task__c.Forecast_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Planned_Start__c</fullName>
        <label>Min Planned Start</label>
        <summarizedField>Task__c.Planned_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Start_Time__c</fullName>
        <label>Min Start Time</label>
        <summarizedField>Task__c.Actual_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SOE_RAG__c</fullName>
        <label>SOE RAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Amber</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End__c</fullName>
        <label>Actual End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Forecast_End__c</fullName>
        <label>Forecast End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planned_End__c</fullName>
        <label>Planned End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Run_Delay__c</fullName>
        <formula>IF(OR(ISPICKVAL( Status__c , &apos;Running&apos;),ISPICKVAL( Status__c , &apos;Completed&apos;),ISPICKVAL( Status__c , &apos;Force Completed&apos;)), ( End_Time__c -  Start_Time__c  )*24*60-( Planned_End__c -  Planned_Start__c )*24*60,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Run Delay</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/SOE_SingleDashboard_Cntrl.cls
/* 
Class Name        : SOE_SingleDashboard_Cntrl
Test Class Name   : Test_SOE_SingleDashboard_Cntrl
Purpose/Overview  : To display all critical information related to the SOE in a single page.
Author            : Purview Ltd.
Code Coverage     : 90%.
Change History    : 
*/
global with sharing class SOE_SingleDashboard_Cntrl{  
    public Id SOEId{get;set;}
    public SOE__c soe{get;set;}
    public integer count{get;set;}
    public list<Task__c> MilestoneList1{get;set;}
    public list<Task__c> CriticalPath1{get;set;}
    public list<Task__c> MilestoneList2{get;set;}
    public list<Task__c> CriticalPath2{get;set;}
    public i8Constants i8{get;set;}
    public list<Incident__c> Incidents1{get;set;}
    public list<Incident__c> Incidents2{get;set;}
    public String OpenIncidents{get;set;}
    public String ClosedIncidents{get;set;}
    public String OverallStatus{get;set;}
    public SOE_SingleDashboard_Cntrl()
    {
        SOEId = ApexPages.CurrentPage().getParameters().get('id'); 
        if(Utils.isAccessible('i8__SOE__c')) {
            soe = [select id,Name,SOE_RAG__c,Completed__c,SOE_Title__c,Dealy_Ahead_mins__c,Max_Planned_End__c,Max_Forecast_End__c,Max_End_Time__c,Min_Forecast_Start__c,Min_Planned_Start__c,Min_Start_Time__c  from SOE__c where id=: SOEId];
        if(soe.Dealy_Ahead_mins__c > 0)
            OverallStatus = 'red';
        else
            OverallStatus = 'green';
        if(soe.SOE_RAG__c=='amber')
            soe.SOE_RAG__c='Orange';  
        i8 = new I8Constants();
        if(UTils.isAccessible('i8__Task__c')){
            count = Database.countquery('select count() from Task__c where SOE__c =: SOEId');
            MilestoneList1 = [select id,name,Milestone__c,Planned_End__c,Task_Title__c,ID_Text__c,Forecast_End__c,Actual_End__c,Run_Delay__c from Task__c where SOE__c =: SOEId and Stage__c =: i8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP  and Milestone__c = true and (Status__c =: i8.STATUS_COMPLETED OR Status__c =: i8.STATUS_FORCE_COMP  or Status__c = : i8.STATUS_COMP_JUMP) order by End_Time__c  limit 5]; 
            CriticalPath1 = [select id,name,Critical_Path__c,Planned_End__c,Task_Title__c,ID_Text__c,Forecast_End__c,Actual_End__c,Run_Delay__c from Task__c where SOE__c =: SOEId and Stage__c =: i8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP  and Critical_Path__c != null  and (Status__c =: i8.STATUS_COMPLETED OR Status__c =: i8.STATUS_FORCE_COMP  or Status__c = : i8.STATUS_COMP_JUMP) order by End_Time__c  limit 5]; 
            MilestoneList2 = [select id,name,Milestone__c,Planned_End__c,Task_Title__c,ID_Text__c,Forecast_End__c,Actual_End__c,Run_Delay__c from Task__c where SOE__c =: SOEId and Stage__c =: i8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP  and Milestone__c = false and (Status__c =: i8.STATUS_WAITING_JUMP OR Status__c =: i8.STATUS_WAITING OR Status__c =: i8.STATUS_RUNNING) order by End_Time__c limit 5]; 
            CriticalPath2 = [select id,name,Critical_Path__c,Planned_End__c,Task_Title__c,ID_Text__c,Forecast_End__c,Actual_End__c,Run_Delay__c from Task__c where SOE__c =: SOEId and Stage__c =: i8.STAGE_IMP and Stage_Level__c =: i8.CONTEXT_IMP  and Critical_Path__c != null and (Status__c =: i8.STATUS_WAITING_JUMP OR Status__c =: i8.STATUS_WAITING OR Status__c =: i8.STATUS_RUNNING) order by End_Time__c limit 5]; 
        }
        if(UTils.isAccessible('i8__Incident__c')){
            Incidents1 = [select id,name,Status__c,Priority__c,Summary__c,Inc_Type__c from Incident__c where SOE1__C =: SOEId and Priority__c = 'High' order by createdDate limit 5];
            Incidents2 = [select id,name,Status__c,Priority__c,Summary__c,Inc_Type__c from Incident__c where SOE1__C =: SOEId and Priority__c = 'Medium' order by createdDate limit 5];
            AggregateResult[] closedResults    = [SELECT COUNT(Id) cnt FROM Incident__c WHERE Status__c='Closed' and SOE1__c=:SOEId GROUP BY SOE1__c ];
            if(closedResults != null&& closedResults.SIze() > 0)
                ClosedIncidents=String.valueOf(closedResults[0].get('cnt')); 
            else
                ClosedIncidents ='0';
            AggregateResult[] openedResults    = [SELECT COUNT(Id) cnt FROM Incident__c WHERE Status__c='Open' and SOE1__c=:SOEId GROUP BY SOE1__c ];
            if(openedResults != null&& openedResults.SIze() > 0)
                OpenIncidents=String.valueOf(openedResults[0].get('cnt')); 
            else
                OpenIncidents='0'; 
        }
        String FileName =soe.Name+'-'+soe.SOE_Title__c+'.pdf' ;
        Apexpages.currentPage().getHeaders().put( 'content-disposition', 'inline; filename=' + FileName );
        }
    }
    @RemoteAction    
    global static list<Task__c> getTasks(string sid,integer start,integer end1) {
        list<task__c> TaskList = new list<Task__C>(); 
        list<task__c> TaskList1 = new list<Task__C>();
        if(Utils.isAccessible('i8__Task__c')){         
            TaskList = [select Task_Title__c,id,Start_time__c,End_Time__c,Owner__c,Minutes__c,Duration__c,Id_Text__c,Id_Before_Decimal__c,Planned_End__c,Forecast_End__c  from Task__c where SOE__c =: sid and Stage_Level__c = 'Implementation' and Is_Stack__c = true and Stage__c = 'Imp' order by End_Time__c asc limit 5];       
            integer last;
            if(start+end1 < = Tasklist.Size())
                last = start+end1;
            else
                last = Tasklist.Size();
            for(  integer i=start; i< last;i++)
                TaskList1.add(tasklist[i]);
        }
        return TaskList1 ;
    }
    public pagereference openCancel(){
        return new pagereference ('/apex/AllTasks_ClientSide?id='+SOEId);
    }
}