temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BackOut_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BackOut Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Imp_Baseline_End__c</fullName>
        <label>Imp Baseline End</label>
        <summarizedField>Task__c.Baseline_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Imp_Baseline_Start__c</fullName>
        <label>Imp Baseline Start</label>
        <summarizedField>Task__c.Baseline_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Forecast_Start__c</fullName>
        <label>Min Forecast Start</label>
        <summarizedField>Task__c.Forecast_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Planned_Start__c</fullName>
        <label>Min Planned Start</label>
        <summarizedField>Task__c.Planned_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>QA_Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QA_Review__c</fullName>
        <label>QA Review</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WalkThrough__c</fullName>
        <label>WalkThrough</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SOE_Schedule_Cntrl.cls
/* 
Class Name        : SOE_Schedule_Cntrl
Test Class Name   : Test_SOE_Schedule_Cntrl
Purpose/Overview  : To schedule an SOE .
Author            : Purview Ltd.
Code Coverage     : 96%.
Change History    : 
*/
public with sharing class SOE_Schedule_Cntrl{    
    public SOE__C SOE{get;set;}
    public string errormessage{get;set;}
    public boolean errorbool{get;set;}
    public string page{get;set;}
    public integer duration{get;set;}
    public static boolean BoolChanges{get;set;}
    public integer SOE_Duration{get;set;}
    public datetime Change_end_time{get;set;}
    public datetime Change_end_time1{get;set;}
    public I8Constants i8{get;set;}
    public string[] errmsg{get;set;}
    Public boolean review{get;set;}
    Public Map<Id,Id> ImpMgrMap{get;set;}
    Id SOEId;
    
    public SOE_Schedule_Cntrl(){
        page = ApexPages.CurrentPage().getParameters().get('page');
        errmsg = new list<string>();
        i8 = new I8Constants();
        SOEId = ApexPages.CurrentPage().getParameters().get('Id');
        if(Utils.isAccessible('i8__SOE__c')) {
        SOE = [select id,SOE_Title__c,Backout_STage__c,Schedule_Start__c,Schedule_End__c,QA_Review_Required__c,QA_Review__c,Walkthrough__c ,Warning_Zone__c,BAU_Impact__c,Imp_Baseline_End__c,Min_Forecast_Start__c,Imp_Baseline_Start__c,Status__c ,Min_PLanned_Start__C,State__c ,Name,Max_Planned_End__c,Max_Forecast_End__c,Dealy_Ahead_mins__c,Max_End_Time__c from SOE__c where id=:SOEId];
        ImpMgrMap = new Map<Id,Id>();
        if(Utils.isAccessible('i8__SOE_Team_Member__c'))
        for( SOE_Team_Member__c imp : [select Id,Name,Team_Member__r.Salesforce_User__c,Access_Level__c  from SOE_Team_Member__c where SOE__c =: SOE.id  and Access_Level__c = 'Read' ])  
            ImpMgrMap.put(imp.Team_Member__r.Salesforce_User__c,imp.Team_Member__r.Salesforce_User__c);
        If((SOE.QA_Review_Required__c == True && SOE.QA_Review__c != 'Complete') || (SOE.Status__c == i8.STATUS_BUILD)){
            review = True;
            errmsg.add( System.Label.Schedule001);
        }
        else If( SOE.QA_Review__c == 'In Progress' || SOE.Walkthrough__c == 'In Progress'){
            review = True;
            errmsg.add( System.Label.AddTask003);
        }
        else if(ImpMgrMap.containskey(UserInfo.getUserId() ) ){
            review = True;
            errmsg.add( System.Label.AddTask001);
        }
        Else{           
            errormessage =''; 
            errorbool = false;
            if(SOE.Status__c == i8.STATUS_BUILD || SOE.Status__c == i8.STATUS_REVIEW)
                duration  = Integer.valueof((SOE.Imp_Baseline_End__c.getTime() - SOE.Imp_Baseline_Start__c.getTime())/(1000*60));
            else
                duration  = Integer.valueof((SOE.Max_End_Time__c.getTime() - SOE.Min_Forecast_Start__c.getTime())/(1000*60));
            if(duration != 0){            
                if(SOE.Schedule_Start__c != null){           
                    Change_end_time1 = SOE.Schedule_Start__c.addminutes(duration);
                    date mydate = Date.newInstance(Change_end_time1.year(),Change_end_time1.month(),Change_end_time1.day());
                    time mytime = time.newInstance(Change_end_time1.hour(),Change_end_time1.minute(),Change_end_time1.second(),Change_end_time1.millisecond());
                    Change_end_time = DateTime.newInstancegmt(myDate, myTime);
                }            
            }        
            BoolChanges = false;
        }
        }else { review = true; errmsg.add( System.Label.ADMIN001);}
    }   
    public pagereference Apply(){ 
        errorbool = false; 
        errmsg.clear();   
        if(Utils.isUpdateable('i8__SOE__c')){
            Savepoint sp = Database.setSavepoint();
            try{
            change_end();
            if(SOE.Schedule_Start__c == null){  
                errmsg.add( System.Label.Schedule002);
                errorbool = true;          
            }else if(SOE.Schedule_Start__c <= system.now()){ 
                errmsg.add( System.Label.Schedule004);
                errorbool = true;               
            }   
            if(SOE.Schedule_End__c == null ){  
                errmsg.add(System.Label.Schedule003);
                errorbool = true;  
            }
            if(SOE.Schedule_End__c < Change_end_time1 ){  
                errmsg.add(System.Label.Schedule005);
                errorbool = true;  
            }
            if(SOE.BAU_Impact__c == null){          
                errmsg.add(System.Label.Schedule006);      
                errorbool = true;           
            }
            if(SOE.Schedule_Start__c != null && SOE.Schedule_End__c != null && SOE.Schedule_Start__c >= SOE.Schedule_End__c){  
                errmsg.add(System.Label.Schedule007);
                errorbool = true;              
            }        
            if(SOE.BAU_Impact__c != null && SOE.Schedule_Start__c != null && SOE.Schedule_End__c != null && SOE.Warning_Zone__c == null){
                SOE.Warning_Zone__c = SOE.BAU_Impact__c;            
            } 
            if(SOE.Warning_Zone__c != null && SOE.Schedule_End__c != null && SOE.Schedule_End__c > SOE.Warning_Zone__c){  
                errmsg.add(System.LAbel.Schedule008);
                errorbool = true;              
            } 
            if(SOE.BAU_Impact__c != null && SOE.Schedule_End__c != null && SOE.Schedule_End__c > SOE.BAU_Impact__c){ 
                errmsg.add(System.Label.Schedule009);
                errorbool = true;             
            }
            if(SOE.BAU_Impact__c != null && SOE.Warning_Zone__c != null && SOE.Warning_Zone__c > SOE.BAU_Impact__c){ 
                errmsg.add(System.Label.Schedule010);
                errorbool = true;           
            }              
            if(errorbool == false  ){ 
                SOE_duration = integer.valueof((SOE.Schedule_End__c.GetTime()-SOE.Schedule_Start__c.GetTime())/(1000*60));           
                if(SOE.Status__c == i8.STATUS_REVIEW)
                    SOE.Status__c =  i8.STATUS_SCHEDULED ; 
                if(Utils.isUpdateable('i8__SOE__c'))            
                    update SOE;            
                BoolChanges = true;
                Task_triggerHandler.UpdateAllTasks(new list<string>{SOE.Id},i8.CONTEXT_IMP); 
                if(SOE.Backout_STage__c == true)
                    Task_TriggerHandler.UpdateAllTasks(new list<string>{SOE.Id},i8.CONTEXT_BO);
                if(page == 'detail')   
                    return new pagereference('/'+SOE.id);
                else 
                    return new pagereference('/apex/AllTasks_ClientSide?id='+SOE.id);
            }
            }
            catch(Exception e){
                       Database.rollback(sp);
                       LogFactory.error('SOE_Schedule_Cntrl', 'Apply', '', e.getMessage() + '' + e.getStackTraceString());  
                       LogFactory.SaveLog(); 
                       errorbool = true; 
                       errormessage= e.getMessage();                  
                }
        } else {errorbool = true;errormessage = System.Label.ADDTASK007;}
        return null; 
    }
    public PageReference change_end() {         
        if(duration != 0 && SOE.Schedule_Start__c != null){  
            if(SOE.Schedule_Start__c != null){                 
                Change_end_time1 = SOE.Schedule_Start__c.addminutes(duration);
                date mydate = Date.newInstance(Change_end_time1.year(),Change_end_time1.month(),Change_end_time1.day());
                time mytime = time.newInstance(Change_end_time1.hour(),Change_end_time1.minute(),Change_end_time1.second(),Change_end_time1.millisecond());
                Change_end_time = DateTime.newInstancegmt(myDate, myTime);
            }
        }        
        return null;
    }
     public pagereference Cancel(){
        if(page == 'detail'){
            if(UserInfo.getUiThemeDisplayed() == 'Theme3')
                return new PageReference('javascript:window.close()');
            else
                return new pagereference('/'+SOEId);
        }
        else
            return new pagereference('/apex/AllTasks_ClientSide?id='+SOEId);
    }
}