temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Role__c</fullName>
        <label>Reference Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Imp Manager</fullName>
                    <default>true</default>
                    <label>Imp Manager</label>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Incident Manager</fullName>
                </value>
                <value>
                    <fullName>Task Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Task_Document_cntrl.cls
/* 
Class Name        : Task_Document_cntrl 
Test Class Name   : Test_Task_Document
Purpose/Overview  : To add attachment to the task. 
Author            : Purview Ltd.
Code Coverage     : 93%
Change History    : 

*/
public with sharing class Task_Document_cntrl {
    public string page{get;set;}
    public string fileName{get;set;}     
    public Transient Blob fileBody {get;set;}  
    public Id recId {get;set;} 
    public id ParentId{get;set;} 
    public Task__c task{get;set;}
    Public SOE__c SOE{get;set;}
    public string AttId{get;set;}
    public list<Attachment>AttachList{get;set;} 
    public boolean checkerror{get;set;}    
    Public Map<Id,Id> ImpMgrMap{get;set;}
    public string ImpMgrMapKey{get;set;}
    public string errormsg{get;set;}
    public string AcceptedDocType {get;set;}
    public Integer FileSize{get;set;}
    Id SOEId;
    
    public Task_Document_cntrl(ApexPages.StandardController controller){
        recId =controller.getRecord().Id; 
        page = ApexPages.currentPage().getParameters().get('page');
        SOEId = ApexPAges.CurrentPage().getParameters().get('SId');
        AcceptedDocType = SystemSettings_Util.getSystemSettings().get('Accepted_Document_Types');
        checkerror = false;
        errormsg = null;
        if(Utils.isAccessible('i8__Task__c') && Schema.SobjectType.Attachment.isAccessible()){
            task=[select id,ID_Text__c,Stage__c,Stage_Level__c,Task_Title__c,soe__c,Id_Before_Decimal__c,soe__r.SOE_Title__c,soe__r.Status__c,soe__r.Name from Task__c where id=:recId ];
            if(Utils.isAccessible('i8__SOE__c'))
                SOE = [select id,name,SOE_Title__c,Status__c,Max_End_Time__c,Max_Forecast_End__c,Dealy_Ahead_mins__c,Max_Planned_End__c from SOE__c where id =: Task.SOE__c];
            ImpMgrMap = new Map<Id,Id>();
            list<string> RolesLIst = System.Label.Roles_To_Edit_SOE.split(',');
            if(Utils.isAccessible('i8__SOE_Team_Member__c'))
                for( SOE_Team_Member__c imp : [select Id,Name,Team_Member__r.Salesforce_User__c,Access_Level__c  from SOE_Team_Member__c where SOE__c =: Task.soe__c  and Access_Level__c != 'Read' and Role__r.Reference_Role__c  IN: RolesLIst ])  
                    ImpMgrMap.put(imp.Team_Member__r.Salesforce_User__c,imp.Team_Member__r.Salesforce_User__c);
            if(Schema.SObjectType.Profile.isAccessible())
                if([Select Id,Name from Profile where Id=:userInfo.getProfileId()].Name == 'System Administrator')
                    ImpMgrMap.put(userInfo.getUserId(),userInfo.getUserId());
            ImpMgrMapKey = string.valueof(ImpMgrMap.keyset()).replace('{', '').replace('{', '');        
            AttachList = [select id,Name,BodyLength,ownerid,createddate,ContentType  from Attachment where parentid=: task.Id order by createddate desc limit 1000]; 
        }else errormsg = System.Label.ADMIN001 ;
    }
    public pagereference  upload() {
        if(Schema.SOBjectType.Attachment.isCreateable()){
            Savepoint sp = Database.setSavepoint();
            try{         
                if(fileName != null && AcceptedDocType.contains(filename.substringAfterLast('.')) && FileSize > 0){
                    Attachment myAttachment  = new Attachment();
                    checkerror = false;  
                    errormsg = null;
                    myAttachment.Name = fileName;
                    myAttachment.Body = fileBody;             
                    myAttachment.ParentId = recId;
                    if(myAttachment.Body == null){
                        checkerror = true;
                        errormsg = System.Label.SOEAttachment003;
                    } 
                    else{ 
                        LogFactory.debug('Task_Document_Cntrl', 'Upload', 'Attachment', 'Attachment got Successfully','Line - 55'); 
                        if(Schema.SobjectType.Attachment.isCreateable())
                            insert myAttachment; 
                        filename = null;
                        filebody = null;                      
                        if(Schema.SOBjectType.Attachment.isAccessible())
                        AttachList = [select id,Name,BodyLength,ownerid,createddate,ContentType  from Attachment where parentid=: task.Id order by createddate desc];               
                    }
                }
                else if(FileSize == 0){
                    checkerror = true;
                    errormsg = System.Label.SOEAttachment006;
                }
                else{
                    checkerror = true;
                    errormsg = System.label.SOEAttachment003+' '+AcceptedDocType+' and FileSize must be less than 10MB'; 
                }
            }catch(Exception e){
                Database.rollback(sp);
                LogFactory.error('Task_Document_Cntrl', 'Upload', '', e.getMessage() + '' + e.getStackTraceString());           
                checkerror = true;
                errormsg = e.getMessage();                  
            }
        }else errormsg = System.Label.ADMIN001;
        LogFactory.SaveLog(); 
        return null;
    }    
    public pagereference delete_attachment(){
        if(Schema.SOBjectTYpe.Attachment.isDeletable() && Schema.SOBjectType.Attachment.isAccessible()){
            Savepoint sp = Database.setSavepoint();
            try{
                Attachment delAttachment  = new Attachment();
                delAttachment = [select id from Attachment where id =: AttId limit 1]; 
                if(Schema.SOBjectType.Attachment.isDeletable())
                    delete delAttachment;    
                AttachList = [select id,Name,BodyLength,ownerid,createddate,ContentType  from Attachment where parentid=: task.Id order by createddate desc limit 1000];
            }catch(Exception e){
                Database.rollback(sp);
                LogFactory.error('Task_Document_cntrl', 'delete_attachment', '', e.getMessage() + '' + e.getStackTraceString());  
                LogFactory.SaveLog(); 
                checkerror = true;
                errormsg = e.getMessage();                  
            }
        } else errormsg = System.Label.ADMIN001;
        return null;
    }
    public pagereference close_action(){
        if(page=='EditStack' && Utils.isAccessible('i8__Task__c')){
            task__c tas = [select id,Id_Before_Decimal__c,SOE__c from task__c where IS_STack__c = true and SOE__C =: task.SOE__c and Stage__c =: task.Stage__c and Id_Before_Decimal__c =: task.Id_Before_Decimal__c ];
            return new PageReference('/apex/EditStack_ClientSide?id='+tas.id +'&SId='+task.SOE__c);
        }
        else if(page=='Modify_Task'){
            Id MISID = ApexPages.CurrentPage().getParameters().get('Mid');
            if(MISID == null)
                return new PageReference('/apex/ModifyTask_ClientSide?id='+recId+'&Sid='+task.SOE__c +'&level='+task.Stage_Level__c+'&page=edit');
            else
                return new PageReference('/apex/ModifyTask_ClientSide?id='+recId+'&Mid='+MISID +'&level='+task.Stage_Level__c+'&page=edit');
        }
        else{
            Id MISID = ApexPages.CurrentPage().getParameters().get('Mid');
            if(MISID != null)
                return new PageReference('/apex/MIS_AllTasks?id='+MISID );
            else
                return new PageReference('/apex/AllTasks_ClientSide?id='+SOEId ); 
        }       
    }
}