temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>QA_Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QA_Review__c</fullName>
        <label>QA Review</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WalkThrough_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Walkthrough Manager is default Implementation Manager.</inlineHelpText>
        <label>WalkThrough Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WalkThrough__c</fullName>
        <label>WalkThrough</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>End Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Running&apos;,IMAGE(&quot;/resource/I8__Running&quot;,&quot;Running&quot;,20,20),
IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),
IF(TEXT(Status__c) = &apos;Waiting&apos;,IMAGE(&quot;/resource/I8__waiting&quot;,&quot;Pending&quot;,17,17),
IF(TEXT(Status__c) = &apos;Ready&apos;,IMAGE(&quot;/resource/I8__ready&quot;,&quot;Ready&quot;,21,22),
IF(TEXT(Status__c) = &apos;Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),
IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),
IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__schedule&quot;,&quot;Scheduled&quot;,20,20),
IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20), 
IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;ReRun&apos;,IMAGE(&quot;/resource/I8__rerun&quot;,&quot;ReRun&quot;,20,20),
IF(TEXT(Status__c) = &apos;To Be Released&apos;,IMAGE(&quot;/resource/I8__ToBeReleased&quot;,&quot;To Be Released&quot;,20,20),
IF(TEXT(Status__c) = &apos;Completed-Jump&apos;,IMAGE(&quot;/resource/I8__completedjump&quot;,&quot;completedjump&quot;,20,20),
IF(TEXT(Status__c) = &apos;Force Completed&apos;,IMAGE(&quot;/resource/I8__forcecomplete&quot;,&quot;Force Completed&quot;,18,18), 
IF(Jump__c = true,IMAGE(&quot;/resource/I8__jump&quot;,&quot;Jump&quot;,24,24),
null)))))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF((Is_Stack__c=true),&apos;stage&apos;,
IF((End_Stack__c =true),&apos;Check point&apos;,
IF(AND((Is_Stack__c=false),(End_Stack__c =false)) ,&apos;Task&apos;,
null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Search_and_Replace_cntrl.cls
/* 
Class Name        : Search_and_Replace_cntrl
Test Class Name   : Test_Search_and_Replace_cntrl
Purpose/Overview  : To search and replace some fields with particular values.
Author            : Purview Ltd.
Code Coverage     : 100%.
Change History    : 
*/
public with sharing class Search_and_Replace_cntrl {
    public map<string,string> map1{get;set;}
    public set<string> strings{get;set;} 
    public String strng { get; set; }
    public boolean selectall { get; set; }
    public boolean str1 {get;set;}
    public string str{get;set;}
    public Task__c taskobj { get; set; }
    public id SOEid{get;set;}
    public SOE__c SOEobj{get;set;}
    public boolean Technical_DetailCheck { get; set; }
    public boolean DescriptionCheck { get; set; }
    public boolean TitleCheck { get; set; }    
    public boolean Filter_check { get; set; }
    public String Replace { get; set; }
    public String Search_string { get; set; }
    public list<WrapperTasks> WrapperList{get;set;}
    public list<task__c> TaskList{get;set;}
    public list<task__C> TaskList1{get;set;}
    public string SearchValue{get;set;}
    public list<string> searchlist1{get;set;}  
    public boolean checkboxvalue{get;set;}
    public boolean displayPopup {get; set;}
    Public Map<Id,Id> ImpMgrMap{get;set;}
    public string ImpMgrMapKey{get;set;}
    public boolean error{get;set;}
    public string errormessage{get;set;}
    boolean Task_Access;
    
    public Search_and_Replace_cntrl(){  
        strings = new set<string>();       
        taskobj = new Task__c ();
        map1=new map<string,string>();
        SOEobj=new SOE__c();
        taskobj.Stage_Level__c='Implementation';
        SearchValue='';
        Search_string ='';
        checkboxvalue=false;
        Filter_check =true; 
        displayPopup = false; 
        error = false;
        strng='';        
        checkboxvalue = false;
        SOEid=Apexpages.currentPage().getParameters().get('id'); 
        Task_Access = Utils.isAccessible('i8__Task__c');
        if(Task_Access){
            if(Utils.isAccessible('i8__SOE__c'))
                SOEobj=[select id,name,SOE_Title__c,State__c,status__c,QA_Review_Required__c,QA_Review__c,WalkThrough_Required__c,WalkThrough__c from SOE__c where id=:SOEId];
            ImpMgrMap = new Map<Id,Id>();
            if(Utils.isAccessible('i8__SOE_Team_Member__c'))
            for( SOE_Team_Member__c imp : [select Id,Name,Team_Member__r.Salesforce_User__c,Access_Level__c  from SOE_Team_Member__c where SOE__c =: SOEObj.Id  and Access_Level__c = 'Read' ])  
                ImpMgrMap.put(imp.Team_Member__r.Salesforce_User__c,imp.Team_Member__r.Salesforce_User__c);
            ImpMgrMapKey = string.valueof(ImpMgrMap.keyset()).replace('{', '').replace('{', '');
            TaskList1= new list<task__c>();
            searchlist1=new list<string>();
            TaskList =[select id,SOE__C,Is_Stack__c,State__c,Status__c,Stage_Level__c,Type__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c from Task__C where SOE__c =:SOEid and Stage_Level__c =: taskobj.Stage_Level__c order by Id_Before_Decimal__c,Id_After_Decimal__c,Stage__c asc limit 1000]; 
            TaskWithWrapper(TaskList);
        }else {error = true;errormessage = System.Label.ADMIN001;}
    }
    public class WrapperTasks{
        public boolean check{get;set;}
        public Task__c task{get;set;}
        public WrapperTasks(boolean b,Task__c t){
            check = b;
            task =t;
        }
    }
    public void TaskWithWrapper(list<Task__c> TaskList){
        WrapperList = new List<WrapperTasks>();
        for(Task__c t: TaskList )  {  
            WrapperList.add(new WrapperTasks(false,t));
        } 
    }
    public void Go_Method() {  
        error = false;
        if(Task_ACCESS){
            if(SearchValue!= ''){ 
                String Search1 = '%' + SearchValue + '%';
                TaskList1 = [select id,SOE__C,Is_Stack__c,Type__c,State__c,Status__c,Stage_Level__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c
                             from Task__c where SOE__c=: SOEId and Stage_Level__c =: taskobj.Stage_Level__c And (Stage__c like :Search1 or ID_Text__c like :Search1 or Task_Title__c like :Search1 or Status__c like :Search1  ) order by Id_After_Decimal__c,Id_Before_Decimal__c asc ];
            }
            else{
                TaskList1= [select id,SOE__C,Is_Stack__c,State__c,Type__c,Status__c,Stage_Level__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c from Task__C where SOE__c =:SOEid and Stage_Level__c =: taskobj.Stage_Level__c order by Id_Before_Decimal__c,Id_After_Decimal__c asc];
                TaskWithWrapper(TaskList1);
            }
            TaskWithWrapper(TaskList1); 
            if(SearchValue=='' ){
                TaskList1= [select id,SOE__C,Is_Stack__c,State__c,Status__c,Type__c,Stage_Level__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c from Task__C where SOE__c =:SOEid and Stage_Level__c =: taskobj.Stage_Level__c order by Id_Before_Decimal__c,Id_After_Decimal__c asc];
                TaskWithWrapper(TaskList1);
            } 
        } else{error = true;errormessage = System.Label.ADMIN001;}                                     
        SearchValue='';            
    }
    public PageReference Replace_action() {    
        if(Task_Access && Utils.isUpdateable('i8__Task__c')) {
            Savepoint sp = Database.setSavepoint();
            try{
                error = false;
                list<task__c> taskchecklist= new list<task__c>(); 
                if(Search_string == '' || Search_string == null){
                    errormessage = SYstem.Label.SOEReplace001;
                    error = true;
                    return null;
                }        
                for(WrapperTasks wt:WrapperList ){
                    if(wt.check == true)
                        taskchecklist.add(wt.task);   
                }
                if(taskchecklist.size()==0){
                    errormessage  = SYstem.Label.SOEReplace002;
                    error = true;
                    return null;
                }
                for(task__c t2:taskchecklist){
                    if(TitleCheck == true){
                        str= t2.Task_Title__c;
                        str1=str.contains(Search_string );
                        if(str1==true){
                            t2.Task_Title__c=str.replace(Search_string ,replace);}
                    }
                    if(DescriptionCheck == true){
                        str=t2.Description__c ;
                        if(str=='' || str ==null){
                            errormessage  = SYstem.Label.SOEReplace003 ;
                            error = true;
                            return null;
                        }
                        else{
                            str1=str.contains(Search_string);
                            if(str1==true){
                                t2.Description__c =str.replace(Search_string ,replace);}                
                        }
                    }   
                    if(Technical_DetailCheck == true){
                        str=t2.Technical_Detail__c;
                        if(str=='' || str ==null){               
                            errormessage  = SYstem.Label.SOEReplace004;
                            error = true;
                        }
                        else{
                            str1=str.contains(Search_string );
                            if(str1==true){
                                t2.Technical_Detail__c =str.replace(Search_string ,replace);} 
                        }     
                    }  
                }
                LogFactory.info('Search_and_Replace_cntrl', 'Replace_action', 'Replace String', replace ,'Line - 145'); 
                if(Utils.isUpdateable('i8__Task__c'))    
                    update taskchecklist;
                TaskList =[select id,SOE__C,Is_Stack__c,State__c,Status__c,Stage_Level__c,Type__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c from Task__C where SOE__c =:SOEid and Stage_Level__c =: taskobj.Stage_Level__c order by Id_Before_Decimal__c,Id_After_Decimal__c asc];
                TaskWithWrapper(TaskList);
                Search_string='';
                Replace='';
                TitleCheck= false;
                DescriptionCheck=false;
                Technical_DetailCheck=false;
            }catch(Exception e){
                Database.rollback(sp);
                LogFactory.error('Search_and_Replace_cntrl', 'Replace_action', '', e.getMessage() + '' + e.getStackTraceString());          
                error = true; 
                errormessage = e.getMessage();                  
             }
         }  else {error = true;errormessage = System.Label.ADMIN001;LogFactory.debug('Search_and_Replace_Cntrl', 'Replace Method', 'TaskInfo ', System.Label.ADMIN001,'Line - 170');}       
         LogFactory.SaveLog();
        return null;
    }
    public void SelectAllCheckbox(){
        if(SelectAll == true){
            for(integer i=0;i< WrapperList.size() ; i++)
                WrapperList[i].check = true;             
        }
        else{
            for(integer i=0;i< WrapperList.size() ; i++)
                WrapperList[i].check = false;
        }     
    } 
    public PageReference cancel_method() {
        return new PageReference('/apex/AllTasks_ClientSide?id='+SOEid);
    }    
    public PageReference Clear_Method() {
        SearchValue='';
        if(Task_Access)
            TaskList1= [select id,SOE__C,Is_Stack__c,State__c,Status__c,Type__c,Stage_Level__c ,End_Stack__c,ID_Text__c,Id_After_Decimal__c,Stage__c,Task_Title__c,Id_Before_Decimal__c,Technical_Detail__c,Description__c from Task__C where SOE__c =:SOEid and Stage_Level__c =: taskobj.Stage_Level__c order by Id_Before_Decimal__c,Id_After_Decimal__c asc];
        TaskWithWrapper(TaskList1);
        return null;
    }
}