temp/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>SOE Team Members</relationshipLabel>
        <relationshipName>SOE_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SOE Team Member</label>
    <nameField>
        <displayFormat>SOET-{0000}</displayFormat>
        <label>SOE Team #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOE Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>IF(Days__c!=0,TEXT(Days__c) +&apos;d &apos;,&apos;&apos;)+ TEXT( Hours__c )+&apos;h &apos;+TEXT( Minutes__c )+&apos;m&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RV_Comments__c</fullName>
        <label>RV Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Review_Comments__c</fullName>
        <label>Review Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stack_Owner_Name__c</fullName>
        <formula>Owner__r.Member__r.Name</formula>
        <label>Stack Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Running&apos;,IMAGE(&quot;/resource/I8__Running&quot;,&quot;Running&quot;,20,20),
IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),
IF(TEXT(Status__c) = &apos;Waiting&apos;,IMAGE(&quot;/resource/I8__waiting&quot;,&quot;Pending&quot;,17,17),
IF(TEXT(Status__c) = &apos;Ready&apos;,IMAGE(&quot;/resource/I8__ready&quot;,&quot;Ready&quot;,21,22),
IF(TEXT(Status__c) = &apos;Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),
IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),
IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__schedule&quot;,&quot;Scheduled&quot;,20,20),
IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20), 
IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;ReRun&apos;,IMAGE(&quot;/resource/I8__rerun&quot;,&quot;ReRun&quot;,20,20),
IF(TEXT(Status__c) = &apos;To Be Released&apos;,IMAGE(&quot;/resource/I8__ToBeReleased&quot;,&quot;To Be Released&quot;,20,20),
IF(TEXT(Status__c) = &apos;Completed-Jump&apos;,IMAGE(&quot;/resource/I8__completedjump&quot;,&quot;completedjump&quot;,20,20),
IF(TEXT(Status__c) = &apos;Force Completed&apos;,IMAGE(&quot;/resource/I8__forcecomplete&quot;,&quot;Force Completed&quot;,18,18), 
IF(Jump__c = true,IMAGE(&quot;/resource/I8__jump&quot;,&quot;Jump&quot;,24,24),
null)))))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Build-Jump</fullName>
                </value>
                <value>
                    <fullName>Review-Jump</fullName>
                </value>
                <value>
                    <fullName>Scheduled-Jump</fullName>
                </value>
                <value>
                    <fullName>Freeze-Jump</fullName>
                </value>
                <value>
                    <fullName>Waiting-Jump</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed-Jump</fullName>
                </value>
                <value>
                    <fullName>Force Completed</fullName>
                </value>
                <value>
                    <fullName>Jump</fullName>
                </value>
                <value>
                    <fullName>ReRun</fullName>
                </value>
                <value>
                    <fullName>To Be Released</fullName>
                </value>
                <value>
                    <fullName>&lt;img src=p onerror=alert(42)/&gt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Detail__c</fullName>
        <label>Technical Detail</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Technical_Skills__c</fullName>
        <label>Technical Skills</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WalkThrough_Comments__c</fullName>
        <label>WalkThrough Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Review_Cntrl.cls
/* 
Class Name        : Review_Cntrl 
Test Class Name   : Test_AllTasks_ClientSide_Cntrl
Purpose/Overview  : Complete QA Review and WalkThrough for an SOE. 
Author            : Purview Ltd.
Code Coverage     : 95%
Change History    : 

*/
public with sharing class Review_Cntrl {    
    Public list<task__c> TaskList{get;set;}
    Public list<task__c> QA_TaskList{get;set;}
    Public SOE__c SOE{get;set;}
    Public id SOEID{get;set;}
    public static boolean review_comp{get;set;}
    public i8Constants i8{get;set;}
    public set<String> EmailList = new set<String>();
    Public Integer NextPage{get;set;}
    Public Integer PrevPage{get;set;}
    Public boolean Next{get;set;}
    public String  statusmsg{get;set;}
    boolean Task_Access_Update;
    
    Public Review_Cntrl(){
        statusmsg = null;
        review_comp = false;
        i8 = new i8Constants();
        Next = true;
        TaskList = new list<task__c>();
        QA_TaskList = new list<task__c>();
        SOE = New SOE__c();
        SOEID = ApexPages.CurrentPage().getparameters().get('Id');
        Task_Access_Update = Utils.isAccess_Update('i8__Task__c');
        if(Task_Access_Update)
            TaskList = [select id,name,State__c,Stage__c,RV_Comments__c,WalkThrough_Comments__c,Status__c,ID_Text__c,Technical_Detail__c,Technical_Skills__c,Description__c,Task_Title__c,Start_Time__c,Duration__c,Review_Comments__c,End_Time__c,Stack_Owner_Name__c,Team__c from Task__c where SOE__c =: SOEID and Stage_Level__c=: i8.CONTEXT_IMP order by Id_Before_Decimal__c,Id_After_Decimal__c limit 50000];
        if(Utils.isAccessible('i8__SOE__c'))
            SOE = [select id,name,State__c,QA_Manager__c,QA_Manager__r.FirstName,Owner.FirstName,SOE_Title__c,Status__c,Dealy_Ahead_mins__c,Max_End_Time__c,Max_Forecast_End__c,QA_Review_Required__c,Max_Planned_End__c,QA_Review__c,WalkThrough__c,WalkThrough_Required__c from SOE__c where id =: SOEID];
        NextPage = 0;
        Next();
    }
    
    Public void Next(){
        Integer j = NextPage;
        PrevPage = NextPage;
        NextPage = NextPage + 1000;
        If(NextPage > TaskList.size()){
            NextPage = TaskList.size();
            Next = false;
        }
        If(NextPage > 1000){
            TaskUpdate();
            QA_TaskList.clear();
        }
        For(Integer i=j; i<NextPage; i++){
            QA_TaskList.add(TaskList[i]);
        }
    }
    
    Public void Prev(){
        TaskUpdate();
        Next = true;
        QA_TaskList.clear();
        if(PrevPage > 1000){
            For(Integer i=(PrevPage-1000); i<PrevPage; i++)
                QA_TaskList.add(TaskList[i]);
            PrevPage = PrevPage - 1000;
        }
    }
    
    public Id getWorkItemId(Id targetObjectId){
        Id retVal = null;
        if(Schema.sObjectTYpe.ProcessInstanceWorkitem.isAccessible())
        for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =: SOE.Id])
            retVal  =  workItem.Id;
        return retVal;
    }

    public pagereference QAComplete(){
        if(Task_Access_Update){
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('QA Review Completed ');
            req.setAction('Approve');
            Id workItemId = getWorkItemId(SOE.Id);         
            if(workItemId == null)
                SOE.addError('Error Occured ');
            else        {
                req.setWorkitemId(workItemId);
                Approval.ProcessResult result =  Approval.process(req);
            }
            review_comp =true;
            TaskUpdate();
            return new pagereference('/apex/AllTasks_ClientSide?id='+SOEID);
        }else{LogFactory.debug('Review_Cntrl', 'QA Complete', 'Task Info ', System.Label.ADDTask007,'Line - 93');
        LogFactory.SaveLog();}
        return null;
    }
    
    public pagereference QAFeedBack(){
        if(Task_Access_Update){
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('QA Review is under Feedback');
            req.setAction('Reject');
            Id workItemId = getWorkItemId(SOE.Id);         
            if(workItemId == null)
                SOE.addError('Error Occured ');
            else{    
                integer count =0;    
                req.setWorkitemId(workItemId);
                Approval.ProcessResult result =  Approval.process(req);
                if(Utils.isAccessible('i8__SOE_Team_Member__c'))
                for(SOE_Team_Member__c STM : [select id,name,Team_Member__r.Email__c from SOE_Team_Member__c where SOE__c =: SOE.Id and Role__r.Reference_Role__c= 'Imp Manager'])
                    EmailList.add(STM.Team_Member__r.Email__c);
                List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();
                list<string> AddList = new list<string>();
                AddList.AddAll(EmailList);
                mail.setToAddresses(AddList);
                mail.setSubject('QA Review Rejected for '+SOE.Name +':'+ SOE.SOE_Title__c);
                String body = 'Hi Imp Managers';
                body += '<br/>QA Review is Rejected  for '+ SOE.Name +':'+ SOE.SOE_Title__c +'<br/><br/> ';            
                body+= '<br/><br/> Regards,<br/>'; 
                    body+= '<b>'+UserInfo.getFirstName()+' '+UserInfo.getLastName()+'</b><br/>';  
                mail.setHtmlBody(body);
                mails.add(mail);
                count += AddList.SIze();
                Savepoint sp = Database.setSavepoint();
                try{
                    Messaging.reserveSingleEmailCapacity(Count);
                    Messaging.sendEmail(mails);
                }
                catch(Exception e){
                    Database.rollback(sp);
                    LogFactory.error('Review_Cntrl', 'QAFeedBack', '', e.getMessage() + '' + e.getStackTraceString());  
                    LogFactory.SaveLog(); 
                    statusmsg = e.getMessage();
                }
            }
            
            TaskUpdate();
            return new pagereference('/apex/AllTasks_ClientSide?id='+SOEID);
          }else{LogFactory.debug('Review_Cntrl', 'QA FeedBack', 'Task Info ', System.Label.ADDTask007,'Line - 140');
        LogFactory.SaveLog();}
        return null;
    }
    
    public pagereference WalkThroughComplete(){
        if(Task_Access_Update){
                Savepoint sp = Database.setSavepoint();
                try{
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('WalkThrough Completed');
                req.setAction('Approve');
                Id workItemId = getWorkItemId(SOE.Id); 
                if(workItemId == null)
                    SOE.addError('Error Occured ');
                else{       
                    req.setWorkitemId(workItemId);
                    Approval.ProcessResult result =  Approval.process(req);
                }
                if(Utils.isUpdateable('i8__Task__c'))
                update QA_TaskList;
                return new pagereference('/apex/AllTasks_ClientSide?id='+SOEID);
              }
                catch(Exception e){
                    Database.rollback(sp);
                    LogFactory.error('Review_Cntrl', 'WalkThroughComplete', '', e.getMessage() + '' + e.getStackTraceString());  
                    LogFactory.SaveLog(); 
                    statusmsg = e.getMessage();                  
               }
            }else{LogFactory.debug('Review_Cntrl', 'QA Complete', 'Task Info ', System.Label.ADDTask007,'Line - 168');
        LogFactory.SaveLog();}
           return null;    
        }
    public void TaskUpdate(){
        if(Task_Access_Update){    
              Savepoint sp = Database.setSavepoint();
                try{
                string comment;
                for(task__c tas : QA_TaskList){ 
                    if(tas.RV_Comments__c !=null){
                            comment = tas.Review_Comments__c; 
                            tas.Review_Comments__c ='';
                        if(string.isnotempty(comment))
                            tas.Review_Comments__c +=system.Now()+'-'+UserInfo.getFirstname()+':'+tas.RV_Comments__c+ '\n'+comment ;
                        else
                            tas.Review_Comments__c +=system.Now()+'-'+UserInfo.getFirstname()+':'+tas.RV_Comments__c; 
                        tas.RV_Comments__c ='';
                    }               
                }
                if(Utils.isUpdateable('i8__Task__c'))
                update QA_TaskList;
             }
             catch(Exception e){
                           Database.rollback(sp);
                           LogFactory.error('Review_Cntrl', 'TaskUpdate', '', e.getMessage() + '' + e.getStackTraceString());  
                           LogFactory.SaveLog(); 
                           statusmsg = e.getMessage();                  
            }  
         }else{LogFactory.debug('Review_Cntrl', 'QA Complete', 'Task Info ', System.Label.ADDTask007,'Line - 197');
        LogFactory.SaveLog();}
    }
    
    Public pagereference Cancel(){
        return new pagereference('/apex/AllTasks_ClientSide?id='+SOEID);
    }
}