temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_PlannedEnd__c</fullName>
        <label>Planned End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_PlannedStart__c</fullName>
        <label>Planned Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comp_Pre_Stacks__c</fullName>
        <label>Comp Pre Stacks</label>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Pre</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed, Completed-Jump</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Imp_Duration__c</fullName>
        <formula>TEXT( FLOOR( Max_Planned_End__c  - Min_Planned_Start__c ) ) &amp; &quot;d &quot; 
&amp; TEXT( FLOOR( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24, 24 ) ) ) &amp; &quot;h &quot; 
&amp; TEXT( ROUND( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24 * 60, 60 ), 0 ) ) &amp; &quot;m&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Imp Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Forecast_Start__c</fullName>
        <label>Min Forecast Start</label>
        <summarizedField>Task__c.Forecast_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Planned_Start__c</fullName>
        <label>Min Planned Start</label>
        <summarizedField>Task__c.Planned_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Not_Comp_Pre_Stacks__c</fullName>
        <label>Not Comp Pre Stacks</label>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Pre</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RAG__c</fullName>
        <formula>IF(TEXT(SOE_RAG__c) = &apos;Green&apos;,IMAGE(&quot;/resource/i8__rag_green&quot;,&quot;Green&quot;,23,23),

IF(TEXT(SOE_RAG__c) = &apos;Amber&apos;,IMAGE(&quot;/resource/i8__rag_amber&quot;,&quot;Amber&quot;,23,23),

IF(TEXT(SOE_RAG__c) = &apos;Red&apos;,IMAGE(&quot;/resource/i8__rag_red&quot;,&quot;Red&quot;,23,23),null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOE_RAG__c</fullName>
        <label>SOE RAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Amber</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MIS_AllSOEs_Cntrl.cls
/* 
Class Name        : MIS_AllSOEs_Cntrl
Test Class Name   : Test_MIS_AllSOEs_Cntrl
Purpose/Overview  : To Display All SOE's in that MIS in single view 
Author            : Purview Ltd.
Code Coverage     : 98%
Change History    : 

*/
public with sharing class MIS_AllSOEs_Cntrl{
    public MIS__c mis{get;set;}
    public list<SOE__c> SOEList;
    public list<SOE__c> SOEList1{get;set;}
    public i8Constants i8{get;set;}
    public boolean Freeze{get;set;}
    public boolean InProgress{get;set;}
    public boolean PreImp{get;set;}
    public boolean Schedule{get;set;}
    public string errormessage {get;set;}
    Id MISID ;
        
    public MIS_AllSOEs_Cntrl(){
        i8 = new i8Constants();
        PreImp = false;
        Schedule = false;
        MISID = ApexPages.CurrentPage().getParameters().get('id') ;
        if(Utils.isAccessible('I8__MIS__c') && Utils.isAccessible('I8__SOE__c')){
        mis = [select id,Name,MIS_Title__c,MIS_PlannedStart__c,MIS_PlannedEnd__c from MIS__c where id=: ApexPages.CurrentPage().getParameters().get('id')];
        SOEList1 = [select id,Name,Status__c,SOE_Title__c,Min_Planned_Start__c ,Max_Planned_End__c,SOE_RAG__c,RAG__c,Imp_Duration__c,Schedule_Start__c,
        Min_Forecast_Start__c,Max_Forecast_End__c,Dealy_Ahead_mins__c,OwnerId,Not_Comp_Pre_Stacks__c,Comp_Pre_Stacks__c,  
        BAU_Impact__c,Schedule_End__c,Max_End_Time__c from SOE__c where MIS__c =: ApexPages.CurrentPage().getParameters().get('id') order by Schedule_Start__c,Min_Planned_Start__c]; 
        for(SOE__c soe: SOEList1){
            if(soe.Status__c != i8.STATUS_FREEZE && soe.Status__c != i8.STATUS_IMPINPROGRESS && soe.Status__c != i8.STATUS_IMP_COMP && soe.Status__c != i8.STATUS_SOE_COMP){
                Freeze = false;
                break;
            }
            else if(soe.Status__c == i8.STATUS_FREEZE)
                Freeze = true;
        }
         for(SOE__c soe: SOEList1){
           if(soe.Status__c != i8.STATUS_IMPINPROGRESS && soe.Status__c != i8.STATUS_IMP_COMP && soe.Status__c != i8.STATUS_SOE_COMP){
               InProgress  = false;
               break;
           }
           else if(soe.Status__c == i8.STATUS_IMPINPROGRESS || soe.Status__c == i8.STATUS_IMP_COMP || soe.Status__c == i8.STATUS_SOE_COMP)
               InProgress = true;
        } 
      }else{ errormessage = System.Label.Admin001;}        
    }
    public void Execute(){
        try{
        if( Utils.isUpdateable('i8__SOE__c')   ) {  
            for(SOE__c soe: SOEList1){
                 if(soe.Not_Comp_Pre_Stacks__c != soe.Comp_Pre_Stacks__c){
                     PreImp = true;
                     break;
                 }
                 else if(soe.Schedule_Start__c > System.Now() || soe.Max_End_Time__c >= soe.BAU_Impact__c){
                     Schedule= true;
                     break;
                 }
             }
             if(PreImp == false && Schedule == false){
                 SOEList = new list<SOE__c>();
                 for(SOE__c soe: SOEList1){
                     if(soe.Status__c == i8.STATUS_FREEZE ){
                        soe.Status__c = i8.STATUS_IMPINPROGRESS;
                        SOEList.add(soe);
                     }
                 }            
                 LogFactory.Debug('MIS_ALlSOEs_Cntrl','Execute', 'SOE List', 'SOE Executed Successfully','Line - 65');
                 if(SOEList.size()>0){
                     if(Utils.isUpdateable('i8__SOE__c') )
                         update SOEList; 
                     list<id> SOEIds = new list<Id>();                   
                     for(integer i=0;i<SOEList.size();i++)
                         SOEIds.add(SOEList[i].id);
                     Task_TriggerHandler.UpdateAllTasks(SOEIds,i8.CONTEXT_IMP);
                 }
            }else{errorMessage =  System.Label.AddTask007;}
         }
         }Catch(Exception e){
             LogFactory.error('MIS_AllSOes_Cntrl','Execute','',e.getMessage() + ''+ e.getStackTraceString());             
         }
         LOgFactory.SaveLog();    
      }
     public pagereference Cancel(){
            if(UserInfo.getUiThemeDisplayed() == 'Theme3')
                return new PageReference('javascript:window.close()');
            else
                return new pagereference('/'+MISID );
    }
}