temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Min_Start_All__c</fullName>
        <label>Min Start All</label>
        <summarizedField>Task__c.Start_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Dependency_Type__c</fullName>
        <label>Dependency Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>IF(Days__c!=0,TEXT(Days__c) +&apos;d &apos;,&apos;&apos;)+ TEXT( Hours__c )+&apos;h &apos;+TEXT( Minutes__c )+&apos;m&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_Text__c</fullName>
        <label>ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Stack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Stack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Team_Member__c.Team__c</field>
                <operation>equals</operation>
                <valueField>$Source.Team__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stack_Owner_Name__c</fullName>
        <formula>Owner__r.Member__r.Name</formula>
        <label>Stack Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Level__c</fullName>
        <label>Stage Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>BackOut</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SOEResource_Gantt_Cntrl.cls
/* 
Class Name        : SOEResource_Gantt_Cntrl
Test Class Name   : Test_SOEResource_Gantt_Cntrl
Purpose/Overview  : To display the REsource Gantt Chart in that SOE.
Author            : Purview Ltd.
Code Coverage     : 100%.
Change History    : 
*/
global with sharing class SOEResource_Gantt_Cntrl {
    public Id SOEId{get;set;}
    public Id MISId{get;set;}
    public SOE__C soe{get;set;}
    public Id RecordId {get;set;}
    public DateTime MinDateTime{get;set;}
    
    public SOEResource_Gantt_Cntrl (){
        SOEId = ApexPages.CurrentPage().getParameters().get('id');
        MISId = ApexPages.CurrentPage().getParameters().get('Mid');
        if(Utils.isAccessible('i8__SOE__c')){
            if(MISId == null){
                soe = [select id,SOE_Title__C,Min_Start_All__c from SOE__c where id=: SOEId];
                MinDateTime  = soe.Min_Start_All__c ;
                RecordId  = soe.id;
            }
            else{
                AggregateResult[] groupedResults =  [SELECT  MIN(Min_Start_All__c ) LastDate FROM SOE__c WHERE MIS__C =: MISID  Group By MIS__c] ;       
                if(groupedResults.Size() > 0)
                    MinDateTime  = DateTime.valueof(groupedResults[0].get('LastDate'));
                RecordId  = MISID;
            }
        }
    }
    @RemoteAction    
    global static list<Task__c> getTasks(string sid) {
        List<Task__c> TaskList ;
        if(Utils.isAccessible('i8__Task__c')){
            if(sid.substring(0,3) == SOE__c.sobjecttype.getdescribe().getkeyprefix())
                TaskLIst = [select Task_Title__c,SOE__r.Name,id,Start_time__c,Stack_Owner_Name__c,End_Time__c,Owner__c,Minutes__c,Duration__c,Id_Text__c,Id_Before_Decimal__c,Is_Stack__c,Dependency_Type__c from Task__c where SOE__c =: sid and Stage_Level__c = 'Implementation' and IS_Stack__c = false order by Id_Before_Decimal__c,Id_After_Decimal__c];       
            else
                TaskLIst = [select Task_Title__c,SOE__r.Name,id,Start_time__c,Stack_Owner_Name__c,End_Time__c,Owner__c,Minutes__c,Duration__c,Id_Text__c,Id_Before_Decimal__c,Is_Stack__c,Dependency_Type__c from Task__c where SOE__r.MIS__c =: sid and Stage_Level__c = 'Implementation' and IS_Stack__c = false order by Id_Before_Decimal__c,Id_After_Decimal__c];       
        }           
        return TaskList;
    }
    public pagereference CancelPage(){
        if(MISID == null)
            return new pagereference('/apex/AllTasks_ClientSide?id='+SOEId);
        else
            return new pagereference('/apex/MIS_AllTasks?id='+MISID);
    }
}