temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_PlannedEnd__c</fullName>
        <label>Planned End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_PlannedStart__c</fullName>
        <label>Planned Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Imp_Duration__c</fullName>
        <formula>TEXT( FLOOR( Max_Planned_End__c  - Min_Planned_Start__c ) ) &amp; &quot;d &quot; 
&amp; TEXT( FLOOR( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24, 24 ) ) ) &amp; &quot;h &quot; 
&amp; TEXT( ROUND( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24 * 60, 60 ), 0 ) ) &amp; &quot;m&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Imp Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Planned_Start__c</fullName>
        <label>Min Planned Start</label>
        <summarizedField>Task__c.Planned_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Start_Time__c</fullName>
        <label>Min Start Time</label>
        <summarizedField>Task__c.Actual_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RAG__c</fullName>
        <formula>IF(TEXT(SOE_RAG__c) = &apos;Green&apos;,IMAGE(&quot;/resource/i8__rag_green&quot;,&quot;Green&quot;,23,23),

IF(TEXT(SOE_RAG__c) = &apos;Amber&apos;,IMAGE(&quot;/resource/i8__rag_amber&quot;,&quot;Amber&quot;,23,23),

IF(TEXT(SOE_RAG__c) = &apos;Red&apos;,IMAGE(&quot;/resource/i8__rag_red&quot;,&quot;Red&quot;,23,23),null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOE_RAG__c</fullName>
        <label>SOE RAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Amber</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/SOEPageHeader.cls
/* 
Class Name        : SOEPageHeader
Test Class Name   : Test_SOEPageHeader
Purpose/Overview  : To display SOE Header / MIS Header in all pages.
Author            : Purview Ltd.
Code Coverage     : 100%.
Change History    : 
*/
public with sharing class SOEPageHeader {
    public string SOEId{get;set;}
    public string MISID{get;set;}
    public List<MIS__c> MISObj{get;set;}
    public List<SOE__c> SOEObj{get;set;}
    
    public List<SOE__c> getSOE () {
        if(Utils.isAccessible('i8__SOE__c'))
        SOEObj = [select id,name,Max_Planned_End__c,SOE_RAG__c ,Max_Forecast_End__c,Min_Start_Time__c,Min_Planned_Start__c ,Imp_Duration__c,Max_End_Time__c,RAG__c,SOE_Title__c,State__c,Status__c,Dealy_Ahead_mins__c
                  from SOE__c where id=: SOEId];
        else SOEObj = new list<SOE__c>();
        return SOEObj;
    }    
    public List<MIS__c> getMIS () {
        if(Utils.isAccessible('i8__MIS__c'))
            MISObj = [select id,name,MIS_PlannedEnd__c,MIS_PlannedStart__c,MIS_Title__c from MIS__c where id=: MISID];
        else
            MISObj = new list<MIS__c>();
        return MISObj;
    }
}