temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Id_After_Decimal__c</fullName>
        <formula>IF(OR(LEN(ID_Text__c) == 1,LEN(ID_Text__c) == 2),0,VALUE(RIGHT(ID_Text__c,LEN(ID_Text__c)-FIND(&apos;.&apos;,ID_Text__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id After Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_Before_Decimal__c</fullName>
        <formula>VALUE(LPAD(ID_Text__c ,  FIND( &apos;.&apos;,ID_Text__c)))</formula>
        <label>Id Before Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/View_All_Documents_Cntrl.cls
/* 
Class Name        : View_All_Documents_Cntrl 
Test Class Name   : Test_View_All_Documents
Purpose/Overview  : To display the attachments for tasks with in that SOE. 
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class View_All_Documents_Cntrl {
    public list<task__C> tasklist{get;set;}
    public id Soeid{get;set;}    
    public list<SOE__c>  MISSOE_list{get;set;}
    public Set<Id> SOEIds{get;set;}
    public string SOEIdstring{get;set;}
    public list<wrapperclass> DocummentsList{get;set;}
    public boolean SOE{get;set;}
    
    public View_All_Documents_Cntrl(){
        DocummentsList = new list<wrapperclass>();
        Soeid = apexpages.currentpage().getparameters().get('id'); 
        SOEIds = new set<id>();      
        SOEIdstring = string.valueof(Soeid);        
        if(SOEIdstring.substring(0,3) == SOE__c.sobjecttype.getDescribe().getKeyPrefix()){
            SOE = true;
            SOEIds.add(SOEID);
        }
        else if(SOEIdstring.substring(0,3) == MIS__c.sobjecttype.getDescribe().getKeyPrefix()){
            SOE = False;
            if(Utils.isAccessible('i8__SOE__c')){
                MISSOE_list=[select id,MIS__c from SOE__c where MIS__c=:SOEID];            
                for(SOE__c MISESOE : MISSOE_list)
                    SOEIds.add(MISESOE.id);
            } 
        }
        if(Utils.isAccessible('i8__Task__c') && Schema.SobjectTYpe.Attachment.isAccessible()) {
            tasklist=[select id,Task_Title__c,Soe__r.Name,Soe__c,(select id,name,BodyLength,ownerid,createddate from attachments) from task__C where Soe__c IN: SOEIds order by Id_Before_Decimal__c,Id_After_Decimal__c];
        for(task__c tas:tasklist){
            for(attachment atth:tas.attachments)  
                DocummentsList.add(new wrapperclass(tas.Soe__r.Name,tas,atth));  
        } 
        }    
    }
    public class wrapperclass {
       public string soe{get;set;}
       public Task__c task{get;set;}
       public Attachment Att{get;set;}
       public wrapperclass(string soe1,Task__c  tas, Attachment att){
           this.soe = soe1;
           this.task = tas;
           this.Att = att;
       }
    } 
   public pagereference CancelTask(){          
        if(SOE == false)
            return new pagereference ('/apex/MIS_AllTasks?id='+SOEId);  
        else  
            return new pagereference ('/apex/AllTasks_ClientSide?id='+SOEId);
    }  
}