temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <fields>
        <fullName>MIS_PlannedEnd__c</fullName>
        <label>Planned End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_PlannedStart__c</fullName>
        <label>Planned Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIS_Title__c</fullName>
        <label>MIS Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOEs__c</fullName>
        <label>SOEs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MIS_DashBoards_Cntrl.cls
/* 
Class Name        : MIS_DashBoards_Cntrl 
Test Class Name   : Test_MIS_DashBoards_Cntrl
Purpose/Overview  : To display dashboards and reports
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class MIS_DashBoards_Cntrl {   
    public Id TaskReportId { get; set; }
    public Id IncidentReportId { get; set; }
    public Id MileStoneReportId  { get; set; }
    public Id CPReportId  { get; set; }
    public Id IncidentsByType{get;set;}   
    public Id LessonsLearned{get;set;}
    public Id AccessRequest {get;set;}
    public id MISID{get;set;}
    public MIS__c MIS{get;set;}
    Public String SOE_Names{get;set;}
    public string statusmsg{get;set;}

    public MIS_DashBoards_Cntrl(){
       Try{
        MISID= ApexPages.CurrentPAge().getParameters().get('Id');
        if(Utils.isAccessible('i8__MIS__c') && Utils.isAccessible('i8__SOE__c')) {
            MIS=[select id,Name,(select id,name from SOEs__r),MIS_PlannedEnd__c,MIS_PlannedStart__c,MIS_Title__c from MIS__c where id=:MISID];
        SOE_Names = '';
        If(MIS.SOEs__r.size() > 0){
            Integer i=1;
            For(SOE__c SOE : MIS.SOEs__r){
                If(i != MIS.SOEs__r.size())
                    SOE_Names += SOE.Name+',';
                Else
                    SOE_Names += SOE.Name;
                i++;
            }
        }
        if(Schema.SObjectTYpe.Report.isAccessible()){
        taskreportId  = [Select Id, Name From Report Where name='Task Status Report IN SOE'].Id;
        IncidentReportId  = [Select Id, Name From Report Where name='MIS Incidents By Status'].Id;
        MileStoneReportId  = [Select Id, Name From Report Where name='Milestone Tasks Report in SOE'].Id;
        CPReportId  = [Select Id, Name From Report Where name='Critical Path Tasks in SOE'].Id;
        IncidentsByType= [Select Id, Name From Report Where name='MIS Incidents By Type'].Id;       
        LessonsLearned = [Select Id, Name From Report Where name='Lessons Learned'].Id;
        AccessRequest = [Select Id, Name From Report Where name='SOE With AccessRequests'].Id;
        Reports.ReportDescribeResult descRes = Reports.ReportManager.describeReport(IncidentsByType);
        }
        }else statusmsg = System.Label.ADMIN001;
        }catch(Exception e){
           statusmsg = e.getMessage();                  
        }
    }
     public pagereference openCancel(){
        return new pagereference ('/apex/MIS_AllTasks?id='+MISID);
    } 
    public pagereference OpenReport(){
       return new pagereference('/apex/Report?id='+MISID+'&url='+taskreportId  );
    }    
}