temp/objects/MIS__c.object
<CustomObject>
    <description>Master Imp SOE</description>
    <label>MIS</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MIS  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MISs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/ROTA__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Desk_Phone__c</fullName>
        <label>Desk Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Manager_DeskPhone__c</fullName>
        <label>Manager DeskPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Mobile__c</fullName>
        <label>Manager Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Hours__c</fullName>
        <formula>((End_Date__c -  Start_Date__c )*24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>No of Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>ROTAs</relationshipLabel>
        <relationshipName>ROTAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_DeskPhone__c</fullName>
        <label>Secondary DeskPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Mail__c</fullName>
        <label>Secondary Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Secondary_Mobile__c</fullName>
        <label>Secondary Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Name__c</fullName>
        <label>Secondary Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>ROTAS (Secondary Team)</relationshipLabel>
        <relationshipName>ROTAS1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_Type__c</fullName>
        <label>Shift Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Call</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>ROTAS</relationshipLabel>
        <relationshipName>ROTAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>ROTA</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ROTA#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ROTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>MIS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIS</label>
        <referenceTo>MIS__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/Rota_Cntrl.cls
/* 
Class Name        : Rota_Cntrl 
Test Class Name   : Test_Rota_Cntrl
Purpose/Overview  : To dislay ROTA records that which resources are working 
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class Rota_Cntrl {
    public list<ROTA__c> RotaList { get;set;}
    public id Soeid{get;set;}
    public list<SOE__c>  MISSOE_list{get;set;}    
    public Set<Id> SOEIds{get;set;}
    public string SOEIdstring{get;set;}
    Public Boolean SOE{get;set;}
    public string errmsg {get;set;}
    
    public Rota_Cntrl(){
        Soeid = apexpages.currentpage().getparameters().get('id'); 
        SOEIds = new set<id>();      
        SOEIdstring = string.valueof(Soeid);        
        if(SOEIdstring.substring(0,3) == SOE__c.sobjecttype.getDescribe().getKeyPrefix()){
            SOE = True;
            SOEIds.add(SOEID); 
        }
        else if(SOEIdstring.substring(0,3) == MIS__c.sobjecttype.getDescribe().getKeyPrefix()){
            SOE = False;
            if(Utils.isAccessible('i8__MIS__c'))
                MISSOE_list=[select id,MIS__c from SOE__c where MIS__c=:SOEID];            
            for(SOE__c MISESOE : MISSOE_list)
                SOEIds.add(MISESOE.id); 
        }
        if(Utils.isAccessible('i8__ROTA__c'))
         RotaList = RotaList = [select id,name,Name__c,Team__c,Email__c,Desk_Phone__c,Mobile__c,Location__c,Secondary_Name__c,Secondary_Team__c,Secondary_Team__r.name,Secondary_Mobile__c,Secondary_DeskPhone__c,Secondary_Mail__c,Manager_Name__c,Manager_Email__c,Manager_Mobile__c,
               Manager_DeskPhone__c,Shift_Type__c,Start_Date__c,SOE__c,SOE__r.name,End_Date__c,Vendor__c,Application__c,Comments__c,No_of_Hours__c from ROTA__C where SOE__c IN: SOEIds];
        else
            errmsg = System.Label.ADMIN001; 
    }  
    public pagereference CancelTask(){          
        if(SOE == False )
            return new pagereference ('/apex/MIS_AllTasks?id='+SOEId);  
        else  
            return new pagereference ('/apex/AllTasks_ClientSide?id='+SOEId);
    }
}