temp/objects/Programme__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Programmes</relationshipLabel>
        <relationshipName>Programmes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programme</label>
    <nameField>
        <label>Programme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BackOut_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BackOut Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Baseline_Start__c</fullName>
        <label>Baseline Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Change_Record__c</fullName>
        <label>Change Request No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conference_Call_No__c</fullName>
        <label>Audio Call No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Implementation_Stage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Imp Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Department__c</field>
                <operation>equals</operation>
                <valueField>Programme__c.Department__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Programme__c</field>
                <operation>equals</operation>
                <valueField>Project__c.Programme__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SOEs</relationshipLabel>
        <relationshipName>SOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Baseline_Start__c</fullName>
        <label>Baseline Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SOE__c</fullName>
        <label>SOE</label>
        <referenceTo>SOE__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Imp</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Running&apos;,IMAGE(&quot;/resource/I8__Running&quot;,&quot;Running&quot;,20,20),
IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),
IF(TEXT(Status__c) = &apos;Waiting&apos;,IMAGE(&quot;/resource/I8__waiting&quot;,&quot;Pending&quot;,17,17),
IF(TEXT(Status__c) = &apos;Ready&apos;,IMAGE(&quot;/resource/I8__ready&quot;,&quot;Ready&quot;,21,22),
IF(TEXT(Status__c) = &apos;Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),
IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),
IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__schedule&quot;,&quot;Scheduled&quot;,20,20),
IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20), 
IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;ReRun&apos;,IMAGE(&quot;/resource/I8__rerun&quot;,&quot;ReRun&quot;,20,20),
IF(TEXT(Status__c) = &apos;To Be Released&apos;,IMAGE(&quot;/resource/I8__ToBeReleased&quot;,&quot;To Be Released&quot;,20,20),
IF(TEXT(Status__c) = &apos;Completed-Jump&apos;,IMAGE(&quot;/resource/I8__completedjump&quot;,&quot;completedjump&quot;,20,20),
IF(TEXT(Status__c) = &apos;Force Completed&apos;,IMAGE(&quot;/resource/I8__forcecomplete&quot;,&quot;Force Completed&quot;,18,18), 
IF(Jump__c = true,IMAGE(&quot;/resource/I8__jump&quot;,&quot;Jump&quot;,24,24),
null)))))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Email_Page_Cntrl.cls
/* 
Class Name        : Email_Page_Cntrl
Test Class Name   : Test_Email_Page
Purpose/Overview  : To send email to users  
Author            : Purview Ltd.
Code Coverage     : 93%
Change History    : 

*/
public with sharing class Email_Page_Cntrl{    
    public SOE__c SOE{get;set;}
    public list<Task__c> task{get;set;}
    public Map<Id,user> UserMap{get;set;}
    public list<Id> LeftUserList{get;set;}
    public list<Id> RightUserList{get;set;}
    public list<Id> LeftSelected{set;get;}
    public list<Id> RightSelected{get;set;}
    public string ExternalMails{get;set;}
    public string Title{get;set;}
    public String emailBody{get;set;}
    Public User curUser{get;set;}
    public string getid {get;set;}
    public boolean displayPopup {get; set;}
    public string selectaction{get;set;}
    public string page{get;set;} 
    public string ownermail{get;set;} 
    public string errormsg{get;set;}
    public Boolean SOE_Access;
    public Boolean Task_Access;
    public Boolean User_Access;  
    
    public Email_Page_Cntrl(){
        SOE_Access = Utils.isAccessible('I8__SOE__c');
        Task_Access = Utils.isAccessible('I8__Task__c');
        User_Access = Utils.isAccessible('User');
        errormsg = null;
        LeftUserList = new list<Id>();
        RightUserList = new list<Id>();
        UserMap = new Map<Id,user>();
        leftselected = new list<Id>();
        RightSelected = new list<Id>();
        selectaction = 'PDF';
        getid = ApexPages.CurrentPage().getParameters().get('Id');
        page = ApexPages.CurrentPage().getParameters().get('page');
        if(SOE_Access  && Task_Access && User_Access ){
        SOE = [select id,Name,SOE_Title__c,Summary__c,Baseline_Start__c,Conference_Call_No__c,Change_Record__c,Project__r.name,Programme__r.name,Department__r.name,BackOut_Stage__c,Post_Implementation_Stage__c,Pre_Implementation_Stage__c,State__c,Status__c From SOE__c where id =: getid];
        task = [select id,Stage_Level__c,SOE__r.SOE_Title__c,SOE__r.Name,Owner__r.Member__r.Email__c,Task_Title__c,Stage__c,Start_Time__c,Description__c,Duration__c,End_Time__c,State__c,ID_Text__c,Id_After_Decimal__c,Id_Before_Decimal__c,SOE__c,Status__c from task__c where SOE__c =: getid or SOE__r.MIS__c =: getid order by Id_Before_Decimal__c,Id_After_Decimal__c];
        Title = task[0].SOE__r.Name+': '+task[0].SOE__r.SOE_Title__c;
        for(Task__c tas : task){
            if(tas.Id_Text__c == ApexPAges.CurrentPage().getParameters().get('mail') && tas.Stage_Level__c == 'Implementation')
                ownermail = tas.Owner__r.Member__r.Email__c; 
        } 
        curUser = [select id,Name,email from user where id =: userinfo.getuserid()];
        for(User u: [select id, Name,Email from User where IsActive = true and id !=: userinfo.getuserid()]){
            UserMap.put(u.Id,u);
            LeftUserList.add(u.Id);
        }        
        ExternalMails = ownermail ;
        RightUserList.add(userinfo.getuserid());
        }else{errormsg = System.Label.ADMIN001;}
    }
    public list<SelectOption> getLeftUsers(){
        list<SelectOption> LeftList1 = new list<SelectOption>();
        for(Id i: LeftUserList){
            if(i == userinfo.getuserid())
                LeftList1.add(new SelectOption(i,CurUser.Name));
            else
                LeftList1.add(new SelectOption(i,UserMap.get(i).Name));
        }
        return LeftList1;
    }
    public list<SelectOption> getRightUsers(){
        list<SelectOption> RightList = new list<SelectOption>();
        for(Id i: RightUserList ){
            if(i == userinfo.getuserid())
                RightList.add(new SelectOption(i,CurUser.Name));
            else
                RightList.add(new SelectOption(i,UserMap.get(i).Name));
        }
        return RightList;
    }
    public void AddUsers(){
        errormsg = null;
        if(leftselected.size()>0){
            RightUserList.addAll(leftselected);
            for( integer i=0; i<LeftUserList.Size(); i++){
                for(Id j: leftselected){
                    if(LeftUserList[i] == j)
                        LeftUserList.remove(i);
                }
            }
        }
    }
    public void DeleteUsers(){
        errormsg = null;
        if(RightSelected.size()>0){
            LeftUserList.addAll(RightSelected);
            for( integer i=0; i<RightUserList .Size(); i++){
                for(Id j: RightSelected){
                    if(RightUserList [i] == j)
                        RightUserList .remove(i);
                }
            }
        }
    }
    public void AddAllUsers(){
         errormsg = null;
        if(LeftUserList.size()>0){
            RightUserList.clear();
            RightUserList.addAll(UserMap.keyset());
            LeftUserList.clear();
            RightUserList.add(userinfo.getuserid());
        }
    }
    public void DeleteAllUsers(){
         errormsg = null;
        if(RightUserList.size()>0){
            LeftUserList.clear();
            LeftUserList.addAll(UserMap.keyset());
            RightUserList.clear();
            LeftUserList.add(userinfo.getuserid());
        }
    }
    public pagereference SendMail(){
    if(SOE_Access  && Task_Access && User_Access ){
        errormsg = null;
        if( RightUserList.size() == 0  &&  ExternalMails == '')
            errormsg =System.Label.Email001;
        else if(emailbody == '' || emailbody == null )
            errormsg = System.Label.Email002;
        else {
            if(page != 'comm')
                displayPopup = true;
            else{
                Pagereference pag1 = selectformat();
                return pag1;
            }
        }
        }else{errormsg = System.Label.ADMIN001;}
        return null;
    }
    public pagereference reset(){
    if(SOE_Access  && Task_Access && User_Access ){
        errormsg = null;
        RightUserList.clear();
        LeftUserList.clear();
        LeftUserList.addAll(UserMap.keyset());
        RightUserList.add(userinfo.getuserid());
        ExternalMails = '';
        emailBody = '';
        }else{errormsg = System.Label.ADMIN001;}
        return null;
    }
    public void ClearRightUsers(){
        if(SOE_Access  && Task_Access && User_Access ){
        errormsg = null;
        RightUserList.clear();
        LeftUserList.clear();
        LeftUserList.addAll(UserMap.keyset());
        RightUserList.add(userinfo.getuserid());
        }else{errormsg = System.Label.ADMIN001;}
    }
    public pagereference Cancel(){
        if(page == 'detail'){
            if(UserInfo.getUiThemeDisplayed() == 'Theme3')
                return new PageReference('javascript:window.close()');
            else
                return new pagereference('/'+getid);
        }
        else
                return new pagereference('/apex/AllTasks_ClientSide?id='+getid);
        return null;
    }
    public list<selectoption> getselectformatoption(){
        list<selectoption> options = new list<selectoption>();
        options.add(new selectoption('PDF','PDF'));
        options.add(new selectoption('Excel','Excel'));
        return options;
    }
    public pagereference selectformat() {
      Savepoint sp = Database.setSavepoint();
        try{
        if(SOE_Access  && Task_Access && User_Access ){
        List<String> sendTo = new List<String>();
        string body='';
        if(RightUserList.size()>0){
            for(Id i: RightUserList){
                if(i == userinfo.getuserid())
                    SendTo.add(CurUser.Email);
                else
                    SendTo.add(UserMap.get(i).Email);
            }
        }
        if(ExternalMails != ''){
            List<String> SplitList = ExternalMails.split(',');
            SendTo.addAll(SplitList);
        }
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        Integer count =0;
        if(page != 'comm'){
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            body+='<html><body><table background-color="blue" style="font-size:16px;"><tr><th colspan="8">'+SOE.Name+' : '+SOE.SOE_Title__c+'</th></tr></table>';
            body+='<table>';
            body+='<tr><th  align="left">Description</th><td >';
              if(SOE.Summary__c != null)
                body+=SOE.Summary__c;
              else 
                body+= '-' ;
            body+='</td></tr>';
            body+='<tr><th align="left">Baseline Start</th><td>'+SOE.Baseline_Start__c+'</td></tr>';
            body+='<tr><th align="left">Change Request No</th><td >';
                if(SOE.Change_Record__c != null)
                    body+=SOE.Change_Record__c;
                else
                    body+= '-' ;
            body+='</td></tr>' ;
            body+='<tr><th align="left">Audio Call No</th><td>';
                if(SOE.Conference_Call_No__c!= null)
                    body+=SOE.Conference_Call_No__c;
                else 
                    body+= '-' ;
            body+='</td></tr>' ;
            body+='<tr><th align="left">Department</th><td>';
                if(soe.Department__r.name != null && soe.Department__r.name != '')
                    body+=SOE.Department__r.Name;
                else 
                    body+= '-' ;
            body+='</td></tr>' ;
            body+='<tr><th align="left">Programme</th><td>';
                if(soe.programme__r.name != null && soe.programme__r.name != '')
                    body+=SOE.programme__r.name;
                else 
                    body+= '-' ;
            body+='</td></tr>' ;
            body+='<tr><th align="left">Project</th><td>';
                if(soe.project__r.name != null && soe.project__r.name != '')
                    body+=SOE.project__r.name;
                else 
                    body+= '-' ;
            body += '</td></tr></table><table><tr><td></td></tr></table></br></br></br>';
            body+='<table border="1"><div><tr><th>SOE Context</th><th>ID</th><th>Task Title</th><th>Stage</th><th>Start Time</th><th>Duration</th><th>End Time</th></tr></div>';
            for(task__c t : task)
                body+='<tr><td>'+t.Stage_Level__c+'</td><td>'+t.ID_Text__c+'</td><td>'+t.task_Title__c+'</td><td>'+t.Stage__c+'</td><td>'+t.Start_Time__c+'</td><td>'+t.Duration__c+'</td><td>'+t.End_Time__c+'</td></tr>';
            body += '</table></body></html>';
            
            if(selectaction == 'PDF'){
                attach.setContentType('application/pdf');
                attach.setFileName('SOE Record.pdf');
                attach.Body = Blob.toPDF(body);
            }
            else{
                attach.setContentType('application/vnd.ms-excel');
                attach.setFileName('SOE Record.xls');
                attach.Body = Blob.Valueof(body);
            }
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach });
        }
        mail.setToAddresses(sendTo);
        count += sendTo.SIze();
        mail.setSubject(Title);
        mail.setHtmlBody(emailBody);        
        mails.add(mail);
            Messaging.reserveSingleEmailCapacity(Count);
            Messaging.sendEmail(mails);
        
        if(page == 'detail'){
            if(UserInfo.getUiThemeDisplayed() == 'Theme3')
                return new PageReference('javascript:window.close()');
            else
                return new pagereference('/'+getid);
        }
        else
            return new pagereference('/apex/AllTasks_ClientSide?id='+getid);
         }else{errormsg = System.Label.ADMIN001;}   
        }
        catch(Exception e){
            Database.rollback(sp);
            LogFactory.error('Email_Page_Cntrl', 'selectformat', '', e.getMessage() + '' + e.getStackTraceString());  
            LogFactory.SaveLog(); 
            errormsg = e.getMessage(); 
        }
        return null;
    }
    public void close(){
        displayPopup = false;
    }
}