temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Baseline_Start__c</fullName>
        <label>Baseline Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Imp_Duration__c</fullName>
        <formula>TEXT( FLOOR( Max_Planned_End__c  - Min_Planned_Start__c ) ) &amp; &quot;d &quot; 
&amp; TEXT( FLOOR( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24, 24 ) ) ) &amp; &quot;h &quot; 
&amp; TEXT( ROUND( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24 * 60, 60 ), 0 ) ) &amp; &quot;m&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Imp Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ThisWeekSOEs.cls
/* 
Class Name        : ThisWeekSOEs 
Test Class Name   : Test_ThisWeekSOEs
Purpose/Overview  : To display this week running SOEs in home page 
Author            : Purview Ltd.
Code Coverage     : 100%
Change History    : 

*/
public with sharing class ThisWeekSOEs {
    public List<SOE__c> SOEList{get;set;}
    
    public ThisWeekSOEs(){
        SOEList = new list<SOE__c>();
        if(Utils.isAccessible('i8__SOE__c'))
            SOEList = [Select id,name,SOE_Title__c,Baseline_Start__c,BAU_Impact__c,Imp_Duration__c,Schedule_Start__c,Schedule_End__c,Warning_Zone__c 
        from SOE__c where Schedule_Start__c = THIS_WEEK ];
    }
}