temp/objects/SOE__c.object
<CustomObject>
    <fields>
        <fullName>BAU_Impact__c</fullName>
        <inlineHelpText>Business As Usual Impact</inlineHelpText>
        <label>BAU Impact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <formula>(Total_Completed_Tasks_in_Imp__c / Total_Tasks_In_Imp__c ) * 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completed %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Time__c</fullName>
        <label>Current Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealy_Ahead_mins__c</fullName>
        <formula>IF(OR( ISPICKVAL(Status__c , &apos;Imp Completed&apos;)  ,ISPICKVAL(Status__c , &apos;SOE Completed&apos;) ),
 ( Max_End_Time__c -  Max_Planned_End__c ) * 24 * 60,
( Max_Forecast_End__c -  Max_Planned_End__c ) * 24 * 60  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealy/Ahead(mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Imp_Duration__c</fullName>
        <formula>TEXT( FLOOR( Max_Planned_End__c  - Min_Planned_Start__c ) ) &amp; &quot;d &quot; 
&amp; TEXT( FLOOR( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24, 24 ) ) ) &amp; &quot;h &quot; 
&amp; TEXT( ROUND( MOD( (Max_Planned_End__c  - Min_Planned_Start__c ) * 24 * 60, 60 ), 0 ) ) &amp; &quot;m&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Imp Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_End_Time__c</fullName>
        <label>Max End Time</label>
        <summarizedField>Task__c.End_Time__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Forecast_End__c</fullName>
        <label>Max Forecast End</label>
        <summarizedField>Task__c.Forecast_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Max_Planned_End__c</fullName>
        <label>Max Planned End</label>
        <summarizedField>Task__c.Planned_End__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Forecast_Start__c</fullName>
        <label>Min Forecast Start</label>
        <summarizedField>Task__c.Forecast_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Planned_Start__c</fullName>
        <label>Min Planned Start</label>
        <summarizedField>Task__c.Planned_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Min_Start_Time__c</fullName>
        <label>Min Start Time</label>
        <summarizedField>Task__c.Actual_Start__c</summarizedField>
        <summaryFilterItems>
            <field>Task__c.Stage_Level__c</field>
            <operation>equals</operation>
            <value>Implementation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Stage__c</field>
            <operation>equals</operation>
            <value>Imp</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Task__c.Is_Stack__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.SOE__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SOE_Title__c</fullName>
        <label>SOE Title</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedule_End__c</fullName>
        <label>Schedule End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule_Start__c</fullName>
        <label>Schedule Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(TEXT(Status__c) = &apos;Build&apos;,IMAGE(&quot;/resource/I8__build&quot;,&quot;Build&quot;,20,20),

IF(TEXT(Status__c) = &apos;Abandoned&apos;,IMAGE(&quot;/resource/I8__abandon&quot;,&quot;Abandoned&quot;,20,20),

IF(TEXT(Status__c) = &apos;Review&apos;,IMAGE(&quot;/resource/I8__Status/review.png&quot;,&quot;Review&quot;,20,20),

IF(TEXT(Status__c) = &apos;Scheduled&apos;,IMAGE(&quot;/resource/I8__Schedule&quot;,&quot;Scheduled&quot;,20,20),

IF(TEXT(Status__c) = &apos;SOE Completed&apos;,IMAGE(&quot;/resource/I8__ImpCompleted&quot;,&quot;Completed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Closed&apos;,IMAGE(&quot;/resource/I8__Iceflow/Closed.png&quot;,&quot;Closed&quot;,20,20),

IF(TEXT(Status__c) = &apos;Freeze&apos;,IMAGE(&quot;/resource/I8__Status/freeze.png&quot;,&quot;Freeze&quot;,20,20),

IF(TEXT(Status__c) = &apos;Suspended&apos;,IMAGE(&quot;/resource/I8__suspend&quot;,&quot;Suspended&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp Completed&apos;,IMAGE(&quot;/resource/I8__Complete&quot;,&quot;ImpCompleted&quot;,20,20),
IF(TEXT(Status__c) = &apos;BO In Progress&apos;,IMAGE(&quot;/resource/I8__BOInProgress&quot;,&quot;BO In Progress&quot;,20,20),
IF(TEXT(Status__c) = &apos;SOE BO completed&apos;,IMAGE(&quot;/resource/I8__SOEBOCompleted&quot;,&quot;SOE BO Completed&quot;,25,25),
IF(TEXT(Status__c) = &apos;BO Completed&apos;,IMAGE(&quot;/resource/I8__BOCompleted&quot;,&quot;BO Completed&quot;,20,20),
IF(TEXT(Status__c) = &apos;Imp In Progress&apos;,IMAGE(&quot;/resource/I8__InProgress&quot;,&quot;InProgress&quot;,20,20),null)
))))))))))))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Build</fullName>
                    <default>true</default>
                    <label>Build</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Imp In Progress</fullName>
                </value>
                <value>
                    <fullName>Imp Completed</fullName>
                </value>
                <value>
                    <fullName>BackingOut</fullName>
                </value>
                <value>
                    <fullName>BackedOut</fullName>
                </value>
                <value>
                    <fullName>BackoutClosed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>SOE Completed</fullName>
                </value>
                <value>
                    <fullName>BO In Progress</fullName>
                </value>
                <value>
                    <fullName>BO Completed</fullName>
                </value>
                <value>
                    <fullName>SOE BO Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warning_Zone__c</fullName>
        <label>Warning Zone</label>
        <type>DateTime</type>
    </fields>
    <label>SOE</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOEs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SOE_DashBoards_Cntrl.cls
/* 
Class Name        : SOE_DashBoards_Cntrl
Test Class Name   : Test_SOE_DashBoards_Cntrl
Purpose/Overview  : To display dashbords related to SOE.
Author            : Purview Ltd.
Code Coverage     : 87%.
Change History    : 
*/
public with sharing class SOE_DashBoards_Cntrl {
    public Id TaskReportId { get; set; }
    public Id IncidentReportId { get; set; }
    public Id MileStoneReportId  { get; set; }
    public Id CPReportId  { get; set; }
    public Id IncidentsByType{get;set;}   
    public Id LessonsLearned{get;set;}
    public Id AccessRequest {get;set;}
    public Id SOEID{get;set;}
    public SOE__C Soe{get;set;}
    public decimal CT{get;set;}
    public decimal PE{get;set;}
    public decimal PS{get;set;}
    public decimal FE{get;set;}
    public decimal ME{get;set;}
    public DateTime dt{get;set;}
    public i8Constants i8{get;set;}   
    public Integer green{get;set;}
    public Integer orange{get;set;}
    public Integer red{get;set;} 
    public string current{get;set;}
    public string statusmsg{get;set;} 
    
    public SOE_DashBoards_Cntrl (){
        try{
        i8 = new I8Constants();
        SOEId= ApexPages.CurrentPAge().getParameters().get('Id');
        if(Utils.isAccessible('i8__SOE__c'))
        Soe=  [select id,name,State__c,SOE_Title__c,Completed__c,Schedule_Start__c,Schedule_End__c,BAU_Impact__c,Warning_Zone__c,Min_Planned_Start__c,Max_Planned_End__c,Min_Forecast_Start__c,Status__c,Imp_Duration__c,Dealy_Ahead_mins__c,
        Max_Forecast_End__C,Max_End_Time__c,Min_Start_Time__c  from SOE__C where id=: SOEID];
        soe.Current_Time__c = System.Now();
        if(soe.Status__c != i8.STATUS_BUILD && soe.Status__c != i8.STATUS_REVIEW){
            integer total = Integer.valueof((soe.BAU_Impact__c.getTime() - soe.Schedule_Start__c.getTime())/(1000*60));
            green =  (Integer.valueof((soe.Schedule_End__c.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;
            orange =  (Integer.valueof((soe.Warning_Zone__c.getTime() - soe.Schedule_End__c.getTime())/(1000*60))*100) / total;
            red =  (Integer.valueof((soe.BAU_Impact__c.getTime() - soe.Warning_Zone__c.getTime())/(1000*60))*100) / total;
            if(green+orange+red <=100)
                red = 100-(green+orange);
            dt = System.Now();
            current = string.valueof(dt);
            PS = (Integer.valueof((soe.Min_Planned_Start__c.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;
            PE = (Integer.valueof((soe.Max_Planned_End__c.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;
            FE = (Integer.valueof((soe.Max_Forecast_End__c.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;
            if(Soe.Status__c == i8.STATUS_IMP_COMP || Soe.Status__c == I8.STATUS_SOE_COMP)
                ME = (Integer.valueof((soe.Max_End_Time__c.getTime() - soe.Min_Start_Time__c.getTime())/(1000*60))*100) / total;
            else if(Soe.Status__c == i8.STATUS_IMPINPROGRESS && soe.Min_Start_Time__c != null)
                ME = (Integer.valueof((dt.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;
            else
                ME = 0;
            if(PS > 100)
                PS= 100;
            if(PE > 100)
                PE= 100;
            if(FE > 100)
                FE= 100;
            if(ME > 100)
                ME= 100;
            if(Soe.Status__c == i8.STATUS_IMPINPROGRESS || Soe.Status__c == i8.STATUS_SCHEDULED || Soe.Status__c == i8.STATUS_FREEZE){
                CT = (Integer.valueof((dt.getTime() - soe.Schedule_Start__c.getTime())/(1000*60))*100) / total;           
                if(CT > 100)
                    CT = 100;
            }
            else if(Soe.Status__c == i8.STATUS_IMP_COMP || Soe.Status__c == I8.STATUS_SOE_COMP)
                CT = 100;
            else
                CT = 0;
        }
        else{
            green = 50; orange = 30; red = 20;
            PS = 0;PE =0;FE=0;ME=0;CT=0;
        }
        if(Schema.SOBjectType.Report.isAccessible()){
            taskreportId  = [Select Id, Name From Report Where name='Task Status Report IN SOE'].Id;
            IncidentReportId  = [Select Id, Name From Report Where name='Incident Status Report'].Id;
            MileStoneReportId  = [Select Id, Name From Report Where name='Milestone Tasks Report in SOE'].Id;
            CPReportId  = [Select Id, Name From Report Where name='Critical Path Tasks in SOE'].Id;
            IncidentsByType = [Select Id, Name From Report Where name='Incidents By Type'].Id;       
            LessonsLearned = [Select Id, Name From Report Where name='Lessons Learned'].Id;
            AccessRequest = [Select Id, Name From Report Where name='SOE With AccessRequests'].Id;
            Reports.ReportDescribeResult descRes = Reports.ReportManager.describeReport(AccessRequest);
        }        
        }
        catch(Exception e){
                   statusmsg = e.getMessage();                  
        }
    }   
    public pagereference openCancel(){
        return new pagereference ('/apex/AllTasks_ClientSide?id='+SOEId);
    } 
    public pagereference OpenReport(){
       return new pagereference('/apex/Report?id='+SOEId+'&url='+taskreportId  );
    }
}